### ISSUE TITLE
Examples depend on Humanizer

### ISSUE THREAD

**Issue by fergusontom** [App-vNext/Polly#109]
It would be useful to mention that your examples depend on Humanizer for this syntax

`2.Seconds()`

Its great syntax but took me a long time to work out what was providing these extensions.

**Comment by reisenberger** [comment]
@fergusontom Thanks for calling that out (and apologies for any confusion caused!).  We'll clarify that shortly.  

I'm assuming you're referring to the `WaitAndRetry(...)` examples in the main https://github.com/App-vNext/Polly/blob/master/README.md ? A quick search only brought up those examples for me - but let us know if you spied any others!

(The Polly specs are in fact pulling this syntax out of https://www.nuget.org/packages/FluentAssertions rather than Humanizer, but some syntax from the specs obviously got copied into the Readme without explanation.  Agree it's a great syntax!)

**Comment by reisenberger** [comment]
Fixed via #108
