### ISSUE TITLE
TimeoutRejectedException - naming?

### ISSUE THREAD

**Issue by silkfire** [App-vNext/Polly#1100]
This might be a bit of a strange question, but what is the reasoning behind the naming of the `TimeoutRejectedException`? Why is a timeout rejected here? Isn't the timeout _honoured_ or _reached_? A timeout is usually phrased as "Timed out when attempting to request the resource". Or simply... `TimeoutException`?

**Comment by PeterCsalaHbo** [comment]
*"There are only two hard things in Computer Science: cache invalidation and naming things."* -- Phil Karlton. L

I might not be the best person to answer your question because most probably Dylan Reisenberger (the original creator of Polly) could give more insight, but let me try to do my best here.

If you look at the [V7.x](https://github.com/App-vNext/Polly/blob/7.2.3%2B24/src/Polly/Timeout/TimeoutRejectedException.cs) or [V8](https://github.com/App-vNext/Polly/blob/b24fa883ec6881d9b7353620311919558281eec3/src/Polly.Core/Timeout/TimeoutRejectedException.cs#L13) version of the `TimeoutRejectedException` then you can spot that this exception is inherited from `ExecutionRejectedException`.
 - *BTW [this might be the original commit of the first version of the Timeout policy](https://github.com/App-vNext/Polly/commit/d8481dbb70f8c694a5532a7f5361843276e5f319#diff-20a463cf64f6f70addf7a644692e3b7c6e992207e7c7e130181044c324ac11ce)*
 
 The `ExecutionRejectedException` is an `abstract` class with the following documentation comment:
```cs
/// <summary>
/// Exception thrown when a policy rejects execution of a delegate.
/// <remarks>More specific exceptions which derive from this type, are generally thrown.</remarks>
/// </summary>
```
Reject or refuse - maybe it is just matter of taste. The idea here is that the decorated method is fizzle out / could not complete.

Beside the `TimeoutRejectedException` there are other derived classes as well:
- [`BulkheadRejectedException`](https://github.com/App-vNext/Polly/blob/b24fa883ec6881d9b7353620311919558281eec3/src/Polly/Bulkhead/BulkheadRejectedException.cs#L14)
  - Please note the name of the consumer delegate parameter  >> `onBulkheadRejected`
- [`RatelimitRejectedException`](https://github.com/App-vNext/Polly/blob/b24fa883ec6881d9b7353620311919558281eec3/src/Polly/RateLimit/RateLimitRejectedException.cs#L15)
- [`BrokenCircuitException`](https://github.com/App-vNext/Polly/blob/b24fa883ec6881d9b7353620311919558281eec3/src/Polly/CircuitBreaker/BrokenCircuitException.cs#L13)
  - This name is bit more expressive than `CircuitBreakerRejectedException` IMHO 

After all they are used to express that **the policy can't continue its work due to some of the pre-conditions are failed**.
___
>  Or simply... TimeoutException?

In .NET we already have [`TimeoutException`](https://learn.microsoft.com/en-us/dotnet/api/system.timeoutexception?view=net-7.0). So, we would name it like that then it would induce ambiguity.

**Comment by silkfire** [comment]
Thanks for the very elaborate and extensive answer, I really appreciate it. It makes things clearer now from a historical point of view.
