### ISSUE TITLE
WaitAndRetryAsync fails to wait and retry

### ISSUE THREAD

**Issue by jeroenwo** [App-vNext/Polly#111]
Hi,

I am trying to use Polly in an asynchronous fashion. I have a console application which imports data. The data is upserted async to DocumentDB.

This synchronous way works:
```
static void Main(string[] args)
{
    ImportDataTransiently();
}

private static void ImportDataTransiently()
{
    Policy
        .Handle<AggregateException>()
        .WaitAndRetry(5,
            retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
            (ex, timeSpan) =>
            {
                Console.WriteLine($"Exception: {ex.Message}");
                Console.WriteLine($"Retrying in {timeSpan.Seconds} seconds");
            })
        .Execute(() => UpsertDocumentAsync(documentCollectionLink, person).Wait());
}
```

This does not, the exception bubbles to the Task.Run. I would have expected the exception to be caught by Polly and retried:
```
static void Main(string[] args)
{
    Task.Run(async () => await ImportDataTransiently()).Wait();
}

private static async Task ImportDataTransiently()
{
    await Policy
        .Handle<AggregateException>()
        .WaitAndRetryAsync(5,
            retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
            (ex, timeSpan) =>
            {
                Console.WriteLine($"Exception: {ex.Message}");
                Console.WriteLine($"Retrying in {timeSpan.Seconds} seconds");
            })
        .ExecuteAsync(async () => await UpsertDocumentAsync(documentCollectionLink, person));
}
```
And the async method:
```
private static async Task UpsertDocumentAsync(Uri documentCollectionLink, TrajectoryPerson person)
{
    using (var documentClient = new DocumentClient(ConfigurationData.DocumentDbUri, ConfigurationData.DocumentDbKey))
    {
        var response = await documentClient.UpsertDocumentAsync(documentCollectionLink, person);

        Console.WriteLine($"{person.Name}: upsert of document consumed {response.RequestCharge} request units");
    }
}
```
What am I doing wrong?

**Comment by reisenberger** [comment]
Hey @jeroenwo !  I am travelling at the moment and haven't been able to test your code, but I think your code needs to take account of the different ways that `await Task` and `Task.Wait()` propagate exceptions.  

When you wait synchronously on a `Task` (such as with `.Wait()` or `.Result`), exceptions thrown are always wrapped in an `AggregateException`.  However, when you `await` a `Task`, original exceptions are rethrown at the `await` (not wrapped in an `AggregateException`).  For a detailed discussion, see [Stephen Toub on “Task.Result” vs “await task” Exception handling](http://blogs.msdn.com/b/pfxteam/archive/2011/09/28/10217876.aspx).

In the async version of your code, you only `.Handle<AggregateException>()`.  But your inner call `documentClient.UpsertDocumentAsync(...)` is presumably throwing some other exception (for discussion let's call it a `CannotUpsertException`).  Since the policy is only declared to handle `AggregateException`s, it doesn't handle the `CannotUpsertException`, and immediately rethrows it without retries, as you are observing.  

Then (in the code you posted), within `Main(...)` you eventually have a `.Wait()`, which causes the `CannotUpsertException` rethrown up the `await` call stack, to be wrapped in an `AggregateException` _at the point of that .Wait() only_ (perhaps making it look superficially as if an `AggregateException` was originally thrown all along - which I'm assuming is not the case).

So to fix: in the async version, just change `.Handle<AggregateException>()` to `.Handle<CannotUpsertException>()` (or whatever the inner work is throwing). 

If you have a number of possible exceptions you want the policy to handle, use Polly's `.Or<AnotherException>()` syntax.

Please let us know if this solves the issue for you!  (Or equally if not! - as I'm travelling, I've only had the chance to run your code through the virtual machine in my head... :smiley: )

**Comment by jeroenwo** [comment]
Wow, that VM of yours works like a charm! I changed the asynchronous code to catch every ``Exception`` and built a ``try {} catch {}`` to trap the actual exception. It is indeed not an ``AggregateException``, but a ``DocumentClientException`` (logical in hindsight)!

Thanks a lot @reisenberger for answering and your detailed explanation!

o/\o (virtual high five) :smile: 

Enjoy your travelling!
