### ISSUE TITLE
Using ExecuteAndCaptureAsync with continueWith

### ISSUE THREAD

**Issue by SeanFarrow** [App-vNext/Polly#121]
Hi,

I'm using .net 4 and need to use the HttpClient's GetAsync method wich returns a Task<HttpResponseMessage> How do I go about doing this using the ContinueWith method on Task?
Any help appreciated.
Kind regards
Sean.

**Comment by joelhulen** [comment]
Which version of .NET are you using, specifically? There's a huge difference between version 4.0 and 4.5/6

**Comment by SeanFarrow** [comment]
4.0.
Cheers
Sean.

**Comment by reisenberger** [comment]
Hi @SeanFarrow 

[This link](https://msdn.microsoft.com/en-us/library/dd321405(v=vs.100).aspx) suggests `Task.ContinueWith(...)` is available in .NET4.0.  You should be able to do something like:

```Task task = httpClient.GetAsync(url).ContinueWith(t => { /* some continuation code */ });```

How are you looking to slot this together with Polly?  What's the overall goal?  Or, do you have some code draft that's not working/compiling, to help us see what you are looking to achieve?

**Comment by SeanFarrow** [comment]
I[‘m trying ot use the HttpClient.GetAsync(url) using poly, then call a continuation with the result with is a HttpRequestMessage.

**Comment by joelhulen** [comment]
@SeanFarrow You're in luck, because we _just_ released a [new version](https://www.nuget.org/packages/Polly.Net40Async/) that adds async methods to Polly for those still using 4.0, via a dependency on the Microsoft BCL Async library.

For sample usage of the Async methods, please check out the [Polly-Samples](https://github.com/App-vNext/Polly-Samples) project. For a great set of videos on using Async and cancellation tokens, I highly recommend [this series](https://www.youtube.com/watch?v=0qiB3oW_nd8&list=PLdbkZkVDyKZWWjJ5yUdd_ooLORZgOSHSP) by Jeremy Clark.

**Comment by reisenberger** [comment]
@SeanFarrow 

Both `.ExecuteAndCaptureAsync(...)` and `.ContinueWith(...)` perform a similar function: both capture any exception thrown by an earlier-executed task into a result object which can be queried.  So, there is possibly little benefit in using `.ExecuteAndCaptureAsync(...)` and `.ContinueWith(...)` combined.  I constructed code to do it (happy to post), but it's unnecessarily double-layered for what it achieves.

To answer this another way, re your q:

>trying to use the HttpClient.GetAsync(url) using polly, 
>then call a continuation with the result with is a HttpRequestMessage

... this will not work directly, because the return type of `ExecuteAndCaptureAsync` is a `PolicyResult<HttpResponseMessage>` not an `HttpResponseMessage`.

To achieve a task-continuation where its `TResult` generic type is an `HttpResponseMessage`, I would suggest using the straightforward `.ExecuteAsync(...)` method with `.ContinueWith(...)`, not `.ExecuteAndCaptureAsync(...)`.  Something (in outline) like: 

```csharp
Policy retryPolicy = Policy.Handle<Exception>().RetryAsync(3);
string url = "some url";
using (HttpClient httpClient = new HttpClient())
{
        HttpResponseMessage response = await retryPolicy.ExecuteAsync(() => httpClient.GetAsync(url))
                .ContinueWith(t => !t.IsFaulted ? t.Result : null)
        // Do other stuff with response
}
```

This is not intended to be a finished example, just to address your question of combining `.ExecuteAndCapureAsync(...)` with a task-continuation.  A more refined example might do something with `response.IsSuccessStatusCode` or `response.EnsureSuccessStatusCode()`, depending what you're trying to achieve.  

Hope this helps!

**Comment by SeanFarrow** [comment]
Hi,

Ok, I’ve now got this working, so this can be closed.
It turns out that ExecuteAsync works really well for my purposes.
Cheers
Sean.

**Comment by reisenberger** [comment]
Thanks @SeanFarrow, glad it helped!.

For anyone reading in future or interested in how to use `HttpClient.GetAsync()` with `HttpResponseMessage.EnsureSuccessStatusCode()` with Polly, I put together this example (will add to wiki).  

Using a `.ContinueWith()` invoking `EnsureSuccessStatusCode()`, _within_ the Polly `ExecuteAsync(...)` call, is a nice way to catch the mix of exceptions and http status codes indicating failure, that `HttpClient.GetAsync()` might generate.

```csharp
PolicyResult<HttpResponseMessage> responseResult = await retryPolicy.ExecuteAndCaptureAsync(
                () => httpClient.GetAsync(url)
                    .ContinueWith(t =>
                    {
                        t.Result.EnsureSuccessStatusCode();
                        return t.Result;
                    }, TaskContinuationOptions.OnlyOnRanToCompletion)
                );
```

Comments:

+ In this case I _have_ combined `.ExecuteAndCaptureAsync()` with `.ContinueWith()`, as the `.ContinueWith()` is being used to throw exceptions, not absorb them.  
+ The use of `TaskContinuationOptions.OnlyOnRanToCompletion` avoids extra code to rethrow `t.Exception` from within the `.ContinueWith()` while preserving the stack-trace.
