### ISSUE TITLE
Polly Sync 4.2.3 lost support for Profile111 (the preferred xamarin profile)

### ISSUE THREAD

**Issue by robertbaker** [App-vNext/Polly#124]
Could not install package 'Polly.Net40Async 4.2.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by joelhulen** [comment]
@robertbaker I haven't checked the change logs, but was this profile previously supported by Polly? "Lost support" suggests this.

**Comment by robertbaker** [comment]
4.2.2 is what I have now and it works.

**Comment by robertbaker** [comment]
If you look at the commits you will see a lot of nuspec changes to the async package.

**Comment by robertbaker** [comment]
Actually, I removed the nuget Async package and just added regular polly and still have async. Guess I was using the wrong one.

**Comment by joelhulen** [comment]
Ah, yes. That makes sense. I was frantically looking through all of the changes in order to see where we may have accidentally removed support for that profile ;)

I assume you installed [the Polly.Net40Async](https://www.nuget.org/packages/Polly.Net40Async/) package instead of [the standard Polly](https://www.nuget.org/packages/Polly/) one?

I wonder if there's a better way for us to communicate which one to use?

**Comment by robertbaker** [comment]
In the readme you can add that package is only needed for .net 4.0. if you
are on 4.5+ there is no need for it. I was confused and thinking that
package is needed for asynx functionality
