### ISSUE TITLE
The new nuget package Polly 7.2.4 is not signed

### ISSUE THREAD

**Issue by elina-zh** [App-vNext/Polly#1323]
**Summary**: 
Nuget package Polly 7.2.4 is not signed

**Expected behavior**: 
Signed package.

**Actual behaviour**:
Not signed package.

**Steps / Code to reproduce the problem**: 
While trying to restore nuget package from the artifactory, I'm getting the following error:

Package 'Polly 7.2.4' from source '[https://api.nuget.org/v3/index.json'](https://api.nuget.org/v3/index.json%27): The package signature is invalid or cannot be verified on this platform.

**Comment by martincostello** [comment]
What operating system are you trying to validate the package signature on?

**Comment by martincostello** [comment]
As shown in the below screenshot, if I inspect the NuGet package with [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) on Windows, the package is signed with a valid signature:

![image](https://github.com/App-vNext/Polly/assets/1439341/0e0eb490-8468-46e4-b239-5afd9b21ac56)

**Comment by elina-zh** [comment]
> What operating system are you trying to validate the package signature on?

Linux

**Comment by martincostello** [comment]
I think you have an Artifactory issue here - the NuGet libraries only support package signature validation on Windows when a package is Authenticode signed. The exception is being [thrown from the NuGet client](https://github.com/mzalves/NuGet.Client/blob/b4c39f96856a62e1805f1236044778f4ca48f9f8/src/NuGet.Core/NuGet.Packaging/Signing/Verification/PackageSignatureVerifier.cs#L66-L70) because the code to validate package signatures is [conditionally complied](https://github.com/NuGet/NuGet.Client/blob/488693efb590056b7f9e07d3a376d17c60d7f9e6/src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs#L392-L473) and returns `false`/`null` as appropriate on non-Windows operating systems.

See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1219 for some more context on this.

The package itself _is_ signed.

**Comment by martincostello** [comment]
FYI, older versions of the .NET SDK fail to validate the package signature. More recent versions do not. See here for more information: https://github.com/App-vNext/Polly/issues/1333#issuecomment-1600955911
