### ISSUE TITLE
Feature Request: Add ability for Policies to react to return values, not just exceptions

### ISSUE THREAD

**Issue by ilmax** [App-vNext/Polly#14]
Hi,

I would like to have the ability to retry method that does not throw exception, in my case I have to do some work with a COM component. In some condition the method I'm calling return null and null is a non valid result for me. I would like to have the ability to retry this method if the result is null.

Best regards, Max.

P.S. Thanks for this great library!

**Comment by vincpa** [comment]
I suggest trying a library like Reactive Extensions. Going by your description it would solve your problem perfectly.

**Comment by joelhulen** [comment]
@ilmax, @DannyRyman:

Is this still an active issue for you? Have you considered using Reactive Extensions like @vincpa suggested?

This does bring up an interesting question as to what is constituted as an Exception for which the Polly framework is used. In your case, it's more a matter of something not returning an expected value, rather than an actual Exception. Is this something Polly should handle as well?

**Comment by reisenberger** [comment]
@joelhulen Extending Polly such that policies could handle/react to return values as well as exceptions could be useful, for example, in the case of calls to endpoints returning HTTP status codes.  eg Calls to RESTful endpoints might be indicating significant failure via 5xx http status codes rather than exceptions. We could look in to this in the longer-term.

**Comment by renzska** [comment]
I like this idea and hope that it gets added.

**Comment by DSanchen** [comment]
I would strongly appreciate this feature ! I'm not currently using Polly, but would, if it allowed to react on return values.
As I understand it, wrapping an expected function outcome into an exception would mean to also wrap the policy.Execute() call into a try/catch block, just to catch the wrapped function outcome (if it "failed") and "convert" it back to the original outcome... sounds weird :unamused:

**Comment by reisenberger** [comment]
@DSanchen Thanks for the feedback!  We are always seeking to understand how people are using or  would like to use Polly: what would your Use Case for reacting-to-return-values be?  (_Others reading this thread in future: feel free to contribute your Use Cases too so we can take into account!_).

And: in the [Polly roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap), there is a more detailed example of the proposed syntax for this feature.  Would this syntax work for you?

**Comment by DSanchen** [comment]
@reisenberger  I'm thinking about just reacting on return values, without handling any exception as in `Handle<something>`...
My use case aims at multithreaded applications that would try to reserve resources for some time and give up when not all of the resources are available after, say, 10 tries with a timeout of some 100ms in between the tries.
In my current project I have to access resources a, b, d, x, y from thread A, while another thread (B) might have access to b, c and e. When B releases access to b (and c and e), then A could continue working, otherwise it would tell the user to try again later (when B finished...). It is expected that A and B work concurrently, and it's no fault for either thread to say: hey I'm still busy, you can have your toy later - right now I'm using it.
So something like
```csharp
bool hasAccess = Policy
.HandleResult<bool>(r => r == false)
.Or<bool>(someCancelFlag == false)
.Retry(10)
.WithDelay(...)
.Execute(TryGetAccessToResources(ISet<...>));
if(!hasAccess) InformTheUserAndReturn(...);
/* work with the resources */
ReleaseResources(ISet<...>);
```

**Comment by reisenberger** [comment]
@DSanchen Thanks -good to see.  

_Others reading the thread later, feel free to share expected usage, how you would like to see this work, views on the syntax etc._

**Comment by tidusjar** [comment]
+1 👍

**Comment by reisenberger** [comment]
@ilmax @DannyRyman @renzska @DSanchen @tidusjar  PR #130 proposes an implementation of this feature: allow Polly policies to react to return values.  Please feel free to pull down the code of the PR and experiment if you wish.  Pending any feedback, I'd expect the feature to be released in the next week or so.  The main outstanding work before release is to add suitable documentation.  

Briefly, the additional syntax for policies-handling-return-results is designed to flow entirely fluently with existing syntax, eg: 

```csharp
int[] httpStatusCodesWorthRetrying = {408, 500, 502, 503, 504}; 
HttpResponse result = Policy
  .Handle<HttpException>()
  .OrResult<HttpResponse>(r => httpStatusCodesWorthRetrying.Contains(r.StatusCode))
  .Retry(...)
  .Execute<HttpResponse>( /* some Func<...,HttpResponse> */ )
```

Essentially, you have new methods `.HandleResult<TResult>(Func<TResult, bool>)`, `.OrResult<TResult>(Func<TResult, bool>)` alongside `.Handle<TException>(...)` and `.Or<TException>(...)`.   

Policies can be configured to handle both exceptions and return results (in the same policy), and exception- and result-handling can be expressed fluently in any preferred order.

The implementation handles return results natively rather than throwing handle-able results as exceptions.

**Comment by tidusjar** [comment]
Looks good. I'll give it a go and let you know.

**Comment by reisenberger** [comment]
Feature delivered: on Nuget as v4.3.0

**Comment by ilmax** [comment]
:tada:

**Comment by DSanchen** [comment]
:+1: Cool, coming back from holidays and finding this feature implemented ! Great work, Thanks !
