### ISSUE TITLE
Auto Reset of Policy after certain timeout

### ISSUE THREAD

**Issue by pvmraghunandan** [App-vNext/Polly#144]
Today we set the threshold of policy, there is no expiry after certain timeout. For example if we set timeout as 100, 100 is valid even if we get 100 exceptions in 10 days. Client can activate background task and do ResetCircuit periodically. But, it is very good option for the SDK to provide OOTB.

**Comment by reisenberger** [comment]
Hi @pvmraghunandan .  Thank you for your question and suggestion.

The [original Polly Circuit Breaker](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker) breaks only if the given number of handled exceptions is raised _consecutively_ (in consecutive calls through the circuit).   Therefore, there is not the risk of the number of exceptions building up and up over time, ever increasing, such that the circuit will eventually break.  Any successful call resets the breaker's internal count of exceptions to zero.  

I see that this (the original breaker's trigger being _consecutive_ exceptions) is in the [wiki](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker), but not in the readme and intellisense: I'll add it to the readme and intellisense, to make that clearer.

The [Advanced Circuit Breaker](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker) provides the feature you are asking for, a timeout on exceptions: the `samplingDuration` effectively acts as duration after which to 'forget'.  

There is a much deeper discussion of this and related issues in [this past thread](https://github.com/App-vNext/Polly/issues/41).  The [Advanced Circuit Breaker](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker) grew out of wanting to offer a 'trigger' measure that would be easier to configure for consistent results for high-throughput and variable throughput circuits.  And out of exactly the point you are raising: the ability to 'forget' exceptions beyond a certain duration.  The [discussion here particularly](https://github.com/App-vNext/Polly/issues/41#issuecomment-199251432) identifies why we chose the form Advanced Circuit Breaker has, effectively a hybrid of proportion-based and frequency-based, rather than a pure proportion-based or frequency-based metric.

**Comment by reisenberger** [comment]
@pvmraghunandan #145 will (when merged) clarify the doco on this issue.

**Comment by reisenberger** [comment]
Thanks again @pvmraghunandan for raising this.  Well worth clarifying this: we've made the doco on the original `CircuitBreaker` clearer through #145.

**Comment by pvmraghunandan** [comment]
@reisenberger  Thanks for clarifying. Will take a look on advanced circuit breaker once.

**Comment by pvmraghunandan** [comment]
@reisenberger Trying to understand SingleHealthMetrics and RollingHealthMetrics. Can you help us understand this and how does sampling and no.of windows work together?

**Comment by reisenberger** [comment]
@pvmraghunandan  Re:

>Trying to understand SingleHealthMetrics and RollingHealthMetrics. 
>Can you help us understand this and how does sampling and no.of windows work together?

See: https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker#detailed-operation-of-failure-statistics

The failure rate and throughput of the breaker is _always_ considered over `samplingDuration`.  Use of `SingleHealthMetrics` versus `RollingHealthMetrics` is purely an internal concern to smooth statistics.  

If `samplingDuration` > 200 milliseconds, the `samplingDuration` is divided internally into up to 10 windows of duration `samplingDuration / 10` each, to smooth the statistics.  This prevents disposing 100% of stats every `samplingDuration`; instead, 10% are disposed potentially every `samplingDuration / 10`.  This creates a _rolling_ statistical window of length `samplingDuration` which moves `samplingDuration / 10` forward every `samplingDuration / 10`, provided executions fall in those periods.  I say "up to", "potentially" and "provided", because the circuit does not waste cpu/memory creating empty windows for periods in which no execution occurred.  `RollingHealthMetrics` manages all this.

Why?  Smoothing using windows improves the breaker's _responsiveness_ and its _fidelity_ to its definition statement: that it will break if the failure and throughput thresholds are both met within **_any_**  timespan of duration `samplingDuration`.  

With no smoothing/windows - if 100% of stats were disposed every `samplingDuration` - it is easy to imagine situations where in real world the conditions to break were met, but because some of the faults fell in one `samplingDuration`, some in the next, the breaker did not detect this.  Equally, with no smoothing/windows, the breaker would potentially only tend to break towards the _end_ of each `samplingDuration`, once failures had built up - giving irregular responsiveness.

If `samplingDuration` < 200 milliseconds, the timescales are considered too small for dividing `samplingDuration` into windows to add any value.  `SingleHealthMetrics` is used internally.
