### ISSUE TITLE
Make the assembly CLS-Compliant

### ISSUE THREAD

**Issue by TrevorPilley** [App-vNext/Polly#159]
Is there reason that Polly isn't marked as CLS-Compliant?

For further info on CLS-Complaince, see https://msdn.microsoft.com/en-us/library/bhc3fa7f.aspx

**Comment by reisenberger** [comment]
@TrevorPilley Thanks for raising this.  

There's no reason the core Polly library is not marked as CLS-Compliant.  I just added the necessary attribute, and no issues were identified for Polly.dll in all the currently supported targets.

An issue was identified for xunit (`warning CS3016: Arrays as attribute arguments is not CLS-compliant`) on the `MemberData` attribute used for `Theory`s.  This is outside our control, but has no impact on the nuget packages: the tests don't form part of the nuget package.

We'll aim to get this attribute added for the v5.0 release.

**Comment by reisenberger** [comment]
Fixed in [Polly v5.0.2 on nuget](https://www.nuget.org/packages/Polly/5.0.2-v5-0-alpha0001)

The Polly.Net40Async remains non-CLS-compliant.  To support Bulkhead async for .NET40, we had to take a dependency on [Nito.Async](https://www.nuget.org/packages/Nito.AsyncEx/) (for .NET40 folks only).  This dependency is non-CLS-compliant.
