### ISSUE TITLE
.NET 3.5 Retry Policy Immediate Cancellation

### ISSUE THREAD

**Issue by OmegaAphex** [App-vNext/Polly#165]
I am currently using Polly in a .NET 3.5 framework environment. I am finding it difficult to find a way to immediately cancel the retry policy. As .NET 3.5 does not support cancellation tokens, how can this be done?

**Comment by reisenberger** [comment]
Hi @OmegaAphex  Are you wanting to:
 
**(a)** simply to **prevent the next try** beginning?; 
**(b)** cancel immediately **during any wait between retries**?; and/or 
**(c)** cancel immediately **during the executed delegate**?

**Comment by OmegaAphex** [comment]
B. Basically i want to immediately stop the retry policy as soon as a the windows service that it is currently running in stops.

**Comment by reisenberger** [comment]
@OmegaAphex As you say, this is not easy in .NET3.5, because of the lack of `CancellationToken`.  

Polly v4.3.0 has the waits in _synchronous_ `WaitAndRetry` implemented as a non-cancellable `Thread.Sleep`.  From Polly v5.0, we are moving these to cancellable - but again, using `CancellationToken` and `Task`.

If you are interested in attempting a back-port of this functionality to .NET3.5, you could:

+ Take a fork of the current Polly [v5.0-alpha branch](https://github.com/App-vNext/Polly/tree/v5.0-alpha), which contains the cancellation support (via `CancellationToken`) for synchronous executions, including `WaitAndRetry`
+ Re-instate a .NET3.5 target
+ Try bringing in a [.NET3.5 back port of the TaskParallelLibrary](https://www.nuget.org/packages/TaskParallelLibrary/) made available on NuGet, as described [here](http://stackoverflow.com/questions/22516303/how-can-i-get-the-equivalent-of-taskt-in-net-3-5).  **Caveat**: I have not had time to explore this.
+ You may well also need to remove the `async`/`await` material which is unlikely to be supportable in .NET3.5; or you could try this [.NET back port](https://www.nuget.org/packages/AsyncBridge.Net35/) from the same team.

Because of the age of .NET3.5, supporting this [has not been a primary focus](https://github.com/App-vNext/Polly/issues/142).  However, I would be willing to provide further support/guidance if you are interested in exploring making the above back-ports.  

_Suggestions from other members of the community (as always) welcome_
,

**Comment by OmegaAphex** [comment]
Thanks for the information. Will let you know.

**Comment by reisenberger** [comment]
Closing due to lack of response. Please re-open if wanting to take this further.
