### ISSUE TITLE
How do I use Polly v8 with .net 4.6.1 ? [Question]: 

### ISSUE THREAD

**Issue by kavin404** [App-vNext/Polly#1703]
### What are you wanting to achieve?

I have a project that uses Polly v7 with .net 4.6.1 and it works fine.  I was trying to upgrade the version to Polly v8 and I am getting dependency issues. Do you have any insight on how to use it on .net 4.6.1?

error : 

System.ComponentModel.Annotations, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### What code or approach do you have so far?

I have checked by adding a redirect as suggested by a stackoverflow answer but it didn't work

**Comment by martincostello** [comment]
As of Polly v8, our minimum supported Target Framework Moniker for .NET Framework is v4.6.2. We also support .NET Standard 2.0 for "modern" .NET as a minimum.

Without being able to look at the code with your project, I would have thought the lowest friction way to use it is to upgrade to target .NET Framework 4.6.2 or later.

If you are still using the "old" Polly API and cannot upgrade (or find a way to make it work) then I wouldn't worry too much about upgrading - the changes in Polly.dll in version 8.0.0 are negligible. The focus of the v8 release was introducing the new API surface.

**Comment by kavin404** [comment]
Thank you for your response. Is there a major performance improvement/bug fixes if I upgrade from v7.2.3  to v8.0.0?

**Comment by martincostello** [comment]
Moving to the brand new Polly v8 API (in Polly.Core.dll) will likely give you improved performance - you can see [some benchmark results here](https://github.com/App-vNext/Polly/tree/main/bench#readme).

Just upgrading the NuGet package but not otherwise making any code changes (i.e. still using Polly.dll) is unlikely to have any significant impact.

7.2.4 is the latest release for Polly v7.
