### ISSUE TITLE
What is the best way to Handle System.AggregateException?

### ISSUE THREAD

**Issue by mmoroni** [App-vNext/Polly#191]
I'm trying to use Polly to implement a retry logic to my requests using System.Net.Http.HttpClient, but this class is throwing AggregateExceptions and not SocketExceptions / WebExceptions...

Thank you!

**Comment by reisenberger** [comment]
Hi.  Polly offers predicate-filtering on exceptions, as described [here](https://github.com/App-vNext/Polly#step-1--specify-the-type-of-exceptions-you-want-the-policy-to-handle).  You can apply this to the [InnerExceptions property of AggregateException](https://msdn.microsoft.com/en-us/library/system.aggregateexception.innerexceptions(v=vs.110).aspx) to filter for a wrapped exception.  For example:

```
Policy
   .Handle<MyException>()
   .Or<AggregateException>(e => e.InnerExceptions.Any(i => i is MyException)) // handle the same exception if wrapped
```

You can additionally use [`AggregateException`s Flatten() method](https://msdn.microsoft.com/en-US/library/system.aggregateexception.flatten(v=vs.110).aspx) if there may be any nested `AggregateException`s.

`AggregateException`s can also often be reduced by making sure you are calling async methods with `await` (which throws exceptions directly), rather than `.Wait()` (or other calls similarly synchronously blocking on a `Task`) (which wrap exceptions in `AggregateException`). (This may or may not be relevant depending on the construction of your code.)

**Comment by mmoroni** [comment]
Thank you!
