### ISSUE TITLE
[Question]: Usage of ExecuteOutcomeAsync

### ISSUE THREAD

**Issue by troygould-stack** [App-vNext/Polly#2025]
### What are you wanting to achieve?

Reading the documentation for `ResiliencePipeline<T>.ExecuteOutcomeAsync`, and [in the remarks section](https://github.com/App-vNext/Polly/blob/083b644dea56bb59a998a92de453ac075bfe34cc/src/Polly.Core/ResiliencePipelineT.Async.cs#L98) it mentions "The caller must make sure that the `callback` does not throw any exceptions. Instead, it converts them to `Outcome<TResult>`."

When I jump through the source code, I end up in the `RetryResilienceStrategy` which uses the `StrategyHelper`. Within the `StrategyHelper`,[ it has a try/catch ](https://github.com/App-vNext/Polly/blob/083b644dea56bb59a998a92de453ac075bfe34cc/src/Polly.Core/Utils/StrategyHelper.cs#L29) around the call to the callback method. Thus, when using `ExecuteOutcomeAsync`, a user isn't _required_ to catch `Exceptions` and call `Outcome.FromException<TResult>(exception)` themselves. The Polly framework already does this.

This is causing some confusion on whether or not we need to add a try/catch blocks within the callback, and return an `Outcome` with `Exception` property set, or just let the Polly framework do it for us. Some guidance on this would be appreciated. 

### What code or approach do you have so far?

Catching exceptions within the callback requires me to be very careful about what exceptions I do catch because this can interfere with the `ShouldHandle` method of of a retry strategy.

**Comment by peter-csala** [comment]
I've put together two simple unit tests.
```cs
[Fact]
public async Task ThrowNotHandledException()
{
    //Arrange
    const int expectedRetryCount = 0;
    int actualRetryCount = 0;
    var context = ResilienceContextPool.Shared.Get();
    var retry = new ResiliencePipelineBuilder<int>()
    .AddRetry(new () {
        ShouldHandle = new PredicateBuilder<int>().Handle<MyException>(),
        MaxRetryAttempts = 3,
        OnRetry = _ =>
        {
            actualRetryCount++;
            return default;
        }
    }).Build();

    //Act
    Outcome<int> actual = await retry.ExecuteOutcomeAsync<int, string>((ctx, stt) => throw new Exception("blah"), context, "a");
    ResilienceContextPool.Shared.Return(context);

    //Assert
    Assert.Equal(expectedRetryCount, actualRetryCount);
    Assert.IsType<Exception>(actual.Exception);
}
```
```cs
[Fact]
public async Task ThrowHandledException()
{
    //Arrange
    const int expectedRetryCount = 3;
    int actualRetryCount = 0;
    var context = ResilienceContextPool.Shared.Get();
    var retry = new ResiliencePipelineBuilder<int>()
    .AddRetry(new () {
        ShouldHandle = new PredicateBuilder<int>().Handle<MyException>(),
        MaxRetryAttempts = 3,
        OnRetry = _ =>
        {
            actualRetryCount++;
            return default;
        }
    }).Build();

    //Act
    Outcome<int> actual = await retry.ExecuteOutcomeAsync<int, string>((ctx, stt) => throw new MyException(), context, "a");
    ResilienceContextPool.Shared.Return(context);

    //Assert
    Assert.Equal(expectedRetryCount, actualRetryCount);
    Assert.IsType<MyException>(actual.Exception);
}
```
Yes, it seems like we don't need to wrap the Exception explicitly into an `Outcome`.

But let's double-check this with @martintmk

**Comment by martintmk** [comment]
Unfortunately, this won't work 100%. For example this piece of code fails:

``` csharp
var outcome = ResiliencePipeline.Empty.ExecuteOutcomeAsync<string, string>(
    (_, _) => throw new InvalidOperationException(),
    ResilienceContextPool.Shared.Get(),
    "dummy");
```

To fix this, try catch needs to be added here and the :
https://github.com/App-vNext/Polly/blob/f99a4cea335ab7891ea6b56284b1d8e47f8e63ab/src/Polly.Core/ResiliencePipeline.AsyncT.cs#L32

Basically, we need to define a static lambda and call `callback` inside it with try/catch block. The reason why I haven't done this is tht async machinery adds constant overhead (around 40ns) on my machine and since this was intended to be high-performance API I thought it's not necessary there.

**Comment by peter-csala** [comment]
> @peter-csala Your example works by luck because the retry strategy does exception handling inside. if you added other strategy (custom for example) the test would fail.

I did not know that. Thanks for calling it out!

**Comment by martintmk** [comment]
We can handle this on Polly level, the question is whether we want to take a perf hit @martincostello, @peter-csala ?

**Comment by martincostello** [comment]
Is there a way to make this opt-in somehow?

I think we'd only want to "spend" some of our theoretical performance budget on making the change for all usage if this is proving a common stumbling block for people.

**Comment by peter-csala** [comment]
I think we can agree on that the current situation is sub-optimal. Asking the caller via a documentation comment to wrap the exceptions into `Outcome` objects is not ideal.

Even though the use of `ExecuteOutcomeAsync` is considered as advanced scenario I still think that every public API should be easy to use, safe and then performant.  Because C# allows you to simply `throw` the exception rather than requiring to wrap it into an `Outcome` object I think it is the library's responsibility to handle this case gracefully as well.

### opt-in vs opt-out

I would personally vote for opt-out instead of opt-in. The default behavior should work with `throw` statements as well. But when all nanoseconds and bytes matter then you can turn off the "safe guard" and it let run without the `try-catch`.

**Comment by troygould-stack** [comment]
As the author of this question, I like that you are putting yourselves in the user's shoes. Thanks for thinking this through. IMO, I think it should work the same for all strategies if possible. Adding some user documentation around opt-in and opt-out is a great idea to add clarity to the situation as well.

**Comment by ben-page-csat** [comment]
I think this should be reopened.

**Comment by ben-page** [comment]
@peter-csala Can this be reopened?

**Comment by peter-csala** [comment]
I'm not the one who can decide this. 

@martincostello what do you think?

**Comment by martincostello** [comment]
What is the goal of re-opening it? What is the intended outcome?
