### ISSUE TITLE
What's the origin of the name Polly?

### ISSUE THREAD

**Issue by michaldivis** [App-vNext/Polly#2158]
Hi, for a few months I've been curious about something. Is this library named after Polly parrot from Peppa Pig? Thanks!

**Comment by martincostello** [comment]
As far as I'm aware, it came about from the use of the term _Policy_ in the API as the entry point for creating the operations like retry, timeout etc. (since Polly v8 we call these _resilience strategies_). Policy => Polly => _"Polly want a cracker"_ => parrot logo

Maybe another maintainer who's been on the project for longer than myself knows more about the origin of the name. I'm certainly not aware of any association with Peppa Pig 😄

**Comment by peter-csala** [comment]
CC: @michael-wolfenden

**Comment by michaldivis** [comment]
Thanks for all the replies, it totally makes sense when you put it like that. I just thought that Polly parrot also existing in Peppa Pig couldn't be a coincidence 😅
