### ISSUE TITLE
Refining the logic for passing from half-open state to closed state

### ISSUE THREAD

**Issue by g7ed6e** [App-vNext/Polly#239]
Hi and thanks for the great work.
I need to apply a policy when the circuit is in half-open state in order to prevent closing too quickly.
I don't think this feature is in the roadmap today, would it be possible to add it ?
Please see below the part that should be modified. 
![be448f2c-181e-11e6-925f-700121d39ddc](https://cloud.githubusercontent.com/assets/681739/24238164/9c8bd934-0fa9-11e7-8811-e1beb71756b4.PNG)

**Comment by reisenberger** [comment]
Hi @railarmenien , thanks for this.  It would be good to understand your thinking / need more clearly.  What factors are you thinking could be useful to govern the transition back from `HalfOpen` to `Closed` state?  And: what is the real-world scenario driving this?  (all helps us think around how tackle).  Thanks!

**Comment by railarmenien** [comment]
Hi @reisenberger. 
I would need either to apply a consecutive success count check or a sampling check before transitionning back to `Closed` state.
The real world scenario is a service hosted in a farm behind a load balancer. Once one node is down the load will be processed by the remaining ones, increasing the response time and leading sometimes to timeout. In this scenario i would have to have fine grained control over the behavior of the `CircuitBreaker` not necessarily applying the governance strategy of the `Closed` to `Open` transition which is the behavior i will get if the first call of the `HalfOpen` results to a timeout.
Regards

**Comment by reisenberger** [comment]
@railarmenien  I understand the logic that if fewer nodes are available behind a load-balancer, the response times of calls could increase (assuming the system is in some sense close to capacity?), but I am not clear how you are seeking the circuit to behave differently in light of that assumed greater potential for timeouts.  

Are you thinking that the circuit should be more 'lenient' (to make allowances for timeouts being higher, and not break again so easily), or more 'strict' (eg to return to closed less readily, and/or break more easily?)

**Comment by railarmenien** [comment]
@reisenberger let's assume the circuit broke before a node fall indeed due to a load close to maximum capacity. Then, before opening gates to consumers (i.e passing from `HalfOpen` to `Closed` state), i would like to ensure the fallen node had enough time to recover not to broke again immediately. So to measure the parameter "the fallen had enough time to recover" i would like to be able to apply a policy/strategy here (more or less strict, that's to be defined). 
My thinking is that we should be able to setup a primary threshold leading to the transition from `Closed` to `Open` state and also a secondary threshold leading to the transition from `HalfOpen` to `Closed`. This pattern is described here http://blog.octo.com/circuit-breaker-un-pattern-pour-fiabiliser-vos-systemes-distribues-ou-microservices-partie-2/ (in french I apologize) and brings to light the idea
of allowing a few requests to try to reach backend instead of only one when in `HalfOpen`state.

**Comment by reisenberger** [comment]
Perfect @railarmenien : glad we are talking about the same thing!  Had just wanted to clarify following your [timeout comments](https://github.com/App-vNext/Polly/issues/239#issuecomment-289372837), because a consecutive success metric at `HalfOpen` can _only_ make the circuit stricter (more likely to break again).  Completely understand the concept (mais merci aussi pour l'article: pas de probleme a lire en francais!)

@railarmenien We would be very happy for a PR on this if you want to work on one!

[Consecutive count circuit-breaker](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker) seems relatively straightforward:

+ **Consecutive success count** (as you say) is the appropriate metric to refine `HalfOpen` to `Closed` for a count-based breaker.  
+ `HalfOpen` state must limit the calls _placed_ as well as measuring incoming results.  Otherwise the `HalfOpen` state is vulnerable to request stampedes: see #216 (an inherited bug which we squashed very quickly!).  If the **consecutive success count** metric required to close again is _N_, we should also limit calls _placed_ to _N_.
+ That limit on calls placed in the `HalfOpen` state should be _N_ calls _per `breakDuration`_.  As [@kharos rightly pointed out](https://github.com/App-vNext/Polly/issues/216#issuecomment-275391582), a `HalfOpen` state should try to place more calls periodically, in case the earlier calls have hung.  

So the specification (as we might document it in the wiki) would become:

>When the circuit is half-open and the `consecutiveSuccessRecoveryThreshold` is specified (call it _N_):
> + the circuit will permit _N_ further calls to be placed per `breakDuration`, as trial calls to determine the circuit's health
> + if the circuit receives _N_ consecutive successes, the circuit will transition back to `Closed`.  
> + if any failures occur before _N_ successes is reached, the circuit will transition immediately back to `Open` again for the configured timespan.

[AdvancedCircuitBreaker](https://github.com/App-vNext/Polly/wiki/Advanced-Circuit-Breaker) case seems more nuanced:

+ For the new metric controlling `HalfOpen` to `Closed`, my thought is that users would specify only one additional parameter `double recoveryThreshold` (not additional values for all three parameters which govern `Closed` state). 
+ `double recoveryThreshold` would again be a percentage of failure.  eg If a user specified `failureThreshold: 0.4, recoveryThreshold: 0.2`, they would be specifying that they want the failure rate through the circuit to fall from 40% to 20% before the circuit closes again.
+ The `HalfOpen` state still exists to place only _limited_ calls, to determine (in a protective way) if the underlying operation has recovered.  It should limit calls to the minimum necessary to determine whether the failure rate falls below `recoveryThreshold`: in this case, _N_ calls, where _N_ is the `minimumThroughput` which the user defined to make circuit metrics statistically significant.  
  - The `samplingDuration` parameter becomes irrelevant to the `HalfOpen` state.  If the `HalfOpen` state permitted calls for `samplingDuration`, it again invites the problem of a request stampede against a recovering/struggling system.
+ For same reasons as earlier, that limit on calls placed in the `HalfOpen` state should be _N_ calls _per `breakDuration`_. 

Thoughts? Could we do anything differently?  _Community views?_

(I had pondered adding this when we last refactored the breaker engine in January, but held off because of some of the nuances of the `AdvancedCircuitBreaker` case.)

**Comment by pvmraghunandan** [comment]
We are also planning to use in high throughput telemetry ingestion in IoT scenarios which involves business processing and communication with different external systems which are out of our control. We want to use circuit breaker there but at the same time we would like to limit no.of calls (i.e. only allow X calls even if requests are more) during Half-Open and then have different configuration on Half-Open i.e. No.of calls, threshold, duration, minimum throughout incase of Advanced for fine grade control.

**Comment by reisenberger** [comment]
_(triage of open issues)_

This (refining the metrics governing exiting half-open) remains a good possible addition to the circuit-breaker.

Because of the core Polly team's desire to deliver events/metrics as the next major feature, the core team hasn't time to work on this #239 at the moment.  Community contributions remain welcome. @reisenberger provided a possible specification/_starting point for discussion_ [above](https://github.com/App-vNext/Polly/issues/239#issuecomment-292710948)

**Comment by reisenberger** [comment]
Removing the 'up-for-grabs' label from this. I would prefer to next develop the circuit-breaker by more cleanly factoring out an `ICircuitStateController` and `ICircuitStateStore`, to facilitate high-priority features like #287 (Distribitued breaker for serverless/actors scenario).  The feature in this issue (refining exit from half-open state) would then become an option (also easier to implement) of a custom `ICircuitStateController` (rather than adding more features to the existing pre-defined circuit-breakers).

**Comment by reisenberger** [comment]
Closing due to no further community request/comment over 24 months.

**Comment by djkarlos** [comment]
Just wondering whether anything came of this since it was closed? I too am looking for a way to transition from HalfOpen back to closed based on a threshold of successful responses rather than just on a single success.
