### ISSUE TITLE
question: Retry policy with action upon failure

### ISSUE THREAD

**Issue by grokky1** [App-vNext/Polly#266]
New user here, loving this library so far... kudos!

I'm using a delay and retry policy, something like this:

````csharp
var policy = Policy
  .Handle<Exception>()
  .WaitAndRetry(10, sleep, () => {
    // do something after retry failure
  });
var policyResult = await policy.ExecuteAndCaptureAsync(() => DoSomething());
````

What I need to do is log before each retry, and log after the last failure. For the before case, there is the `onRetry` delegate... but what about the after case?

I haven't found anything, so I append this to the code above:
````csharp
if (policyResult.Outcome == OutcomeType.Failure) {
  // do something after last failure
}
````

This works, but it isn't reusable. I want to be able to define a `Policy` instance, and pass it around.

Is there an overload I've missed, or some way to do this? It would have been awesome if the library had a callback for the after case, something like `"onLastFailure"`.

**Comment by reisenberger** [comment]
Hi @grokky1 , thanks for joining the Polly conversation!  

Re logging a final failure from a policy operation: We could / could have added an extra `onLastFailure` delegate to the retry policies, but opted to provide similar functionality through [`FallbackPolicy`](https://github.com/App-vNext/Polly/wiki/Fallback).  `FallbackPolicy` targets code you want to run if an overall operation still fails, and is typically used as the outermost layer of a [`PolicyWrap`](https://github.com/App-vNext/Polly/wiki/PolicyWrap).  It serves the same purpose as   `onLastFailure`, but can be used after any policy type (or wider resilience strategy expressed as a `PolicyWrap`).

The main intent of `FallbackPolicy` is to provide a substitute value/code-to-run in the case of overall failure. It also provides an [`onFallback`](https://github.com/App-vNext/Polly/wiki/Fallback#onfallback) delegate, which can be used like the `onRetry` delegate for general concerns such as logging.  To make a combined policy you can pass around, use [`PolicyWrap`](https://github.com/App-vNext/Polly/wiki/PolicyWrap) to wrap your `FallbackPolicy` outside the retry:  

```
var retryPolicy = ...
var fallbackPolicy = ...
var retryWithFallback = fallbackPolicy.WrapAsync(retryPolicy);

// elsewhere:
var result = await retryWithFallback.ExecuteAsync(...)
```

If you want to provide _different fallback values/executions for different call sites_, but re-use the same `onFallback` delegate for common logging, see the **Theme and variations** approach noted in [this blog post](http://www.thepollyproject.org/2016/10/25/polly-5-0-a-wider-resilience-framework/).

A minor wrinkle is that `ExecuteAndCapture/Async()` does not play well with `PolicyWrap` at present, for the (conceptual) reason [described here](https://github.com/App-vNext/Polly/wiki/PolicyWrap#executeandcapture).  For now, switch back to `Execute/Async()` rather than `ExecuteAndCapture/Async()` 

Let us know if that provides what you need, or if you have further ideas for how this could be improved.

**Comment by grokky1** [comment]
Thanks for the detailed info!

A wrapped policy's lack of support for `ExecuteAndCapture/Async()` is confusing... Supposing my `DoSomething()` returns void:

    await policy.ExecuteAsync(() => DoSomething());

So I don't know whether the policy passed/failed, because there is nothing similar to `PolicyResult.Outcome`. Is there a way around this?

**Comment by reisenberger** [comment]
Hi @grokky1 !   We'll aim to fix up the use of `ExecuteAndCapture/Async()` with `PolicyWrap`; I've raised #267, with a proposal.

Re:

>I don't know whether the policy passed/failed [with `ExecuteAndCapture/Async()`], because there is nothing similar to `PolicyResult.Outcome`. 

`ExecuteAndCapture/Async()` is [just a try-catch, -> set result object](https://github.com/App-vNext/Polly/blob/75456beee1c4e25b88ab34057434bdc1eec30480/src/Polly.Shared/PolicyAsync.cs#L1130-L1138).  With `ExecuteAsync()` rather than `ExecuteAndCaptureAsync()`, you just have any final exception thrown.

So: If `policy` in `await policy.ExecuteAsync(() => DoSomething());` were just a retry policy, and all retries fail, the retry policy [will propagate the final exception](https://github.com/App-vNext/Polly/wiki/Retry#how-polly-retry-works) - so you'd know the retry policy failed by that exception being thrown (and need to `try/catch` for it).

If following the `PolicyWrap` pattern earlier in the thread, you'd typically use the `FallbackPolicy` to absorb that final exception from the inner retry policy (and take whatever compensating action you deem), so you'd know the retries failed from the `FallbackPolicy` kicking in.  Here's a fuller example commenting that, and demonstrating a common `LogPolicyExceptionAsync(exc)` delegate:

```
var retryPolicy = Policy
  .Handle<Exception>()
  .WaitAndRetryAsync(10, sleep, onRetryAsync: async (exc, span) => LogPolicyExceptionAsync(exc));
var fallbackPolicy = Policy
  .Handle<Exception>()
  .FallbackAsync(fallbackAction: async cancellationToken => 
     {
         // You will know all retries failed because your code hits here.
         // Do whatever desired to substitute for/compensate-for-failure-of executions through the policy.  
     },
     onFallbackAsync: async exc => LogPolicyExceptionAsync(exc));
var retryWithFallback = fallbackPolicy.WrapAsync(retryPolicy);

// elsewhere:
await retryWithFallback.ExecuteAsync(() => DoSomethingAsync())
```

**Comment by grokky1** [comment]
Is there a tradeoff to running the code in `fallbackAction` or `onFallbackAsync`? The latter has the exception info, so I assume as you've indicated that would be the correct place. But your comment "// You will know all retries failed because ..." surely applies to both delegates?

**Comment by grokky1** [comment]
Okay that try-catch approach makes good sense!

I had to change it a bit, specifically to rethrow the exception from `onFallback/Async`:

    onFallback: (exception, context) => { /* do something here */; throw exception; }

and later when executing the policy:

    try {
      policy.Execute(() => DoSomething());
      // if we get here, then it succeeded
    }
    catch {
      // if we get here, then it failed
    }

So for the above to work the exception must be rethrown.

**Comment by grokky1** [comment]
After going through all this, it's worth revisiting the original point. Take into account I'm new to Polly, so maybe my opinion doesn't count, but on the other hand, I'm new to Polly so I'm looking at things differently.

I get what you said about it being more powerful to combine policies. So in this case to detect the final failure, I just need to add the fallback policy. And if I want to know whether the overall thing succeeded, I need to use the try/catch approach you explained (because `ExecuteAndCapture` doesn't work). *All this works, but looking at this thread, it's messy.*

I need to rely on a side effect, i.e. by comibining two policies, I can detect the state that I'm interested in. That's real overkill. If you want to run a retry policy, it's much cleaner to simply run a retry policy, and have an `onLastFailure` (or something similar, I don't know what would be the best approach). Design-wise / semantically, what I want is to run a retry policy, not a retry and then fallback policy, to give me the semantics of a retry policy.

Not trying to be argumentative, just my 0.02. This library is great!

**Comment by reisenberger** [comment]
Hi @grokky1 ! Newness to Polly is no measure of quality of input: thanks for all your comments!

Agree about the long-windedness of `FallbackPolicy` for this Use Case.  May be one of those cases where one API design would have suited some contexts, another others.  The `FallbackPolicy` gives us a powerful concept for providing alternative values/actions for 'if all else fails' across all policy types / wraps, but agree, it feels heavyweight for this logging.

Another (unfortunate) consideration is that we're becoming constrained by the existing Polly syntax.  Distinct _positives_ of the existing Polly syntax are that everything about a retry policy is configured explicitly in one shot at configuration (highly visible; no 'hidden magic' defaults); and a policy is immutable once configured.  But the very same design (that everything is configured in one builder overload; no setting-after-the-event) leads to a distinct _negative_: Polly retry is already groaning under the weight of over 100 overloads. ... Which discourages adding further overloads, at least if there are alternatives (each new feature multiplies up).  ... Which is not a comment on the merit of `onLastFailure`; rather, on the syntax.  **TL:DR;** your suggestion could be a good, easy add if we were doing after-configured fluent adjustment, as in `.WithOnLastFailure(...)`.  

I can see a path to the overhauling the syntax (thanks to ideas from (shout-out) @brunolauze, @lakario , and @ankitbko ), but with the number of substantive features on the [roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap), syntax overhaul is sitting lower priority just at the moment.

Will keep `onLastFailure` in mind; we should try to find a way to work it in.

Thanks for the great observations!

**Comment by grokky1** [comment]
Yeah I peeked into the source and saw the staggering number of overloads! 😄 I agree that adding more would just make it harder to maintain.

Glad you agree with some of my points though. Hopefully in the future we can work around such issues. Until then I've used your workaround to great effect. Thanks again.
