### ISSUE TITLE
Target .NET 4.0 "non-async" (without Microsoft.Bcl.Async)?

### ISSUE THREAD

**Issue by johanna-bodnyk** [App-vNext/Polly#269]
We're using Polly in a large legacy system that does not support the System.Threading binding redirects necessary to use Microsoft.Bcl.Async -- which means we're stuck back on version 4.2.1 of Polly.

Would you consider offering a "sync-only" 4.0 target that does not depend on Microsoft.Bcl.Async?

**Comment by joelhulen** [comment]
Thanks for using Polly, and thanks for the request! However, after much consideration with the team, I don't think it is possible to provide a "sync-only" 4.0 target at this time. There are a couple reasons for this:

1. The .NET40 Async library currently accounts for less than 0.5% of our user base, as it is. The **no-async** version would account for an even smaller constituency. This alone is not the issue, however.
2. Introducing a **no-async** version would introduce significant `#if` / `#endif` forking/complexity into our codebase, hitting around 50% of the files.

That level of impact and maintenance overhead for such a small number of users/use cases doesn't make sense for us to devote our time to at this point.

However, because Polly is open source :) - you are free and able to fork the latest head revision and strip out the async stuff that you don't want.

We must consider every request very carefully to ensure our limited time makes the most positive impact, and does not negatively impact any customers in a significant way. I'm sorry, but unless someone thinks of a better way to address this, or if there's significant buy-in from the community at large, we'll have to decline your request at this time.

**Comment by johanna-bodnyk** [comment]
Thanks for considering and for the explanation, that makes lots of sense!
