### ISSUE TITLE
Make overload in retry to take exception before pause provide

### ISSUE THREAD

**Issue by ijsgaus** [App-vNext/Polly#301]
WaitAndRetry(int, Func<int, TException, TimeSpan> timeout);

**Comment by reisenberger** [comment]
Broadly related to #177 .  

At the moment, we are looking not to add further policy configuration overloads to Polly, due to the already too-numerous overloads.  The forthcoming syntax changes proposed in #281 are intended to reduce the number of overloads by splitting `onPolicyEvent`-type delegates out of Policy configuration.  

It could be good then to add [this](https://github.com/App-vNext/Polly/issues/301#issue-252734315) after the #281 syntax changes.

**Comment by reisenberger** [comment]
This feature is delivered in Polly v5.6.0 (will be released via nuget in next day or so).
