### ISSUE TITLE
Must be able to assert result from Polly in unit tests

### ISSUE THREAD

**Issue by jiimaho** [App-vNext/Polly#315]
There's the [noOp ](https://github.com/App-vNext/Polly/wiki/NoOp) policy that is recommended to be used in tests. This class allows your code to bypass polly itself, ignoring timeouts for example (which is our case). 

This is all great, but we **must** be able to assert the TimeoutRejectedException from polly. I guess what we want to do is to "fake" the noOp policy to always have a `FinalException `set. Is this possible?

In essence, we want to;
1. Write code dependent on the timeout policy.
2. Inject `noOp `policy in our tests
3. Make polly return `TimeoutRejectedException`, even though not applying the real timeout policy (because of obvious reasons)
4. **Assert our code behaves correctly on the policy result**. (We make decisions based on the `FinalException `property on the policy result)

I've tried to narrow this down as much as I can while still making it useful and hopefully understandable.

**Comment by reisenberger** [comment]
@jiimaho  Makes complete sense.  Great q.

A few possibilities:

(a) _available now_: **Inject a `TimeoutPolicy` configured to `TimeSpan.Zero`** : 

+ With [`TimeoutStrategy.Optimistic`](https://github.com/App-vNext/Polly/wiki/Timeout#optimistic-timeout), bear in mind that the executed delegate will execute any code up until the point it first honours a cancellation token.  Well-designed code should check the cancellation token on entry.  
+ If using [`TimeoutStrategy.Pessimistic`](https://github.com/App-vNext/Polly/wiki/Timeout#pessimistic-timeout) because the executed delegates do not observe cancellation, the policy would throw the `TimeoutRejectedException`, but the delegate (if not observing cancellation) [would continue to execute](https://github.com/App-vNext/Polly/wiki/Timeout#what-happens-to-the-timed-out-delegate) - which may not be what you want in the test.

(b) _available following a small PR_: **Mock an injected policy to throw `TimeoutRejectedException` or to set up a `PolicyResult` denoting `TimeoutRejectedException`** : If you're using / can use a mocking framework, and you inject your policy in one of the [interface forms](https://github.com/App-vNext/Polly/wiki/Polly-and-interfaces), then in the test, you could set up the mock to throw `TimeoutRejectedException`; or the execution to return a `PolicyResult` with `FinalException` set to `TimeoutRejectedException`.  For the latter, the various static constructors in [PolicyResult](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/PolicyResult.cs) would need to be made `public` - we'd be happy to accept a PR for that.

(c) _not available yet_: **Custom policy**: When we have PR #299 finalised (but it needs review/small changes), you would be able to write your own custom policy - say, `AlwaysTimesOutPolicy` - and inject this instead of your real `TimeoutPolicy` or `NoOp`.  

Do any of these help?

**Comment by reisenberger** [comment]
Addendum: when **custom policies** are possible, the suggestion (c) could of course be generalised to various test-helper policies such as:

`Policy.TestHelperReturns<T>(T instance)`: always returns `instance` instead of executing supplied delegate
`Policy.TestHelperThrows(Exception exception)`: always throws `exception`

(and similar).

To some extent this overlaps with facilities already available in standard mocking frameworks, so may be better left to them.  Having a number of these would also be a distraction, if in core `Polly`.  Perhaps better as part of a `Polly.Contrib`.

Thinking aloud here - _community views?_

**Comment by udlose** [comment]
I had a similar requirement - to verify the result of a Fallback.  I looked at mocking out NoOpPolicy but found it insufficient.  What I ended up doing was to exercise my policy in my unit test and pass it a Func that caused failures  Maybe this will help you somewhat:

```
        [Test]
        public async Task FallbackValueIsReturnedAfterRetryAttemptsExceededOnHttpException()
        {
            //arrange
            var myPolicy = ObjectUnderTest.Build<Foo>();
            var testRequest = BuildRequestMessage();
            var expectedFallback = new HttpResponseMessage(HttpStatusCode.PartialContent)
            {
                Content = new ObjectContent<Foo>(BuildTestFoo(), Formatter),
                RequestMessage = testRequest
            };

            Func<Task<HttpResponseMessage>> funcToCauseRetry = () =>
            {
                throw new HttpException(ApiExceptionMessage);
            };
            var callContext = new PolicyCallContext(MyPolicyBuilder.CallsiteContextExecutionKey);
            callContext.Add(MyPolicyBuilder.CallContextRequestLookupKey, testRequest);
            callContext.Add(MyPolicyBuilder.CallContextUserContextKey, _userContext);

            //act
            var actual = await myPolicy.ExecuteAsync((context, token) => funcToCauseRetry(), callContext, new CancellationToken(), false);

            //assert
            actual.ShouldBeEquivalentTo(expectedFallback, options => options.RespectingRuntimeTypes());

            //retry
            this.ForLogger().Verify(l => l.Error(It.Is<int>(i => i == TxErrorCodes.ResiliencyCodes.RetryFailed), 
                It.Is<string>(m => m.Contains($"{CallFailedPartialMessage} 1"))), Times.Once);
            this.ForLogger().Verify(l => l.Error(It.Is<int>(i => i == TxErrorCodes.ResiliencyCodes.RetryFailed), 
                It.Is<string>(m => m.Contains($"{CallFailedPartialMessage} 2"))), Times.Once);
            this.ForLogger().Verify(l => l.Error(It.Is<int>(i => i == TxErrorCodes.ResiliencyCodes.RetryFailed), 
                It.Is<string>(m => m.Contains($"{CallFailedPartialMessage} 3"))), Times.Once);

            //circuit breaker
            this.ForLogger().Verify(l => l.Error(It.Is<int>(i => i == TxErrorCodes.ResiliencyCodes.CircuitOpenError),
                It.Is<string>(m => m.Contains($"{CfcPolicyBuilder.NameKey} reached max retry attempts of {DefaultRetryCount}"))), Times.Once);

            //fallback (circuit-breaker caused the Fallback)
            var fallbackMessage = $"{MyPolicyBuilder.NameKey}_CircuitBreaker at {MyPolicyBuilder.CallsiteContextExecutionKey}: fallback value substituted, due to: Polly.CircuitBreaker.BrokenCircuitException";
            this.ForLogger().Verify(l => l.Error(It.Is<int>(i => i == TxErrorCodes.ResiliencyCodes.FallbackUsed), 
                It.Is<string>(m => m.Contains(fallbackMessage))), Times.Once);
        }

```

**Comment by jiimaho** [comment]
> (a) available now: Inject a TimeoutPolicy configured to TimeSpan.Zero

This doesn't work. It throws an ArgumentOutOfRange exception.

> (b) available following a small PR: Mock an injected policy to throw TimeoutRejectedException or to set up a PolicyResult denoting TimeoutRejectedException

This would be the best it seems, not sure if we can afford the time for PR now though.

Thanks a lot for all your help and fast response! Will see how we will solve this.

**Comment by reisenberger** [comment]
>This doesn't work. It throws an ArgumentOutOfRange exception. 

True: I misread the boundary condition.  We could change the boundary condition to permit `TimeSpan.Zero`, to support this Use Case.  You could also (right now) likely use `TimeSpan.FromTicks(1)` with the same practical effect.

**Comment by jiimaho** [comment]
> True: I misread the boundary condition. We could change the boundary condition to permit TimeSpan.Zero, to support this Use Case. You could also (right now) likely use TimeSpan.FromTicks(1) with the same practical effect.

Yes we tried this, or something very similar. Seemed the effects were different depending on which machine executed it. (locally or through AppVeyor).

Anyway - I created a pull request. It's very minor, and i'm not sure about the comments. Please have a look: https://github.com/App-vNext/Polly/pull/317

**Comment by reisenberger** [comment]
@jiimaho Re:

>Seemed the effects [of a test based on a short timeout] were different depending on which machine 
>executed it. (locally or through AppVeyor).

Aha.  Well, we can corroborate that experience if AppVeyor is in the mix.  We in the past [observed a similar problem with `CancellationToken.CancelAfter()` firing significantly later than billed, in an AppVeyor build](https://github.com/App-vNext/Polly/issues/220).  (A wrinkle; AppVeyor awesome in so many other ways.)

In any case, moving (as we are doing) to simply being able to mock the policy to return a desired `PolicyResult` is a much more robust solution.

**Comment by reisenberger** [comment]
Close via #317

**Comment by reisenberger** [comment]
@jiimaho  Added to the Polly [unit-testing documentation)(https://github.com/App-vNext/Polly/wiki/Unit-testing-with-Polly), to reflect this approach.
