### ISSUE TITLE
Circuit Breaker question: break on frequency of failures?

### ISSUE THREAD

**Issue by udlose** [App-vNext/Polly#316]
I've been using Circuit Breaker with WaitAndRetry for my current work.  Requirements have changed slightly since we're still learning about the way Polly works and adapting our strategy to leverage what exists out of the box.

What would be your suggestion on implementing a requirement of: 
_if there are 10 failures with a span of 5 mins, open the circuit for 5 mins_

I looked at the AdvancedCircuitBreaker but it seems focused on a proportion of errors.

**Comment by reisenberger** [comment]
@udlose  Great question.  

This kind of configuration option (_N failures within timespan T_) was one we [considered for triggering circuit-breaking](https://github.com/App-vNext/Polly/issues/41#issuecomment-199251432), but shied away from because pure error frequencies (N per time T) as a measure are vulnerable to not scaling with load increases or decreases.

Say you set the trigger level at 4 failures in 30 seconds.  If your circuit is handling 'typically' (say) 10 calls/30-seconds, that's a nice sensible trigger threshold (about 40% failure rate).  But what if throughput increases to, say, 100 calls/30-seconds?  Suddenly 4 failures is only 4% - would one still want to break (impose 100% failure) on a 4% failure rate?  It's a more extreme example, but the principle holds: effectively, the influence of a trigger configured as _N failures per T_ varies with throughput.  

(That's not to say you might not have a scenario where you might be comfortable with it as a measure; but it's why we didn't implement it.)

**Comment by reisenberger** [comment]
So to come back to your question, practically:

>What would be your suggestion on implementing a requirement of:
>if there are 10 failures with a span of 5 mins, open the circuit for 5 mins

My suggestion would be: if you're thinking 10 failures in 5 mins is your trigger, you probably have in the back of your mind some idea of the overall throughput that's against: say, 20 calls in 5 mins or 30 calls in 5 mins.  I'd convert that to a proportion for the `AdvancedCircuitBreaker` (break on 50% failure rate; or 33% failrue rate).  Set up your `AdvancedCircuitBreaker` as something like:

`failureThreshold`: 30% or 50%
`samplingDuration`: 5 minutes (as you wanted) (forgets about things that happened >5 mins ago)
`minimumThroughput`: 10 calls.  (This effectively gives you part of what you wanted - it won't trigger unless you have at least 10 failures in those 5 minutes.)

Then you have something close to your original intention, but you also now have a version which scales appropriately with varying throughput.

**Comment by udlose** [comment]
@reisenberger - no problem. I appreciate the discussion and your recommendation. I'll give that a try and we'll see how it does under stress testing.

So in the case of the AdvancedCircuitBreaker, what happens to the requests that come thru and fail but do not cause the circuit to open?  In my case, I am using a PolicyWrap with Wait/Retry, AdvancedCB, and Fallback.  I assume that the failures will cause a Fallback policy to be invoked.

**Comment by reisenberger** [comment]
Hi @udlose 

>So in the case of the AdvancedCircuitBreaker, what happens to the requests that come thru and fail but do not cause the circuit to open?

They are [rethrown](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#exception-handling) and will bubble to the calling code - either the next outer policy in the wrap, or (if none), your calling code.

> I assume that the failures will cause a Fallback policy to be invoked.

Yes (assuming - stating these just for precision - the [fallback is somewhere outside the breaker in the wrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#ordering-the-available-policy-types-in-a-wrap), and the fallback is configured to handle the given exception)
