### ISSUE TITLE
AdvancedCircuitBreaker not opening as expected

### ISSUE THREAD

**Issue by udlose** [App-vNext/Polly#320]
I'm doing some perf/scale testing with my perf engineer running a NeoLoad script.  My app is using a `Fallback`, `AdvancedCircuitBreaker`, `WaitAndRetry `in a `PolicyWrap`.  I'm experimenting with different values for the ACB settings below and not seeing the Circuit open as I'd expect (I realize these settings make the CB "trigger happy" but I'm trying to understand how this is supposed to work):

```
failureThreshold: .01
samplingDuration:  TimeSpan.FromSeconds(300)
minimumThroughput: 10
```

I expect this to work as follows: after 10 requests have been made within 300 secs (or less), and 1% of them fail, then open the circuit.  In this case, I'd expect the **first** failure (after 10 requests have been made) to open the circuit.  Is my understanding correct?  If so, then either I am doing something wrong or there is a bug in Polly.  I am seeing it take well over 10 - 20 requests (in this exact case) to open the circuit.  I've experimented with `failureThreshold `values of .01, .10, .20, .30 and though there seems to be a small amount of variance between when the circuit is opened, it doesn't seem to match what is expected.

```
    private static readonly List<HttpStatusCode> _httpStatusCodesWorthRetrying = new List<HttpStatusCode>
    {
        HttpStatusCode.RequestTimeout, // 408
        HttpStatusCode.InternalServerError, // 500
        HttpStatusCode.BadGateway, // 502
        HttpStatusCode.ServiceUnavailable, // 503
        HttpStatusCode.GatewayTimeout // 504
    };
```
...

```
        var waitAndRetryPolicy = Policy<HttpResponseMessage>
            .Handle<Exception>(e => !(e is BrokenCircuitException)) //exception filtering!  We don't retry if the inner circuit-breaker determines the underlying system is down
            .OrResult(r => _httpStatusCodesWorthRetrying.Contains(r.StatusCode))
            .WaitAndRetryAsync(
                retryCount: 1,
                sleepDurationProvider: attempt => TimeSpan.FromMilliseconds(150),
                onRetry: (delegateResult, calculatedWaitDuration) =>
                {                        
                });

        var advancedCircuitBreakerPolicy = Policy<HttpResponseMessage>
            .Handle<Exception>()
            .OrResult(r => _httpStatusCodesWorthRetrying.Contains(r.StatusCode))
            .AdvancedCircuitBreakerAsync(
                failureThreshold: .01,
                samplingDuration: TimeSpan.FromSeconds(300),
                minimumThroughput: 10,
                durationOfBreak: TimeSpan.FromSeconds(300),
                onBreak: (delegateResult, breakDelay) =>
                {
                },
                onReset: () =>
                {
                },
                onHalfOpen: () =>
                {
                }
            );

        var fallbackPolicy = Policy<HttpResponseMessage>
            .Handle<Exception>()
            .OrResult(r => _httpStatusCodesWorthRetrying.Contains(r.StatusCode))
            .FallbackAsync(
                fallbackAction: async (callContext, token) => await BuildFallback(callContext), 
                onFallbackAsync: async (delegateResult, callContext) =>
                {
                });

        _policyWrap = Policy.WrapAsync(new[] {fallbackPolicy, advancedCircuitBreakerPolicy, waitAndRetryPolicy});
```
The state of the circuit is observed through calls to the `CircuitState `for `advancedCircuitBreakerPolicy`.

**Comment by reisenberger** [comment]
@udlose I haven't full sight of your test setup, but the effect you describe is likely due to concurrency of calls through the breaker.  I'm assuming the NeoLoad script is placing sufficient load that calls are being handled in parallel on different threads. 

The [path of an individual call through the breaker](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#putting-it-all-together-) has three broad phases:

(I) [Should the call be allowed to proceed?](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitBreakerEngineAsync.cs#L24) (eg reject if circuit broken)
(II) [Execute the user delegate](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitBreakerEngineAsync.cs#L28)
(III) [Update circuit metrics for the result, and return/rethrow the result](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/CircuitBreakerEngineAsync.cs#L30-L51)

The nub of the 'gotcha' to get in mind is that in parallel throughput, further calls can arrive at (I) before preceding calls have exited at (III).

Say all calls fail, we're just executing `throw someException;`.  Consider calls arriving in high concurrency.  For example:

+ Say 10 calls pass stage (I).
+ While those 10 calls are in stages (II) and (III), another 4 calls (they're arriving in parallel) get through the gateway of stage (I), _before the first 10 calls have all completed (III)_.
+ Now the 10th call failure registers at (III) and the circuit opens.  Calls 15, 16 etc arriving at stage (I) are rejected with `BrokenCircuitException`.
+ Calls 11, 12, 13, 14 meanwhile passed (I) earlier, so they (II) executed, and arrive at (III) as failures.  The circuit-breaker bubbles their outcome outwards (rethrows `someException` in this case).  
  - _Note_: Polly can detect the circuit is now open and could throw `BrokenCircuitException` instead at this point.  But [this was considered misleading](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/CircuitBreaker/AdvancedCircuitController.cs#L95-L98).  The user delegate _has_ executed, and to throw `BrokenCircuitException` instead would mask an outcome (success or failure) of an execution which has actually occurred - this could be critical in some business scenarios.

The above scenario might easily look as if it took 14 failures to open the circuit.  In fact, the circuit opened correctly once 10 failures could be detected, but 14 executions proceeded before those 10 failures arrived (and so those 14 failures, to be faithful to the calls, have to be reported).

Does this sound like it describes what you are observing?  If not, please share more, and we can dig deeper.

See also the comments below about how `BulkheadPolicy` complements circuit-breakers, and addresses parallelism.

**Comment by reisenberger** [comment]
A few related observations:

+ This behaviour is not as uncommon as the description in the previous comment (involving racing threads) might suggest.  This can be common when calls at stage (II) are timing out.  Consider you are calling a third-party endpoint which starts failing. You have a 5-second timeout imposed on it.  Consider calls are arriving/being placed at a rate of 10/second.  You quickly have 50 calls in flight in parallel (assuming no other limitations), before you even receive your first timeout.  Parallelism can rise quite quickly, regardless of how eagerly a circuit-breaker is configured.

+ This is why [`BulkheadPolicy`](https://github.com/App-vNext/Polly/wiki/Bulkhead) exists.  `BulkheadPolicy` exists to prevent resource/parallelism bulges like this, when calls back up. `BulkheadPolicy` is a parallelism throttle.

+ The behaviours described are common to both `AdvancedCircuitBreaker` and original `CircuitBreaker` (not particularly a quirk of ACB).
