### ISSUE TITLE
Get current tryCountwhen excute?

### ISSUE THREAD

**Issue by zirain** [App-vNext/Polly#380]
Hello,

Is there any way to get current tryCount when excuting the real function?

**Comment by reisenberger** [comment]
Hi @zirain . There is no built-in way to do this.  


You can of course achieve this by maintaining your own try count, closing over a variable you increment yourself:

```
int attempts = 0;
var result = policy.Execute(() => { 
   attempts++;
   //  ... 
} );
```

Polly does not have this built in due to the fully flexible functional-composition nature of [`PolicyWrap`](https://github.com/App-vNext/Polly/wiki/PolicyWrap).  Each layer of a PolicyWrap is agnostic to whether it is executing the final user delegate or another layer of PolicyWrap.  Equally, some users intentionally have [more than one Retry policy in a PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#using-the-same-type-of-policy-more-than-once-in-a-wrap) - to treat different kinds of exception to different retry strategies.  A price of this flexibility is that it is non-trivial to define what 'number of tries' means in the context of a PolicyWrap.

**Comment by zirain** [comment]
Hi @reisenberger ,thx for you reply,I will maintain it myself
