### ISSUE TITLE
PolicyWrap containing only one Policy?

### ISSUE THREAD

**Issue by joshidp** [App-vNext/Polly#386]
Hi,

Thanks for your effort.

I am getting error while wrapping the Policy[] like 

> _policyWrapper = Policy.WrapAsync(policies);

Additional information: The enumerable of policies to form the wrap must contain at least two policies.

I don't want to add two policies, please describe the way to do it.

Thanks

**Comment by udlose** [comment]
There is no need to use a `PolicyWrap` if you only have 1 `Policy`.  `PolicyWrap` is designed to associate multiple policies together.

**Comment by reisenberger** [comment]
Hi @joshidp . `PolicyWrap` is designed always to contain two (or by nesting, more) policies.

If you want sometimes to apply only a single policy, sometimes multiple policies, based on a supplied `Policy[] policies`, you could use a helper method:

```
public Policy WrapOrSingleAsync(Policy[] policies)
{
    switch(policies.Length)
    {
         case 0: 
            throw new ArgumentException(/* some error message that no policies were supplied */);
         case 1: 
            return policies[0];
         default: 
            return Policy.WrapAsync(policies);
    }
}
```

The subsequent code to execute delegates using the returned `Policy` will be identical regardless of whether the returned value is a single policy or wrap, since [PolicyWrap is just another kind of Policy](https://github.com/App-vNext/Polly/wiki/PolicyWrap#policywrap-is-a-policy).

---

The constraint that a `PolicyWrap` always contains >=2 policies reduces run-time checks on `PolicyWrap`, but does require a workround such as above in the case you want a 'wrap containing only one Policy'.

There would be trade-offs to changing this, but I'll revisit the possibilities as part of a future release.

**Comment by reisenberger** [comment]
Closing (a 'how to' question that has not received recent comment).  Please re-open if further support is required.
