### ISSUE TITLE
WaitAndRetryAsync overload where 'onRetryAsync' is a Func - should be an Action?

### ISSUE THREAD

**Issue by ciarancolgan** [App-vNext/Polly#399]
Hi, i'm wondering why this method signature:

public static RetryPolicy WaitAndRetryAsync(this PolicyBuilder policyBuilder, int retryCount,
            Func<int, Exception, Context, TimeSpan> sleepDurationProvider, Func<Exception, TimeSpan, int, Context, Task> onRetryAsync)

has 'onRetryAsync' as a Func - there shouldnt be anything returned from this right? The synchronous version of this has it as an Action.

**Comment by reisenberger** [comment]
Hi @ciarancolgan 

`Func<..., Task>` is the standard return type for an async delegate that returns nothing.  The delegate signature must return `Task` in order that that `Task` can be awaited by the `await` statement.  

You don't however have to explicitly return a `Task` instance if your delegate is delcared `async`: when you code `async (...) => { /* some async work returning no value */ }`, the compiler transforms this to a `Func<..., Task>` for you.   

See [Stephen Cleary's article on sync and async delegate types](https://blog.stephencleary.com/2014/02/synchronous-and-asynchronous-delegate.html) - particularly the table in that article - for a full set of examples.

If the async delegate was returning something, say an instance of `TResult`, the delegate's type would be `Func<..., Task<TResult>>`

**Comment by ciarancolgan** [comment]
Superb answer - i missed the 'async' modifier on the delegate declaration which meant the compiler wanted a return type. 
Thanks and keep up the great work :)

**Comment by reisenberger** [comment]
No problem!  For backwards compatibility reasons, btw, for retry policies, there are also overloads with the `onSomePolicyEvent` delegates available in _sync_ form on the _async_ policies.  For instance, the overload with the synchronous analogue of the delegate you quoted (with `onRetry` rather than `onRetryAsync`) is [here](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Retry/RetrySyntaxAsync.cs#L142).  So if you prefer/only need the sync delegate, that's an option.
