### ISSUE TITLE
Policies for multiple hops

### ISSUE THREAD

**Issue by subatta** [App-vNext/Polly#401]
In our current architecture, we have multiple HTTP clients involved in making calls to web services. We are planning to start using Polly but need some guidance when multiple calls are involved. For example, where do we apply a retry policy when the following chain of calls are involved? 

Client 1 --> Client 2 at interim Service --> Client 3 at gateway --> Backend service

Do we apply policies at multiple points? That seems risky with the probability of exaggerating waits. If we limit resilience policies at fixed points, how should other clients respond?

@reisenberger we spoke earlier with an issue we have with tests but now this is in real code and we'd appreciate your input.

**Comment by reisenberger** [comment]
@subatta I will aim to put together some comments around the weekend.

**Comment by reisenberger** [comment]
@subatta I understand the concern as being that if WaitAndRetry policies are used at all points in a chain of synchronous calls, the waits could compound over the chain in a failing scenario, leading to an inappropriately long wait before reporting overall failure, at the outermost, original caller.  

I can make two suggestions:

(1) Only use wait-and-retry policies at the outermost caller in any chain.  Disadvantages may be that you may not have control over all callers; or you may not want to embed the knowledge of retry strategies into those callers.

(2) Tag the failure response returned by any layer with an annotation of which layer is failing (perhaps using a custom HTTP header).  Then, use the [ability of Polly policies to filter on any property of the response](https://github.com/App-vNext/Polly/blob/master/README.md#step-1b-optionally-specify-return-results-you-want-to-handle) so that the wait-and-retry policy at each layer only handles faults originating from the layer immediately below.

This annotation approach also allows the use of circuit-breakers at each level, reflecting only (and thus allowing monitoring of) the health of the layer immediately below.  All of course at the cost of some extra complexity.

Minimizing chains of synchronous calls, where possible, is obviously also good practice.
