### ISSUE TITLE
how to extend Polly with a custom RetryWithRetryAfterPolicy

### ISSUE THREAD

**Issue by apobekiaris** [App-vNext/Polly#407]
> A future blog post will cover how to extend Polly with a custom RetryWithRetryAfterPolicy, hiding the detail in the above example.

If a blog post takes too much time, care to share a short how to here?

**Comment by reisenberger** [comment]
@apobekiaris Since that blog post, we have hopefully made this easier.  From #367, new overloads exist for WaitAndRetry and WaitAndRetryForever policies which take the just-happened-error as an input parameter to the `sleepDurationProvider` delegate.  

Have a look at the unit tests on the TResult handling policies, in the [files changed in that PR](https://github.com/App-vNext/Polly/pull/367/files); these demonstrate examples.  If an endpoint returns a HTTP 429 `x-ms-retry-after-ms` header, your policy can detect that in the [`outcome.Result` property passed to the `sleepDurationProvider` delegate](https://github.com/App-vNext/Polly/blob/master/src/Polly.SharedSpecs/Retry/WaitAndRetryTResultAsyncSpecs.cs#L35), and make `sleepDurationProvider` return a wait duration based on the passed `x-ms-retry-after-ms` header.

**Comment by reisenberger** [comment]
Hi @apobekiaris . Thanks for spotting and pointing out that [that blog post](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/) was out of date.  I've updated the blog post to point to [the new approach for handling RetryAfter within Polly](https://github.com/App-vNext/Polly/wiki/Retry#when-the-response-specifies-how-long-to-wait-before-retrying).

Having spotted that we have a section on this on the [retry wiki page](https://github.com/App-vNext/Polly/wiki/Retry#when-the-response-specifies-how-long-to-wait-before-retrying), I'm going to close this issue.  However, do come back to us if you need any further assistance!
