### ISSUE TITLE
CircuitBreakerPolicy - handling different return types

### ISSUE THREAD

**Issue by janzakrzewskipl** [App-vNext/Polly#411]
Is there a way to work on the same circuit state, while handling different return types?
Let's say I have:
```
class Service
{
    StateA GetStateA();
    StateB GetStateB();
    ...
    StateX GetStateX();
}
```
and I want to open circuit if `StateA.IsBad` or `StateB.IsWrong` or ...
One thing that comes to my mind is to define `Policy<object>` and in `Handle(object obj)` do a proper casting, but maybe there is some better way to do that?

**Comment by reisenberger** [comment]
Hi @janzakrzewskipl .  There isn't currently a way for a single Polly policy natively to handle multiple disjoint `TResult` types.  `Policy<TResult>` instances are strongly-typed to a single `TResult` in order to provide that compile-time binding [between `.Handle<TResult>`, `.Execute<TResult>` and multiple `TResult` policies in a `PolicyWrap<TResult>`](https://github.com/App-vNext/Polly/wiki/Non-generic-and-generic-policies#features-that-drive-the-transition-to-policytresult).

Options now:

+ Define a `Policy<object>` and cast, as you say. 
+ Use a non-generic `Policy`, and wrap the calls so that they throw exceptions for the unhealthy states.  (Just a different kind of compromise.)
+ If you have control over `StateA`, `StateB` etc (ie if it's your code), you might be able to:
  - have `StateA`, `StateB` etc extend or fulfil some common base class or interface, and have that base class or interface signal unhealthy state, allowing you to use a common `Policy<TInterface>` or `Policy<TBaseClass>`.
  - (or) wrap the outcomes in a wrapper class `Outcome<TResult> : Outcome`, with `Outcome` signalling healthy/unhealthy, and have the circuit-breaker policy handle `Outcome`.

---

From Polly v6 something more native might be possible.  For Polly v6 I have sketched the ability for users to define custom circuit-breakers, passing in their own circuit controllers.  The existing circuit-controllers would also be available with public constructors.  This could allow you to set up two strongly-typed policies which share the same controller and state:

```csharp
ConsecutiveCountCircuitController sharedController = new ConsecutiveCountCircuitController(/* your configuration */);
Policy<StateA> policyA = Policy.HandleResult<StateA>(StateA.Bad).CustomCircuitBreaker(sharedController);
Policy<StateB> policyB = Policy.HandleResult<StateB>(StateB.Unhealthy).CustomCircuitBreaker(sharedController);
```

Hope this helps.

**Comment by janzakrzewskipl** [comment]
Yes it helps.
Thanks.
