### ISSUE TITLE
Cancel in Retry Action

### ISSUE THREAD

**Issue by Discofunk** [App-vNext/Polly#431]
Is there a way to cancel additional retries within the retry action (synchronous)?

For example:

```
var policy = Policy
    .Handle<OfflineException>()
    .Retry(3, (ex, retryAttempt, ctx) =>
    {
        var result = MessageBox.Show("Please retry once the application is back online or cancel this request", "Application Offline", MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
        if (result != DialogResult.Retry)
        {
            //ToDo: cancel further attempts.  ctx.AbortRetries(); ??
        }
    });
```
When executing a cancellation token can be passed but one would not necessarily have access to the token source during the retry action.

**Comment by reisenberger** [comment]
Hi @Discofunk .  Overloads exist for all synchronous executions taking a `CancellationToken`.  The retry implementation [honours cancellation before each try](https://github.com/App-vNext/Polly/blob/2ac94cff75d2a63200dfab76f90e7c462f463a3b/src/Polly.Shared/Retry/RetryEngine.cs#L27) as well as (with wait-and-retry policies) during any wait-before-retry.

You can pass arbitrary data in to the execution via the `Context` as [shown here in the readme](https://github.com/App-vNext/Polly#step-3--execute-the-policy).  You would need to pass in a related `CancellationTokenSource` in order to be able to initiate cancellation within the execution.  

If you do not have access to the `CancellationTokenSource` for some existing `CancellationToken` being passed, then you would need to create your own `CancellationTokenSource` (to which you therefore do have access) and use `CancellationTokenSource.CreateLinkedTokenSource()` to combine with the other token.

**Comment by reisenberger** [comment]
@Discofunk  The example you posted should work.  But per my [near-simultaneous comment](https://github.com/App-vNext/Polly/issues/431#issuecomment-378403502), if the scenario is simply the [code you originally posted](https://github.com/App-vNext/Polly/issues/431#issue-310967559), the context-passing solution seems over-engineered.

From your initial comment about 'not having access to the token source' I assumed that was the way you wanted to initiate cancellation.  But would the following not also suffice?

```
var policy = Policy
    .Handle<OfflineException>()
    .Retry(3, (ex, retryAttempt, ctx) =>
    {
        var result = MessageBox.Show("Please retry once the application is back online or cancel this request", "Application Offline", MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
        if (result != DialogResult.Retry)
        {
            throw new OperationCanceledException();
        }
    });
```

**Comment by reisenberger** [comment]
Closing as I believe we have a resolution for the question raised.  However, do please reopen - or open another issue - if you have further questions.

**Comment by rodion-m** [comment]
Hello guys! @reisenberger, sorry, but your solution looks like a hack. Please consider a solution with a nullable TimeSpan in sleepDurationProvider and if it null, it means just Cancel (without any unnecessary  exceptions).

**Comment by reisenberger** [comment]
Thanks @rodion-m for the comment.  

A better solution here (which I missed pointing out originally) is that `onRetry` is not really the place to decide whether an action should be retried.  Polly already offers a [well-defined, strongly-expressive API](https://github.com/App-vNext/Polly/#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle) for whether exceptions should be retried: the `.Handle<>()` clauses.

So @Discofunk 's original problem could also be solved by:

```
var policy = Policy
    .Handle<OfflineException>(_ => 
     {
        var result = MessageBox.Show("Please retry once the application is back online or cancel this request", "Application Offline", MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
        return (result == DialogResult.Retry);
    });
).Retry(3);
```

---

Thanks @rodion-m for the suggestion that `sleepDurationProvider` could return `null` to indicate "don't retry". Broadly, I am not in favour of having two places in an API to accomplish the same thing, as this tends to dilute the focus of the API overall (users will ask: "What is the difference?"). So, because Polly already has the strong API of the `.Handle<>()` clauses to indicate whether to retry exceptions, we will probably not modify `sleepDurationProvider` to also indicate this.
