### ISSUE TITLE
WaitAndRetry with new value

### ISSUE THREAD

**Issue by luistest** [App-vNext/Polly#440]
Hi, i just starting using Polly and i have a question: i have a **Policy.HandleResult.WaitAndRetry A** for a method X and **Policy.HandleResult.WaitAndRetry B** for method Y that uses value returned by method X, but now i want to try the following: if **B** is triggered i want to retry method Y, making a new request to method X, keeping policy usage in both methods. Is that possible?

**Comment by reisenberger** [comment]
Hi @luistest . It's certainly possible to nest calls through policies, so that (for example) an outer WaitAndRetry(...) policy executes code that itself includes an inner WaitAndRetry(...) execution. It sounds like that's what you want.

From the problem description, I don't have a clear picture of the method signatures and how they interact. Re "method Y uses value returned by method X": Is that, method Y calls X(...) internally?  Or is the result of X() passed as an input parameter to Y?  For us to help further, please could you post pseudo-code showing the elements in the question and how they interact?  Without seeing that, there's a risk any code I propose might make different assumptions and not meet your needs.  Many thanks.

**Comment by reisenberger** [comment]
Hi @luistest . Does this help?

```
var policyA = // ...
var policyB = // ...

public ReturnTypeOfX X() ( /* code */ }
public ReturnTypeOfY Y(ReturnTypeOfX x) ( /* code */ }

var y = policyB.Execute(() => Y(policyA.Execute(() => X()));
```

I am not sure if this meets your needs, because it may not match how your method Y uses the return value of X().  And in my example above, the policy usage is not in the method.  We would need to see an example of your existing code, to understand better your code structures.

**Comment by reisenberger** [comment]
Closing due to lack of response.  However, do please reopen or ask a new question if we can help further.
