### ISSUE TITLE
WaitAndRetryForever variants: add overloads where onRetry takes retry number

### ISSUE THREAD

**Issue by SashaPshenychniy** [App-vNext/Polly#451]
Method `WaitAndRetryAsync `do have an override:
`public static RetryPolicy WaitAndRetryAsync(this PolicyBuilder policyBuilder, int retryCount, Func<int, Context, TimeSpan> sleepDurationProvider, Action<Exception, TimeSpan, int, Context> onRetry)`
allowing to log exception together with **number of attempt** during which it ocurred:
```
Policy
    .Handle<ArgumentException>()
    .WaitAndRetryAsync(10, (rn, ctx) => TimeSpan.FromSeconds(1),
        (ex, ts, rc, ctx) => { Console.WriteLine($"Exception logged: {ex.GetType().Name}. Attempt: {rc}"); })
```
But method `WaitAndRetryForeverAsync `does not have similar override. As a workaround I could use `WaitAndRetryAsync` with `int.MaxValue` as first argument, but that is not the best look and feel especially when we have Forever counterpart method.

As a solution I can propose either add the missing override, or add retryAttemptNumber to Context class. Latter option would also help when retry attempt is needed during main action execution (mainly for logging purposes).

**Comment by reisenberger** [comment]
@SashaPshenychniy  Thank you for this and apologies for the delayed reply.  We would accept a PR to add the missing overloads.  The changes would need to be implemented in [all four variants](https://github.com/App-vNext/Polly/wiki/Polly-concept-and-architecture#all-policies-operate-across-two-key-dimensions) of the WaitAndRetryForever policy, ie in:

+ [RetrySyntax.cs](https://github.com/App-vNext/Polly/tree/master/src/Polly.Shared/Retry/RetrySyntax.cs)
+ [RetrySyntaxAsync.cs](https://github.com/App-vNext/Polly/tree/master/src/Polly.Shared/Retry/RetrySyntaxAsync.cs)
+ [RetryTResultSyntax.cs](https://github.com/App-vNext/Polly/tree/master/src/Polly.Shared/Retry/RetryTResultSyntax.cs)
+ [RetryTResultSyntaxAsync.cs](https://github.com/App-vNext/Polly/tree/master/src/Polly.Shared/Retry/RetryTResultSyntaxAsync.cs)

---

Re:
>add retryAttemptNumber to Context class

Because [users may have more than one retry-policy nested in a PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#using-the-same-type-of-policy-more-than-once-in-a-wrap), this option is not viable.  When the execution was through a PolicyWrap nesting more than one retry policy, it would not be clear what `Context.RetryAttemptNumber` meant.

---

Marking this 'up-for-grabs'.  Anyone who wants to take it on, post on the issue and - please ask if you have any questions!

**Comment by NRKirby** [comment]
I'm interested in picking this up. I've had a look in `RetrySyntaxAsync` but I'm having trouble figuring out what the overload signatures should be - can you give any guidance on this?

I added this overload, does it look ok? 

```
        /// <summary>
        ///     Builds a <see cref="Policy" /> that will wait and retry indefinitely
        ///     calling <paramref name="onRetry" /> on each retry with the raised exception, the current sleep duration, retry count, and context data.
        ///     On each retry, the duration to wait is calculated by calling <paramref name="sleepDurationProvider" /> with
        ///     the current retry attempt allowing an exponentially increasing wait time (exponential backoff).
        /// </summary>
        /// <param name="policyBuilder">The policy builder.</param>
        /// <param name="sleepDurationProvider">The function that provides the duration to wait for for a particular retry attempt.</param>
        /// <param name="onRetry">The action to call on each retry.</param>
        /// <returns>The policy instance.</returns>
        /// <exception cref="System.ArgumentOutOfRangeException">retryCount;Value must be greater than or equal to zero.</exception>
        /// <exception cref="System.ArgumentNullException">
        ///     sleepDurationProvider
        ///     or
        ///     onRetry
        /// </exception>
        public static RetryPolicy WaitAndRetryForeverAsync(this PolicyBuilder policyBuilder, Func<int, Context, TimeSpan> sleepDurationProvider, Action<Exception, TimeSpan, int, Context> onRetry)
        {
            if (sleepDurationProvider == null) throw new ArgumentNullException(nameof(sleepDurationProvider));
            if (onRetry == null) throw new ArgumentNullException(nameof(onRetry));

            return policyBuilder.WaitAndRetryForeverAsync(
                sleepDurationProvider,
#pragma warning disable 1998 // async method has no awaits, will run synchronously
                async (exception, timespan, i, ctx) => onRetry(exception, timespan, i, ctx)
#pragma warning restore 1998
            );
        }
```

If you could give me any advice on how I know what the overload signatures should be, I will make a start on this!

**Comment by reisenberger** [comment]
Hi @NRKirby Thank you for your interest in this!  @Freakazoid182 has made a PR ( #471 ) on this just hours earlier, so it may no longer be 'up-for-grabs'.  @Freakazoid182 / both: I haven't had the chance to read #471 today, but will do shortly.  @NRKirby  Do feel free to read #471; comments welcome!

**Comment by reisenberger** [comment]
Thank you @SashaPshenychniy for raising this!  Even more thanks @Freakazoid182 for implementing it (you have a credit in the Readme!).  Fixed in v6.1.0 which will release to nuget shortly.

**Comment by SashaPshenychniy** [comment]
Thank you, @Freakazoid182 and everyone who participated!

**Comment by Freakazoid182** [comment]
My pleasure @SashaPshenychniy and @reisenberger
