### ISSUE TITLE
Can I use context to pass in custom data?

### ISSUE THREAD

**Issue by rkandi590** [App-vNext/Polly#453]
_myPolicy.Execute((ctoken) =>
                {
                   //  post some data to an api and get httpresonse
                }
              },cancellationToken);

Upon handling the result, I want to access the count of the data that I had sent over to the api. Can I use context to achieve this?

Policy.HandleResult<HttpResponseMessage>(response =>
                        response.StatusCode == HttpStatusCode.BadRequest )
                    .WaitAndRetryForever(
                        retryAttempt => TimeSpan.FromSeconds(some time),
                        (exception, timespan) =>
                        {
                           // HERE -> I want to access and log the size of the data that was sent over to the api in the execute. 
                        });

**Comment by reisenberger** [comment]
@rkandi590 Yes, `Context` is the intended mechanism for passing custom data into an execution - and between different parts of an execution.  This blog post '[Using execution context in Polly](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/)' gives some examples.

If you need to exchange data between the executed Func and the `onRetry` delegate of the policy, use an overload [like this](https://github.com/App-vNext/Polly/blob/9da3f7dcea4b559fd9ec68a53dc4601c8977469f/src/Polly.Shared/Retry/RetryTResultSyntaxAsync.cs#L904) (or any richer overload) of `WaitAndRetryForever(...)`, where the `onRetry` delegate takes `Context` as an input parameter.  Similarly, use an [`ExecuteAsync(...)` overload which takes a Context input parameter](https://github.com/App-vNext/Polly/blob/f4404005b5c1e4965b74b3fe01a6b4ec0642f97a/src/Polly.Shared/Policy.Async.TResult.ExecuteOverloads.cs#L46), so that you can pass `Context` into the execution.

Assuming this is an async execution, you'll want to use the async variants of the overloads, as linked to above.

**Comment by rkandi590** [comment]
Thank you @reisenberger !  I have to however use Sync execution, but assuming that everything remains the same either way, closing this issue. Also, please let me know if that is not the case.
