### ISSUE TITLE
'CS0120: An object reference is required' when using Policy.Wrap static overload with single argument

### ISSUE THREAD

**Issue by yaireclipse** [App-vNext/Polly#460]
**Polly version**: 6.0.1.

**Step to Repro:**

1.  Install Polly version 6.0.1 and use it a new project.
2.  Add a file named `PollyStaticOverloadNotInferred` and copy the following text into it:

```csharp
namespace My.Namespace
{
  using Polly;

  public class PollyStaticOverloadNotInferred
  {
    public PollyStaticOverloadNotInferred()
    {
      var bulk = Policy.Bulkhead(1);

      Policy.Wrap(bulk, bulk); // compiles
      Policy.Wrap(bulk); // Error CS0120: An object reference is required for the non-static field, method, or property 'Policy.Wrap(ISyncPolicy)'

      var bulkGeneric = Policy.Bulkhead<string>(1);
      Policy.Wrap<string>(bulkGeneric, bulkGeneric); // compiles
      Policy.Wrap<string>(bulkGeneric); // Error CS0120: An object reference is required for the non-static field, method, or property 'Policy.Wrap<string>(ISyncPolicy<string>)'
    }
  }
}
```
3. Build project.

**Expected behavior:**

No error highlights by Visual Studio. After compilation, no compile errors.

**Actual behavior:**

Even before compilation, there are error highlights on the lines that invoke `Policy.Wrap` methods statically with a single argument. Compilation explicitly yields these errors.

The problem is that the compiler infers those method calls as the instance-methods that each accept a single argument:
*  [`public PolicyWrap Policy.Wrap(ISyncPolicy innerPolicy)`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Wrap/PolicyWrapSyntax.cs#L15); and
*  [`public PolicyWrap<TResult> Policy<TResult>.Wrap(ISyncPolicy innerPolicy)`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Wrap/PolicyWrapSyntax.cs#L51);

instead of the static-methods that accept varargs:
*  [`public static PolicyWrap Wrap(params ISyncPolicy[] policies)`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Wrap/PolicyWrapSyntax.cs#L87); and
*  [`public static PolicyWrap<TResult> Wrap<TResult>(params ISyncPolicy<TResult>[] policies)`](https://github.com/App-vNext/Polly/blob/master/src/Polly.Shared/Wrap/PolicyWrapSyntax.cs#L116).

I wondered how come C# lets these overloads live together in the same `Policy` class, but maybe the fact they're defined in different `partial` parts of `Policy`, it's OK.

You'd probably ask, why would I use the static varargs overload with a single argument, since when there's only one policy to wrap - why would I statically wrap it in the first place. That'd be a fair question :). The answer is that I indeed intended to wrap several policies, but ran into this unexpected compilation error on the way :).

So I'm not sure that it's worth fixing, but I think it's worth to be known, even if only for the sake of future developers that'd scratch their heads for the first time they try to wrap a policy.

If you *do* decide to fix this, a quick solution might be to rename the static overloads to something like `WrapAll`.

Thanks for the good work!
Yair

**Comment by reisenberger** [comment]
@yaireclipse Thanks for this clear and thorough analysis.  We'll have a think about whether there is a clever way to avoid this in a future release.  

As it happens we [explicitly don't (currently) support](https://github.com/App-vNext/Polly/blob/ed77fe7ffa04298031af911c99074172ed140bc5/src/Polly.Shared/Wrap/PolicyWrapSyntax.cs#L92-L93) the use of the static varargs overload with only one policy anyway (it intends to throw as that link shows). So even if the compiler inference ambiguity were resolved, it would not be a supported feature. This is because the internal design of the `PolicyWrap` is essentially a b-tree. By avoiding allowing a wrap of only one policy, we avoid a lot of runtime checks for a b-tree-that-isn't-really-a-b-tree. It was not intended however that that should express itself, unhelpfully, as a compiler overload inference failure! (not sure whether something has changed there in recent compiler inference or not)

Renaming overloads is a fix that would clear the issue as you say, but has the cost/benefit trade-off around being a breaking change for users.

For now I've added to the documentation ([wiki](https://github.com/App-vNext/Polly/wiki/PolicyWrap)) the clarification:

>All `PolicyWrap` instances must contain two or more policies.

Thanks again.

**Comment by yaireclipse** [comment]
@reisenberger Thanks for responding!

> By avoiding allowing a wrap of only one policy, we avoid a lot of runtime checks for a b-tree-that-isn't-really-a-b-tree.

That's actually a nice trick :)

> For now I've added to the documentation (wiki) the clarification.

That's great! Thanks!
