### ISSUE TITLE
UP-FOR-GRABS: Refine debug experience via SourceLink

### ISSUE THREAD

**Issue by alexakryvenko** [App-vNext/Polly#464]
Hi, 
I would like to request to remove .pdb files generation from Polly and serve them with separate Symbol package for debug purposes.
Having this .pdb files in Release mode of builds in the project made us manually exclude Polly pdbs from code coverage reports.

**Comment by reisenberger** [comment]
That seems like a good suggestion.  We should probably [publish symbol packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) instead.  _Other community views on this?_

[SourceLink](https://github.com/dotnet/sourcelink) probably isn't an option for us as a library as of this date, as we don't (as a library) want to target a `netcoreapp2.1` tfm.  However, that's based on a quick read of the docs; happy for comment from anyone who has insight on this.

**Comment by phatcher** [comment]
@reisenberger Have a look at https://github.com/Humanizr/Humanizer, they have successfully implemented GitLink and it works nicely

**Comment by reisenberger** [comment]
Also the new `<DebugType>embedded</DebugType>` to consider, as an option for this.  Discussion and further links from here: https://twitter.com/KirillOsenkov/status/1007052524946255872

**Comment by reisenberger** [comment]
It seems like [NewtonSoft.Json is successfully enabling SourceLink](https://twitter.com/JamesNK/status/1012198188520910848) and intends to start including .pdbs in nuget packages, as part of this.  Noting for reference.  We would have either that option of publishing symbol packages as [previously mentioned](https://github.com/App-vNext/Polly/issues/464#issuecomment-395220061).

**Comment by reisenberger** [comment]
Improving debug experience around Polly looks like a great area to improve the Polly experience with minimal other impact.  

Three main options:

1. Create and publish [Symbol packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) to SymbolSource
2. Use [SourceLink](https://github.com/dotnet/sourcelink)  (more info also in earlier comments)
3. Use the new [portable pdbs](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md), probably as `<DebugType>embedded</DebugType>` in the main Polly dll  (more info also in earlier comments) (would want to review size change of DLL; public reports seem v good but low-memory scenarios like Xamarin/embedded to keep in mind)

@alexakryvenko Do you know whether, with each of options 2 and 3 above, you would still have the problem of having to manually exclude Polly from your code coverage reports? (Also: what code coverage tool were you using?)

I'm going to 'up-for-grabs' this so that the core Polly team can focus on new functionality.  Happy to see contributions on any/all of 1, 2, 3 above.

**Comment by reisenberger** [comment]
@paulomorgado / anyone : We have now [consolidated the Polly solution](https://github.com/App-vNext/Polly/pull/606) similar to Paulo's original #504, which we wanted in before updating the Polly build for SourceLink.

**Up-for-grabs** again to add SourceLink to Polly.  From discussion between Paulo and I (thanks Paulo!) and further investigation [here](https://github.com/App-vNext/Polly/pull/502#issuecomment-437653893), it looks like we should/could:

+ Remove [BrutalDev/StrongNameSigner](https://github.com/brutaldev/StrongNameSigner) from the Polly build, and replace with eg `<AssemblyOriginatorKeyFile>...</AssemblyOriginatorKeyFile>` and `<SignAssembly>true</SignAssembly>` in the csproj (or similar)
  - BrutalDev/StrongNameSigner was useful when Polly published _both_ non-strong-named and strong-named packages from the same build, now we publish strong-named only.
+ Replace [direct call to nuget pack](https://github.com/App-vNext/Polly/blob/96a1f0d81b37255ced7a836f64fa322041584239/build.cake#L276-L283) with [dotnet pack](https://cakebuild.net/api/Cake.Common.Tools.DotNetCore.Pack/), as inserting the new `<repository commit="{specific-sha}">` attribute in the nupkg for SourceLink, relies on this - seems to be key step to get SourceLink working for Polly
+ Move everything in [Polly.nuspec](https://github.com/App-vNext/Polly/blob/v704or710/src/Polly.nuspec) into [Polly.csproj](https://github.com/App-vNext/Polly/blob/v704or710/src/Polly/Polly.csproj)
  - Removes duplication and risk of inconsistency in stating dependencies between nuspec and csproj
  - Everything in the nuspec seems [covered by new csproj tags](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties)
  - The lengthy `<releaseNotes>...</releaseNotes>` in the nuspec, we could replace just with a simple `<PackageReleaseNotes>See https://github.com/App-vNext/Polly/blob/master/CHANGELOG.md</PackageReleaseNotes>` in the `.csproj`

NB all work should be against [latest dev branch](https://github.com/App-vNext/Polly/tree/v704or710) as [this major commit consolidated the solution](https://github.com/App-vNext/Polly/commit/ced966fc1b1d836ecc8d7bfb3d3f9e8f86ddc45e).

**Comment by Kesmy** [comment]
@paulomorgado @reisenberger I noticed this was `up-for-grabs` and branched off of [v704or710](https://github.com/App-vNext/Polly/tree/v704or710).

Ran into a couple minor issues

1. `owner` is not available in the csproj nuget properties, it inherits from `Authors`. Should the new `Authors` be `App vNext` to match the csproj, or `Michael Wolfenden, App vNext` to match the nuspec?
1. Since `SourceLink` is still prerelease, is `1.0.0-beta2-18618-05` or `1.0.0-*` preferable?

**Comment by phatcher** [comment]
You can avoid dotnet pack entirely if you put a `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`in the project files

**Comment by reisenberger** [comment]
That's a great point, @phatcher . Having given this some thought, I'm coming down on the side that we stick with the current construction of the build script (ie still use `dotnet pack`), because we currently only build the nuget package if the test runs completely pass - and I like that cleanliness.  What do others think?

@Kesmy Answers coming to your other queries shortly. Huge thanks for picking this up!

**Comment by Kesmy** [comment]
I see both sides of the argument (and didn't even realise that `GeneratePackageOnBuild` was a thing, so thanks @phatcher !)

I like the idea of eliminating a big chunk of a build script, but I think at the end of the day, I prefer the hard-block on test failures.
-----
On a related note, the package restore step can be removed, and the build can automatically restore, but that change may not belong here (and is going to be similarly opinionated).

**Comment by reisenberger** [comment]
Hi @Kesmy Re the great queries ... (and: thanks again for picking this up!) : 

>1. owner is not available in the csproj nuget properties, it inherits from Authors. Should the new Authors be `App vNext` to match the csproj, or `Michael Wolfenden, App vNext` to match the nuspec?

Stay with `Michael Wolfenden, App vNext` for now. Per this [nuget doco](https://blog.nuget.org/20130205/managing-package-owners.html) (which seems to correspond with our experience even if dating from 2013):

>While each NuGet package’s nuspec metadata defines the package’s owner(s), the NuGet gallery at nuget.org ignores that piece of nuspec metadata. Instead, ownership of a package is defined by who publishes the package to the gallery.

---

Re:

>2. Since SourceLink is still prerelease, is `1.0.0-beta2-18618-05` or `1.0.0-*` preferable?

I would be good with `1.0.0-*` if we knew that robustly picked up the latest pre-release version.  There's some [relatively recent commentary](https://github.com/NuGet/Home/issues/912#issuecomment-456005110) tho that `1.0.0-*` is not entirely robust, and various hacky workrounds on linked threads.  Unless you think the situation is clearer than that, I'm happy we just go with `1.0.0-beta2-18618-05` and keep the build scripts clean.  Quick survey also: NewtonSoft.Json still [points at a specific](https://github.com/JamesNK/Newtonsoft.Json/blob/88dae521655b05bbe5b3d1821d82523a60d23dcc/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L37), and [sourcelink doco](https://github.com/dotnet/sourcelink/blob/master/README.md#githubcom-and-github-enterprise) specifies a specific, so seems expected practice.  We can always update it if problems emerge.  And we'll switch to `1.0` soon as they move off pre-release.

---

>the package restore step can be removed, and the build can automatically restore

Happy either way, depending on your available time.

Thanks again!

**Comment by Kesmy** [comment]
Thanks for the quick responses.

Updated the Authors, will leave the restore step alone. That will be consistent with independent build/test/package, and may make it easier to differentiate between types of error in a build.

**Comment by reisenberger** [comment]
@Kesmy Thank _you_.  Just tested out the debug experience against the newly-built package - awesome. :+1:

**Comment by reisenberger** [comment]
Closed via #616.  Huge thanks to @Kesmy for picking this up 🎆 .  Thanks to @paulomorgado for earlier contributions too :+1:

Release as part of Polly v7.1.0 shortly.
