### ISSUE TITLE
WaitAndRetryAsync does not use first sleep time

### ISSUE THREAD

**Issue by B1nke** [App-vNext/Polly#465]
When using multiple timespans with **WaitAndRetryAsync** (don't know if this affects other methods as well), the onRetry action is hit directly when I get a result back from my API, and it does not wait for the expected 20 seconds. The call to the action is made first, and then it will use the first timespan for sleeping.

This is most noticeable when just providing a single timespan. The action will be executed directly, and then it will sleep for the timespan provided, but then it will never hit the action again because there are no more timespans.

Here's the gist of the code I use
```
var TimeSpans = new [] {
  TimeSpan.FromSeconds(20),
  TimeSpan.FromSeconds(20)
};

var retryPolicy = Policy
    .HandleResult<HttpResponseMessage>(r => r.StatusCode != HttpStatusCode.OK)
    .Or<Exception>()
       .WaitAndRetryAsync(TimeSpans, (exception, timeSpan, retryCount, context) =>
       {
            _log.Exception(GetRetryException(exception));
        });

await retryPolicy.ExecuteAsync(CallApiAsync);
```

**Comment by reisenberger** [comment]
Thanks for the question @B1nke ! I wonder if something else may be affecting your cases, or if you are expecting WaitAndRetryAsync to behave differently from actual in some way I haven't grasped, as I'm not sure I can reproduce the problems. Are you able to provide any minimum runnable code reproducing a problem? And/or clarify what you are expecting to happen, and what is not happening?  

Re: 

>the onRetry action is hit directly when I get a result back from my API [...] The call to the action is made first, and then it will use the first timespan for sleeping

This is intended - see [retry wiki](https://github.com/App-vNext/Polly/wiki/Retry).  The policy calls the `onRetry` delegate first (before waiting) so that there is some immediate feedback what happened with the execution, as soon as we have the execution result.  This ensures it is possible to log, for example, that the execution failed and the wait-before-next-retry commenced - and capture that logging even if the next thing that occurs is cancellation of that wait.  

>WaitAndRetryAsync does not use first sleep time

Can you clarify or provide example code demonstrating? I re-checked [this test](https://github.com/App-vNext/Polly/blob/64b21c82d79c2b441be566d06f2dfb5bcfddd338/src/Polly.SharedSpecs/Retry/WaitAndRetryAsyncSpecs.cs#L226-L249) and think it confirms that the first sleep time is used.

>when just providing a single timespan. The action will be executed directly, and then it will sleep for the timespan provided, but then it will never hit the action again because there are no more timespans.

Which action is it not hitting again that you are expecting - the `onRetry` action or the action executed through `.ExecuteAsync(...)`?  If meaning the delegate executed through `.ExecuteAsync(...)`: I re-checked and think that [this test](https://github.com/App-vNext/Polly/blob/64b21c82d79c2b441be566d06f2dfb5bcfddd338/src/Polly.SharedSpecs/Retry/WaitAndRetryAsyncSpecs.cs#L252-L276) confirms that the delegate executed through `ExecuteAsync(...)` is executed one more time than the number of timespans provided.  

If you are looking for a policy which retries repeatedly (forever) on failure, with a wait of `TimeSpan.FromSeconds(20)` between each try, there is this option:

    var retryPolicy = Policy
        .HandleResult<HttpResponseMessage>(r => r.StatusCode != HttpStatusCode.OK)
        .Or<Exception>()
           .WaitAndRetryForeverAsync(i => TimeSpan.FromSeconds(20), (exception, timeSpan, context) => { /* logging */ });

Hope this helps. Let me know if I still haven't understood a problem you are seeing!

**Comment by B1nke** [comment]
I'm sorry, I was just looking at the `onRetry` action and logging from there and I was expecting it to hit one last time after the last call to `ExecuteAsync(CallApiAsync)` had failed.
After adding logging to `CallApiAsync` I can see that it's executed after the expected amount of time without executing `onRetry` afterwards.
