### ISSUE TITLE
[Question]: How wrap service API with policies

### ISSUE THREAD

**Issue by phatcher** [App-vNext/Polly#467]
New to Polly so please forgive the naive questions...

My use case is common, in that I have a service definition which calls an API using HttpClient to get some data, and I can see from the examples how to configure this with policies to handle retry/timeout/bulkhead etc.

What I'm struggling with is how to handle things like caching and fallback, both from a per-user basis and that my API has multiple methods which have different parameters and results.  Looking at it caching the HttpResponseMessage doesn't appeal, I'd prefer to retain the actual result.

I think one approach is to proceed as follows

1. The API client which uses HttpClient is configured with retry/timeout/bulkhead policies
2. I have another implementation of the API client which is policy aware and it handles caching/fallback etc and inject 1. into it

What I don't like about this it looks like I'll have a lot of boilerplate code which is just wrapping calls to the real API which suggest that I've missed something somewhere?

**Comment by reisenberger** [comment]
Paul, Your considerations and reasoning make sense to me.  **TL;DR** For this use case, one layer with resilience policies in the `HttpClient` working at the `HttpResponseMessage` level; and a layer further out where more content-aware policies (cache; fallback) work at the level of the actual response.  

A few thoughts in detail:

+ Retry, circuit-breaker, timeout, bulkhead can certainly be common to all endpoints on an API with the same BaseUrl, and as such the policies can be reused and embedded within the HttpClient.  Note that a best practice pattern is to place the policies [in `DelegatingHandler`s](https://stackoverflow.com/a/35183487/) as outgoing middleware, to sidestep a number of issues detailed in that StackOverflow discussion.  In ASP NET Core 2.1 you can [use IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1) to configure this and to manage the HttpClient (and internal handler) lifecycles; we describe this in detail also [in the Polly wiki](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory).  Those policies _can_ be common to all API endpoints on the same base address, but of course you can choose to scope them differently if you want to group calls to different endpoints in different bulkheads or something like that.

+ Cache: you _can_ use the same single Cache policy instance across different API endpoints (because the cache policy just defines the underlying cache and ttl to use, while a [varying `OperationKey` can be passed into the execution to specify the _key_ to cache under](https://github.com/App-vNext/Polly/wiki/Cache#default-cachekeystrategy-if-none-specified)).  However, there are (as you allude) a number of uncomfortable points around caching at the `HttpResponseMessage` level, as we discuss [here](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-cachepolicy) and [here](https://github.com/App-vNext/Polly/wiki/Anonymising-and-de-timestamping-cached-data#example-httpresponsemessage) and Scott Hanselman discusses [here](https://www.hanselman.com/blog/TheProgrammersHindsightCachingWithHttpClientFactoryAndPollyPart2.aspx) (Scott's other posts on caching in that series give good food for thought too).  

+ Fallback likewise is content-aware, so perhaps sits better at an layer where the content has already been extracted from the http call.

Re:

>a lot of boilerplate code which is just wrapping calls to the real API

sounds like a classic decorator, effectively what this is - seems reasonable. 

Thanks for sharing your q and thoughts; hope some of the links herein are useful.

**Comment by phatcher** [comment]
Dylan

Thanks for the response. I'd followed Scott's blog posts and as I'm currently writing some new microservices in ASP.NET Core 2.1 I thought I'd use Polly rather than my current hand-rolled implementation of retry/caching

So my current implementation normally has something like this...

- IFooService : The service interface
- FooServiceClient : Client implementation that talks over http
- CachingFooServiceClient : Caching implementation that takes a IFooService and a cache implementation

What I think the new architecture looks like is

- IFooService : Same as before
- FooServiceClient : Same as before but configured via Polly to have appropriate retry/timeout/circuit-breaker policies
- FallbackFooServiceClient : Delivers data/response in case of service failure, basically a null object pattern in case of get and a wrapped exception in the case of put/post
- PolicyFooServiceClient: Takes two IFooServices and wraps with with cache/fallback policies

This then isolates most of the front-end from service failures and it can decide what to do when presented with the null object.

The data we are presenting changes relatively infrequently but it's important to present new data when it does arrive, so I can also see some interesting use cases for a two level cache; one that has the normal expiry and another with a long timeout which is used when the service call fails instead of a null object response.

**Comment by reisenberger** [comment]
@phatcher . Closing this as I think we are done here.  Do however re-open, or start a new issue, if there's more to discuss.
