### ISSUE TITLE
How to dynamically set sleep time and retry times! I want dynamically sleep time and retry times By Excute Result

### ISSUE THREAD

**Issue by taomylife521** [App-vNext/Polly#473]

**Comment by reisenberger** [comment]
@taomylife521 For a wait-before-retry time set according to the execution result, see the [discussion on handling 429 RetryAfter](https://github.com/App-vNext/Polly/wiki/Retry#retryafter-when-the-response-specifies-how-long-to-wait) and code samples linked to from there.

For controlling how many times to retry based on execution result, I would suggest using `WaitAndRetryForever(...)`; when you wish to not make further retries, throw an exception the policy does not handle.

**Comment by taomylife521** [comment]
For Example: 
public void Excute()
        {
            int retryCount = 3;
            int sleepTime = 1;
            RetryPolicy policy = Policy.Handle<Exception>((ex) =>
            {
                return true;
            }).WaitAndRetry(retryCount, attempt => TimeSpan.FromSeconds(sleepTime), (exception, timespan) => { 
                Console.WriteLine("休眠" + sleepTime.ToString() + "秒后重试");
            });
            try
            {
                policy.Execute(() =>
                {
                    using (var client = new WebClient())
                    {
                        string response = null; //client.DownloadString(Configuration.WEB_API_ROOT + "/api/values/");
                        if (response == null)    
                        {
                            //Here TODO: i want to dynamically set retryCount and sleepTime By response
                            retryCount = 4;
                            sleepTime = 2;
                        }
                        Console.WriteLine(response);
                       
                       
                    }
                });

            }
            catch (Exception) { }
        }

**Comment by reisenberger** [comment]
@taomylife521 . Polly policies are intentionally immutable.  We intentionally do not allow the main parameters (eg number of retries) of an existing Polly `Policy` instance to be modified after initial configuration, because the consequences could be indeterminate for instances used in multi-threaded scenarios.  

In your [specific example](https://github.com/App-vNext/Polly/issues/473#issuecomment-401265114), since you create and use the policy within the method and all variables are method-invocation-scoped, you could thread-safely do something like that.  Because we intentionally do not allow the number of retries to be modified after configuration, you would have to use `WaitAndRetryForever(...)` and throw when you do not wish to retry any further, per my [original comment](https://github.com/App-vNext/Polly/issues/473#issuecomment-401261146):

        public void Excute()
        {
            int retryCount = 3;
            int sleepTime = 1;
            RetryPolicy policy = Policy.Handle<Exception>((ex) =>
            {
                return (retryCount-- > 0);
            }).WaitAndRetryForever(attempt => TimeSpan.FromSeconds(sleepTime), (exception, timespan) => { 
                Console.WriteLine("休眠" + sleepTime.ToString() + "秒后重试");
            });
            try
            {
                policy.Execute(() =>
                {
                    using (var client = new WebClient())
                    {
                        string response = null; //client.DownloadString(Configuration.WEB_API_ROOT + "/api/values/");
                        if (response == null)    
                        {
                            **//Here TODO: i want to dynamically set retryCount and sleepTime By response
                            retryCount = 4;
                            sleepTime = 2;**
                        }
                        Console.WriteLine(response);
                       
                       
                    }
                });

            }
            catch { }
        }

**Comment by reisenberger** [comment]
Hi @taomylife521 . Hope this helped.  Closing due to lack of further comment. Do however re-open, or start a new issue, if you require further assistance.
