### ISSUE TITLE
Can I use multiple CircuitBreakerPolicy?

### ISSUE THREAD

**Issue by shagilt** [App-vNext/Polly#474]
Hi,

At present, we have a circuit breaker policy with MinimumThroughPut as 100, Sampling duration as 1 min and failure threshold 50%. But we also wanted to add another policy to detect consistent 90% failures for longer duration. In this case we may have lower throughput(say 10). 

Can i achieve this by adding new policy? IS there a different way to accomplish this?

**Comment by reisenberger** [comment]
@shaglit  Yes.  `PolicyWrap` ([readme](https://github.com/App-vNext/Polly#policywrap); [wiki](https://github.com/App-vNext/Polly/wiki/PolicyWrap)) is the way to combine more than one policy, so that multiple policies can be applied easily to one call.

There are no barriers on the way you can combine policies with `PolicyWrap`: you can certainly combine two policies of the same type (eg two circuit-breakers), as [described in the wiki here](https://github.com/App-vNext/Polly/wiki/PolicyWrap#using-the-same-type-of-policy-more-than-once-in-a-wrap).

**Comment by shagilt** [comment]
Thank you @reisenberger I will check PollyWrap API.

**Comment by reisenberger** [comment]
Closing due to lack of further comment. Do however re-open, or start a new issue, if you require further assistance.
