### ISSUE TITLE
Throw on final exception

### ISSUE THREAD

**Issue by grik001** [App-vNext/Polly#500]
Hi,

Is it possible to throw the exception if the final Retry Fails? I am using the WaitAndRetryAsync, but I wish to throw the exception if the final retry throws and exception.

I can see the CircuitBreaker throws the exception but is it possible waiting before retries?

Thanks in advance!

**Comment by reisenberger** [comment]
Hi @grik001  

>Is it possible to throw the exception if the final Retry Fails?

That is exactly what the library does by default - see [how retry works](https://github.com/App-vNext/Polly/wiki/Retry#how-polly-retry-works) in the wiki.

Let me know if I've not understood the question, and you're after something slightly different!

**Comment by grik001** [comment]
I will test this again, but I am sure that WaitAndRetryAsync was blocking the exception even if the last try does not succeed.

**Comment by reisenberger** [comment]
Hi @grik001 . Happy to look at any code if you can post a repro.  Here within Polly is a [unit test demonstrating that WaitAndRetryAsync does rethrow the final exception](https://github.com/App-vNext/Polly/blob/7c5ecfcfc7abceb33b19bcd8a2d252bd59a3df91/src/Polly.SharedSpecs/Retry/WaitAndRetryAsyncSpecs.cs#L117-L131).

Couple of things that could cause a final exception not to be rethrown:

+ `.ExecuteAsync(...)`, like any async API, returns `Task`. If the result of `.ExecuteAsync(...)` isn't `await`ed, then the exception will remain captured on the `Task` rather than rethrown.
+ If using [`.ExecuteAndCaptureAsync(...)`](https://github.com/App-vNext/Polly#post-execution-capturing-the-result-or-any-final-exception), then the design intent of that is to capture any final exception into the `FinalException` property.  `.ExecuteAndCaptureAsync(...)` captures any final exception, whereas `.ExecuteAsync(...)` rethrows it.

**Comment by grik001** [comment]
@reisenberger 

Hi, I confirmed that you are right, sorry for wasting your time and thanks for the explanation

**Comment by reisenberger** [comment]
No problem @grik001 ! Let us know if there is anything else we can help with.
