### ISSUE TITLE
.Net Core: Access Information about retry attempts from HttpResponseMessage returned from HttpClient

### ISSUE THREAD

**Issue by chrisckc** [App-vNext/Polly#505]
**Summary: What are you wanting to achieve?**

I want to be able to show if and how many retries occurred after making a request from a Typed HttpClient in .NET Core.

I am already logging the retries inside the WaitAndRetryAsync onRetryAsync function, but want to have access to the information outside this function, ideally as part of the HttpResponseMessage obtained from the HttpClient: 
`var response = await _client.GetAsync(resource)`
eg. stored in the response.RequestMessage.Properties 

<br/>
<br/>

**What code or approach do you have so far?**  

I noticed that the response.RequestMessage.Properties contains a Key "PolicyExecutionContext" but its value is always null. 
`Polly.Context context = response.RequestMessage.Properties[PolicyExecutionContext];`

However Inside the onRetryAsync function is is available directly as one of the function parameters (context) and also via:
`result.Result.RequestMessage.Properties[PolicyExecutionContext];`

I created a class called PollyInfo where i store the number of retry attempts and details of each failure. Inside the onRetryAsync function i create and store an instance of PollyInfo in the context as so: `context["PollyInfo"] = pollyInfo;`
On each retry the instance is updated with the retry count and failure details.

As the PolicyExecutionContext is not available in the HttpResponseMessage obtained from the HttpClient, i checked the case from inside a DelegatingHandler:

```
         services.AddHttpClient<ApiClient>(client => 
                {
                    client.BaseAddress = new Uri(configuration["Api:BaseUrl"]);
                    .......
                })
                .ConfigurePrimaryHttpMessageHandler(() => new MyHandler
                {
                    InnerHandler = new HttpClientHandler()
                })
                .AddPolicyHandler(waitAndRetryPolicy);
```

It works! inside the DelegatingHandler's SendAsync override, the PolicyExecutionContext is not null.
`Polly.Context context = request.Properties[PolicyExecutionContext];`

So what i did was just transfer the "PollyInfo" object from the Polly context into the request.Properties, or in the case of an exception into Exception.Data

```
            try
            {
                TransferPollyInfo(request);
                return await base.SendAsync(request, cts?.Token ?? cancellationToken);
            }
            catch(Exception ex)
            {
                TransferPollyInfo(ex, request);
                throw ex;
            }
```

```
   // Stores the PollyInfo object into the Request properties    
   private void TransferPollyInfo(HttpRequestMessage request) {
        request.Properties["PollyInfo"] = GetPollyInfo(request);
    }

    // Stores the PollyInfo object into the Exception data
    private void TransferPollyInfo(Exception exception, HttpRequestMessage request) {
        exception.Data["PollyInfo"] = GetPollyInfo(request);
    }

   private object GetPollyInfo(HttpRequestMessage request) {
        object context = null;
        object pollyInfo = null;
        request.Properties.TryGetValue("PolicyExecutionContext", out context);
        if (context != null) {
            ((Polly.Context)context).TryGetValue("PollyInfo", out pollyInfo);
        }
        return pollyInfo;
    }
```

Note that this only works if the DelegatingHandler is the Primary or outermost Handler in the pipeline, ie. the one that receives the request first.

This approach works and i am now able to access retry info using:

```
           try {
                using(var response = await _client.GetAsync(resource)) {
                    try {
                        PollyInfo pollyInfo = GetPollyInfo(response);
                        //Do other stuff...
                    } catch (Exception ex) {
                        _logger.LogError($"An exception occurred doing other stuff");
                    }
                } 
            } catch (Exception exception) {
                // Handles communication errors such as "Connection Refused" etc.
                // Network failures (System.Net.Http.HttpRequestException)
                PollyInfo pollyInfo = (PollyInfo)exception.Data["PollyInfo"];
            }


      private PollyInfo GetPollyInfo(HttpRequestMessage request) {
            object pollyInfo = null;
            request.Properties.TryGetValue("PollyInfo", out pollyInfo);
            return (PollyInfo)pollyInfo;
        }
```

Is there a built-in or better way of doing this? If not can something be done to avoid having to do the above to get the retry info outside of the HttpClient?

**Comment by reisenberger** [comment]
@chrisckc Great question.  As you rightly observe:

+ a `Polly.Context` travels with each Polly execution, allowing information exchange between pre-execution, during-execution and post-execution.  
+ that `Polly.Context` is [attached to the HttpRequestMessage](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/HttpRequestMessageExtensions.cs), so that while the [call through Polly is within the DelegatingHandler configured by HttpClientFactory](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L130), there is a bridge allowing you to obtain/set that `Polly.Context` via the `HttpRequestMessage`.

I believe you are finding `RequestMessage.Properties[PolicyExecutionContext]` to be `null` after execution because, when we built the Polly-HttpClientFactory integration, we [chose, for cleanliness, to clean it up if it was generated internally, not user-supplied](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L117-L138).  

If you call [`request.SetPolicyExecutionContext(...)`](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/HttpRequestMessageExtensions.cs#L48) _yourself_ on an `HttpRequestMessage` before passing it into a call through `HttpClient`, then the `Polly.Context` you supply will [not be cleaned up](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L134-L136), and you will still have access to it after execution. This may allow you to dispense with/simplify some of your info-capturing code.

Where your call into `HttpClient` is an overload such as `await _client.GetAsync(resource)`, which doesn't directly take an `HttpRequestMessage`, then to use the above technique, you would of course have to [replace that call with the underlying SendAsync call taking an `HttpRequestMessage` which it drills down to](https://github.com/dotnet/corefx/blob/e0ba7aa8026280ee3571179cc06431baf1dfaaac/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L260-L300).  On that point we had no other option: overloads such as `HttpClient.GetAsync(resource)` understandably weren't up-for-grabs for modification to add `Polly.Context`.

Hope this helps. I haven't followed through all the reasons for the `PollyInfo` class in your example, but intuition suggests you may be able to replace that with an instance of `Polly.Context` which you create and pass into the execution.

**Comment by reisenberger** [comment]
[Added this](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#use-case-exchanging-information-between-policy-execution-and-calling-code) to the [Polly and HttpClientFactory](https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory) documentation.

**Comment by chrisckc** [comment]
@reisenberger Thanks for the response, very helpful,  i have just read the update you have made to the docs, nicely written.

I have now been able to refactor my code to achieve better separation of concerns.

I still need to use a DelegatingHandler for the case where an exception occurs due to a network error or timeout etc. In this case my PollyInfo object needs to be transferred into the Exception Data.

The difference now is that i have been able to split this code out into a separate handler from some other tasks that needed to be done.

It would be useful if the Polly.Context could be automatically transferred into the Exception data, or  was made to be a configurable option?

**Comment by reisenberger** [comment]
@chrisckc  I haven't sight of the full code, so am guessing what requires the transfer of the gathered `PollyInfo` via the `exception.Data[]` dictionary.  Is the issue that, if the execution throws, then you can no longer obtain the `Polly.Context` via `result.Result.RequestMessage.GetPolicyExecutionContext()` ? 

If so: With a pattern where you pass a `Polly.Context` into the execution yourself (as below) you have access to it everywhere post-execution because it's still in scope :

    var context = new Polly.Context();
    HttpRequestMessage request = /* whatever */;
    request.SetPolicyExecutionContext(context); 

    try
    {
        var response = await client.DoWhateverAsync(/* some overload taking HttpRequestMessage request */);
    }
    catch
    {
        // Handling for eventual error despite resilience strategies (unless you have already used a FallbackPolicy)

        // Of course the variable `context` (the same `Polly.Context` instance that was passed to onRetryAsync that you added data to) is still in scope here
    }

    // And ditto `context` local variable obvs still available here

But the above approach does require you to use overloads on `HttpClient` which take an `HttpRequestMessage` as an input parameter. 

---

Re:

>It would be useful if the Polly.Context could be automatically transferred into the Exception data

We could consider this but it would be a change in the Microsoft codebase [here](https://github.com/aspnet/HttpClientFactory/blob/release/2.2/src/Microsoft.Extensions.Http.Polly/PolicyHttpMessageHandler.cs#L130) (at some future release), rather than in the Polly codebase. And it would necessitate an extra catch-and-rethrow, which would be a (minor) performance penalty, but a penalty paid by everybody using the codepath whether they were interested in the `Polly.Context` or not.  And there are patterns avoiding the need for it such as the one posted here (or the custom DelegatingHandler you created).

Will keep this in mind but see if more users hit the same problem before we have the next dev round with the MS team.

**Comment by chrisckc** [comment]
@reisenberger Good point, I only quickly jumped back into the code the other day to do a quick refactor to check that your suggestion worked. Now that i have revisited the code properly, as you have pointed out above, in the case of an exception i can obtain the Polly.Context from inside the method which is making the request.

I have now done away with the additional delegating handler (which had to do a catch and re-throw to inject the "PollyInfo" object) as everything Polly related can be handled in my "ApiClient" base class. I am still extracting and injecting my "PollyInfo" object into either the request properties or the exception data, but now doing it all inside the method which makes the request in the "ApiClient" base class.

The "PollyInfo" object is really "RetryInfo" and contains properties such as "RetryCount" and a list of objects that describe the failure reasons and wait times etc.

The response or exception is passed along to another class for processing and i decided that it was cleaner to augment the response.request properties or exception data with the "RetryInfo" object than pass it over separately.

The object which processes the response or exception does not care about where the retry info came from,  if it's available then make use of it. This way i can more easily substitute Polly for another library that handles retries, or re-use code in other projects that don't need Polly. Not that i can see my self using something other than Polly at the moment as it seems to be very good!

Re my previous statement:

> It would be useful if the Polly.Context could be automatically transferred into the Exception data

I no longer feel that this would provide any benefit.

Thanks!

**Comment by reisenberger** [comment]
Thanks @chrisckc ! Closing this out, as I think we have answered everything; and updated the doco to capture the learnt.
