### ISSUE TITLE
Policybuilder<TO> does not contain a definition for circuit Breaker Async

### ISSUE THREAD

**Issue by Shadowman4205** [App-vNext/Polly#529]
Hello, 

what am i missing here?

```
var retryPolicy = Policy.Handle<Exception>(e => !(e is BrokenCircuitException))
                                    .OrResult<TO>(a => a.Success != null)
                                    .WaitAndRetryForeverAsync(retryAttempt => TimeSpan.FromSeconds(Math.Pow(1, retryAttempt)));  

var circuitBreakerPolicy = Policy.HandleResult<TO>(a => a.Success != null)
                                             .CircuitBreakerAsync(
                                                  exceptionsAllowedBeforeBreaking: 4,
                                                  durationOfBreak: TimeSpan.FromSeconds(10),
                                                  onBreak: (ex,  breakDelay) =>
                                                  {
                                                      _logger.Console("Circuit Breaker Logging: Breaking the circuit for " + breakDelay.TotalSeconds);

                                                      // ConsoleHelper.WriteLineInColor("..due to: " + ex.Message, ConsoleColor.Magenta);
                                                  },
                                                  onReset:() => _logger.Console("Circuit Breaker Logging: Call ok! Closed the circuit again!"),
                                                  onHalfOpen: () => _logger.Console("Circuit Breaker Logging: Half-open: Next call is a trial!")
                                             );

PolicyWrap policyWrap = Policy.WrapAsync(retryPolicy, circuitBreakerPolicy);
```
on 

> var circuitBreakerPolicy =  Policy.HandleResult<TO>(a => a.Success != null) 

I am geting this

`'PolicyBuilder<TO>' does not contain a definition for 'CircuitBreakerAsync' and the best extension method overload 'CircuitBreakerSyntaxAsync.CircuitBreakerAsync(PolicyBuilder, int, TimeSpan, Action<Exception, TimeSpan>, Action, Action)' requires a receiver of type 'PolicyBuilder'
`

**Comment by reisenberger** [comment]
@Shadowman4205 The overload you are looking for [exists here](https://github.com/App-vNext/Polly/blob/2ca4533a2b3f5f4b1e9fcf5cd4dd4a873c9891af/src/Polly.Shared/CircuitBreaker/CircuitBreakerTResultSyntaxAsync.cs#L135).  

The compiler is not finding it because, as the overloads change from exception-handling only, to also handling results (as you are using), we rename the parameters accordingly.  So the parameter `exceptionsAllowedBeforeBreaking:` becomes `handledEventsAllowedBeforeBreaking:`.  (For info, the other change is: the type of the first input parameter to `onBreak` changes from `Exception` to `DelegateResult<TO>`.)

Delete `exceptionsAllowedBeforeBreaking:` from your code and the compiler should find the overload; then hover/whatever to reveal the intellisense for the found overload and you should see the matched parameter is called `handledEventsAllowedBeforeBreaking:`.

Let me know if that sorts it for you.

**Comment by reisenberger** [comment]
@Shadowman4205 Closing on the assumption this solved the problem, but please reopen (or raise another issue) if you need any further assistance.
