### ISSUE TITLE
Feature request - public API for the policies list

### ISSUE THREAD

**Issue by DennisNerush** [App-vNext/Polly#54]
It will be great if you could add a public API for the policies collection (the ones that are internal in PolicyBuilder) so it would be possible to cancel or reset a policy. Extremlly useful in integration tests when testing a class that uses the policy features. I want the ability to reset the policy after each test.

**Comment by DennisNerush** [comment]
Currently I do this:

  private void ResetPolicy(Policy policy)
        {
            var privatePolicy = policy.GetType().GetField("_policy", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(policy);
            var exPol = privatePolicy.GetType().GetField("_exceptionPolicy", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(privatePolicy);
            var target = exPol.GetType().GetField("_target", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(exPol);
            var state = target.GetType().GetField("policyState").GetValue(target);
            state.GetType().GetMethod("Reset").Invoke(state, null);
        }

**Comment by DennisNerush** [comment]
IPolicy is my interface

**Comment by joelhulen** [comment]
Off the top of my head, I don't see any drawback to exposing the policies list. Marking this issue for review.

**Comment by DennisNerush** [comment]
Thank you

**Comment by reisenberger** [comment]
Hi @DennisNerush Many thanks for the idea here and your interest in the Polly library!

Polly does not currently maintain an internal list of the policies which have been created.  I would be reluctant to recommend adding this, because it could constitute a memory leak.  At the moment, if somebody codes `Policy.Handle<Whatever>().Retry().Execute(...)` (or similar), the single-use policy created is, in due course, garbage-collected.  If otoh Polly were maintaining some static/thread-safe list of all policies created, single-use policies would not be garbage-collected and (think high-volume scenarios) could eventually constitute a memory-leak.  Therefore recommending this one as 'wont fix'

There is nothing of course to stop library users holding references to created policies themselves (`var myPolicy = Policy.Handle<Whatever>().Retry();`)

Regarding the ability to reset a circuit-breaker policy, this seems like a valuable addition for other reasons too (eg for operational control); keeping #62 open to track that.
