### ISSUE TITLE
Consider adding .netfx target to avoid huge dependency graph

### ISSUE THREAD

**Issue by Tyrrrz** [App-vNext/Polly#545]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

Currently, when adding Polly's nuget package in a project targetting .net471 or lower, the package comes with a huge list of System.* dependencies. This is annoying because it makes the dependency list messy and also makes nuget restore slower.

**Describe your proposed or preferred solution**:

Add a .netfx target. Microsoft recommends adding .net461 if you're targetting only .netstandard2.0, but since Polly also targets .netstandard1.1, it would make sense to add .net45 too.
Source: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting
![image](https://user-images.githubusercontent.com/1935960/49329363-42351d00-f586-11e8-8d6d-21ff3d203ea1.png)

**Describe any alternative options you've considered**:

None.

**Any additional info?**

Right now I'm staying on Polly 5.x because of this issue, as it was still targetting .net45.

**Comment by reisenberger** [comment]
@Tyrrrz , We [have this under consideration](https://github.com/App-vNext/Polly/blob/9b9a3f5f4097fab50e88214c35210ff3232a050b/src/Polly.Specs/Polly.Specs.csproj#L4) as part of #504 (simplifying the project structure to make multi-targeting easier). We will re-visit this when #504 progresses (after 508 and 536).  

I noticed there are some mixed opinions about that Microsoft recommendation in the feedback to the doc: https://github.com/dotnet/docs/issues/8997 ; https://github.com/dotnet/docs/issues/8896 , so we'd gladly welcome further feedback from our .NET Framework users (or Microsoft) about the .NET Framework library-consumption experience.

**Comment by reisenberger** [comment]
Posting x-refs to other issues - and other repos discussing the same issues - for future ref:

+ https://github.com/App-vNext/Polly/issues/655
+ https://github.com/dotnet/docs/pull/9033#discussion_r275600751 ; https://github.com/terrajobst/require-net472
+ https://github.com/StephenCleary/AsyncEx/issues/173#issuecomment-491898242
+ https://github.com/dotnet-state-machine/stateless/pull/320

**Comment by reisenberger** [comment]
Polly v7.2.0 [has been published](https://www.nuget.org/packages/polly) with .NET Framework targets 4.6.1 and 4.7.2 now supported natively as part of the nuget package, because of the issues in the join between .NET Standard 2.0 and .NET Framework up to 4.7.1.

Per discussion in the [issues linked here](https://github.com/App-vNext/Polly/issues/545#issuecomment-502480771), a .NET Framework 4.7.2 target has been added also _even though the experience with .NET Framework 4.7.2 consuming .NET Standard 2.0 packages is smoother_ , because without it, the presence of the .NET 4.6.1 Framework target in the nuget package may cause nuget tooling to install the .NET4.6.1 version of Polly into .NET4.7.2 projects _even though they could_ consume .NET Standard 2.0.

**Comment by Tyrrrz** [comment]
Awesome!
