### ISSUE TITLE
How to defer declaration of onRetry method in RetryPolicy

### ISSUE THREAD

**Issue by ankitgh** [App-vNext/Polly#549]
**Summary: What are you wanting to achieve?**
I don't want to create a new retrypolicy instance on each communication and want to defer onRetry function definition to the communication call. 
In my class, i have created a retry policy instance as a class member and using it on communication but i can't access onRetry method on retryPolicy instance.  

**What code or approach do you have so far?**  

```
/// <summary>
/// Retry handler to handle retries.
/// </summary>
private Action<Exception, int> retryHandler;
```
Inside constructor - 

```
this.writerPolicy = Policy.Handle<TimeoutException>().RetryAsync(retryCount, onRetry: this.retryHandler);
```

How to defer retryHandler definition later.

**Comment by reisenberger** [comment]
@ankitgh Welcome to Polly.  It is not possible to change or add an `onRetry` method after the policy has been configured.  This is intentional: Polly adopts the principle that policies should be immutable once constructed.

What is the reason for wanting to add `onRetry` to the policy later?  Is it that the `onRetry` wants to exchange information with other variables / context at the calling site?  If so, Polly provides the `Polly.Context` class as a way of doing this.  You can pass a `Context` instance into the execution, you can access that `Context` instance in the `onRetry` delegate, and (if it was in scope) you also have access to the `Context` instance after the execution.

For more information on that, see:

+ the [basic examples in the readme](https://github.com/App-vNext/Polly#step-3--execute-the-policy)
+ a [blog on this topic](http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/)

---

If that doesn't help, please provide more code to allow us to see more what you are seeking to achieve, and why.

**Comment by reisenberger** [comment]
Closing due to lack of further response.  However, if you do require further assistance, please do open another question, or ask on our slack channel, or stack overflow.  It would also be useful to have a longer description of what you are seeking to achieve, to be able to help in more depth.
