### ISSUE TITLE
Handle different exceptions with custom behavior

### ISSUE THREAD

**Issue by confusedIamHowBoutU** [App-vNext/Polly#603]
After reading https://github.com/App-vNext/Polly/issues/104
Is any functionality planned to have one policy handle multiple exceptions with each having custom behavior. 

    Policy
        .Handle<FooException>(() -> log.Error("Foo"))
        .Handle<BarException>(() -> log.Error("Bar"))
        .Execute(() -> DoSomething())

Thanks

**Comment by reisenberger** [comment]
Hi @confusedIamHowBoutU , thanks for the question. [`PolicyWrap`](https://github.com/App-vNext/Polly/wiki/PolicyWrap) already provides this functionality, and there are no plans to have one policy handle multiple exceptions differently in any way other than PolicyWrap.  

There is also no intention to develop a long-running chaining syntax to result in equivalent `PolicyWrap` outputs (though somebody could develop it as a Polly.Contrib if they wanted to). When PolicyWrap was designed, we moved away from the long-running chaining syntax, as it was found to be limiting (/to lead to significantly more complexity) for defining policy instances which could be recombined in different ways in different PolicyWraps.  Stateless policy instances can be re-used without consequence. For [stateful policies](https://github.com/App-vNext/Polly/wiki/Statefulness-of-policies) circuit-breaker and bulkhead, on the other hand, it is functionally significant whether you re-use the same instance or different instances, across call sites. So a common requirement might be to have retry -> circuit-breaker -> timeout, using a common retry policy across all endpoints, variant circuit-breaker instances with a breaker per downstream system called, and a common timeout policy.  A long-running chaining syntax doesn't lend itself to achieving that degree of control.

**Comment by reisenberger** [comment]
One more thought:

    Policy
        .Handle<FooException>(() -> log.Error("Foo"))
        .Handle<BarException>(() -> log.Error("Bar"))
        .Execute(() -> DoSomething())

possibly suggests combining policies via an exclusive-or switch-case-ry: "if a then DoA else if b then DoB" (etc) (as opposed to the [functional-composition, nested-function nature of PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#operation)).

For the logging example given this looks logical and simple, and it could also work for `Fallback`.  But my view is that it could only make sense (remain simple) to combine multiple predicates-and-consequences _within a single policy instance_, for these simpler kinds of action. For anything beyond (retry or circuit-breaker), reasoning about the meaning and usage (especially in combination with the pre-existing PolicyWrap) becomes complicated. Because of this limited applicability, I doubt we will invest time taking Polly in that direction.

For specific cases, building one's own extension methods to achieve a particular syntax is always an option.

If @confusedIamHowBoutU there is anything else we can help with, let us know. If logging is a particular interest, see also [Polly.Contrib.LoggingPolicy](https://github.com/Polly-Contrib/Polly.Contrib.LoggingPolicy).

Hope this helps!

**Comment by confusedIamHowBoutU** [comment]
@reisenberger thanks for insight that super help full.

What is guidance around following pattern?
```
Policy
    .Handle<FooException>()
    .Handle<BarException>()
    .onRertry(3, (exp, i) -> {
         if (exp is FooException){
               log.error("foo")
         }
         else if (exp is BarException){
               log.error("Bar")
         }
    })
    .Execute(() -> DoSomething())
```

**Comment by reisenberger** [comment]
Thanks @confusedIamHowBoutU .  From:

```
Policy
    .Handle<FooException>()
    .Handle<BarException>()
    .onRertry(3, (exp, i) -> {
         if (exp is FooException){
               log.error("foo")
         }
         else if (exp is BarException){
               log.error("Bar")
         }
    })
    .Execute(() -> DoSomething())
```

it is clearer that the question is about logging on retry.

---

[Step 1 of the Polly Readme](https://github.com/App-vNext/Polly#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle) demonstrates `.Or<BarException>()`, see the example labelled `// Multiple exception types`

The [retry section of the readme](https://github.com/App-vNext/Polly/blob/master/README.md#retry) shows syntax for correctly configuring `onRetry:`; see the third example.

[Step 3 of the readme](https://github.com/App-vNext/Polly/blob/master/README.md#step-3--execute-the-policy) shows syntax examples putting it all together; the second example there executes through a policy which has just been configured to log in the `onRetry`.

**Comment by reisenberger** [comment]
And here's a quick working example: https://dotnetfiddle.net/Sipste

[Polly-Samples](https://github.com/App-vNext/Polly-Samples) also contains many more developed examples.
