### ISSUE TITLE
Contrib projects are lacking CI

### ISSUE THREAD

**Issue by aprooks** [App-vNext/Polly#608]
Contrib projects are not by an automated build system.

While I don't think there will be a huge amount of activities I'd feel much safer if any PR would be automatically signed off by a CI server.

**Comment by reisenberger** [comment]
Thanks @aprooks , it is intended, we just haven't got to it yet 🙂 . Added issues on the couple repos where it wasn't explicitly flagged, so that people can see it's intended.

https://github.com/Polly-Contrib/Polly.Contrib.CustomPolicyTemplates/issues/9
https://github.com/Polly-Contrib/Polly.Contrib.BlankTemplate/issues/5
https://github.com/Polly-Contrib/Polly.Contrib.LoggingPolicy/issues/2
https://github.com/Polly-Contrib/Polly.Contrib.TimingPolicy/issues/4
