### ISSUE TITLE
Callbacks specific to Execution

### ISSUE THREAD

**Issue by pvmraghunandan** [App-vNext/Polly#610]
While creating policy, we have an option to handle callbacks for example OnBreak. The issue is we want to log but the instance of logger should different for each call and same is case when we use ASP.Net Core Logger so that Activity Id can be retained for E2E Tracing. The current design of Polly policy creation doesn't support as Retry Callbacks should be created while instantiating object. This makes us impossible to use Policy callbacks.

For Example :

```
Policy.Handle<Exception>(RestRetryPolicyHelper.IsTransient)
                .OrResult<object>(RestRetryPolicyHelper.IsTransient)
                .WaitAndRetryAsync(
                    options.RetryCount,
                    retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
                    (exception, timeSpan, retryCount, context) =>
                    {
                        var msg = $"Retrying request for {retryCount} " +
                                  $"at {context.OperationKey}, " +
                                  $"due to: {exception}.";
                        logger.LogWarning(msg);
                        logger.LogDebug(msg);
                    });
```

Couldn't use context as the object of logger is not singleton and transient type which differs across each calls.

**Comment by reisenberger** [comment]
Hi @pvmraghunandan . I'm understanding that you want to be able to specify a different instance of `logger` per execution, using the above policy.  

There are two ways you could achieve this with current Polly:

#### (1) Define the policy immediately before use

You could simply define the policy immediately before use, when the correct instance of `logger` is in scope.  There are disadvantages: It would incur the (small) execution cost of defining the policy each execution. And obviously not in keeping with DI (eg policies defined at startup; perhaps placed in a PolicyRegistry; policies or registry then injected into usage sites by DI).

#### (2) (recommended) Use execution-scoped `Context` to pass in the `logger`

You can pass any transient custom data into an execution using Polly's execution-scoped `Context`; and the `onRetry` delegate can have been configured to retrieve that information from `Context`.  

I have just updated the wiki to give an example with `ILogger`: https://github.com/App-vNext/Polly/wiki/Keys-and-Context-Data#example-varying-the-ilogger-used-within-an-onretry-delegate

Does this meet your need?

The example code there passes an `ILogger` into an execution, but any other object can also be passed: `Context` has full dictionary-like semantics.

---

_To answer a few related background questions:_

The fact that policy instances are immutable after creation is intentional. Policy instances being mutable would create many other problems around multi-threaded use and policy use in multiple locations in an app.

The fact that `onRetry` delegate hooks are scoped to the policy at policy-configuration time, not attachable closer to execution time, goes back to the early origins of Polly (pre-dating even my involvement). I can see advantages and disadvantages both ways - and future versions of Polly could change this or provide other options - but it is not a small change.

---

Let us know if the code example solves your issue!

**Comment by pvmraghunandan** [comment]
@reisenberger Thanks for input. I liked option 2. Will give it a try and update.

**Comment by pvmraghunandan** [comment]
@reisenberger  This worked!! Thanks for putting up documentation very quick. It's very helpful. Closing the issue.
