### ISSUE TITLE
Policies should (do) fulfil interfaces, to help with unit-testing

### ISSUE THREAD

**Issue by rvgolovin** [App-vNext/Polly#631]
Returning an interface instead of concrete class helps with testability.

**Comment by reisenberger** [comment]
@rvgolovin Is your goal to use a tool such as Moq or NSubstitute to make a mock/stub of the policy, so that in a unit test, you can manipulate that mock/stub to return a specific result?  If so, Polly already supports this.

`.WaitAndRetryAsync(...)` [returns a concrete class `AsyncRetryPolicy`](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Retry/AsyncRetrySyntax.cs#L327), but that class already fulfils two kinds of interface, by the interface segregation principle:

+ `AsyncRetryPolicy : IRetryPolicy`: In fact, this is [just an empty marker interface](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Retry/IRetryPolicy.cs), so this is not the interface to use if you want to provide stub return values from executions. (These [policy-type interfaces](https://github.com/App-vNext/Polly/wiki/Polly-and-interfaces#the-policy-type-interfaces) become more interesting for other types of policy like [circuit-breaker](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/CircuitBreaker/ICircuitBreakerPolicy.cs).)
+ `AsyncRetryPolicy : IAsyncPolicy`: This `IAsyncPolicy` [contains all the execute overloads](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/IAsyncPolicy.cs). So this is the interface to use for mocking/stubbing.

If you are using the policies generic in `TResult`, then there is a similar interface [`IAsyncPolicy<TResult>`](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/IAsyncPolicy.TResult.cs).

Let me know if that helps.

More:

+ [Polly wiki: interfaces](https://github.com/App-vNext/Polly/wiki/Polly-and-interfaces)
+ [Polly wiki: unit-testing](https://github.com/App-vNext/Polly/wiki/Unit-testing-with-Polly#4-i-want-to-unit-test-how-my-code-reacts-to-results-or-faults-returned-by-the-execution-through-polly)

**Comment by reisenberger** [comment]
Assuming from no response that this covered the question, so closing.  If you have further questions, please post (or open a new issue).
