### ISSUE TITLE
Cannot make cache providers v3.0.1 compile

### ISSUE THREAD

**Issue by JimSmith99** [App-vNext/Polly#639]
Hi guys
New to polly.
I found this example https://nodogmablog.bryanhogan.net/tag/polly/
which uses Polly.Caching.Memory 2.0.2. This project compiles.

I try to recreate this with polly (EDIT: presumably Polly.Caching.Memory?) 3.0.1.
This now gives error in Configure():
`CachePolicy<int> cachePolicy = Policy.CacheAsync<int>(cacheProvider, TimeSpan.FromSeconds(10));`
Error: Cannot implicitly convert type 'Polly.Caching.AsyncCachePolicy<int>' to 'Polly.Caching.CachePolicy<int>'	

I tried this:
`AsyncCachePolicy<int> cachePolicy = Policy.CacheAsync<int>(cacheProvider,TimeSpan.FromSeconds(10));`

Then  `_cachePolicy.ExecuteAsync()` cannot be recognized.

Is there any documentation that I haven't found yet?

Br,

**Comment by reisenberger** [comment]
Hi @JimSmith99 

Which version of Polly are you using? Polly cache providers v3.0+ are for use with Polly v7.0+.  With Polly v < 7, remain with cache providers v2.x

(This information was in the doco but I've made it more prominent now [here](https://github.com/App-vNext/Polly/wiki/Cache#working-with-cacheproviders and [here](https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes#how-to-upgrade-to-v7-1) also.)

Does that resolve the issue?

If not, could you provide a simple ZIP or paste the exact code of the combination that isn't compiling? Thanks.

//cc @bryanjhogan

**Comment by JimSmith99** [comment]
Hi reisenberger.
I have uploaded a zip file with a small sample project based on the code from the blog I mentioned in my first post.
[polly.zip](https://github.com/App-vNext/Polly/files/3145919/polly.zip)

**Comment by reisenberger** [comment]
Hi @JimSmith99 . Here is a zip file with this fixed to compile.  

[polly-blogExample20190411fix.zip](https://github.com/App-vNext/Polly/files/3149937/polly-blogExample20190411fix.zip)

The changes were:

+ to add a Nuget reference to [`Microsoft.Extensions.Http.Polly`](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly)
+ to change the type of the Cache policy to AsyncCachePolicy in two places:
  - `StartUp` line 49, where the policy is declared: `AsyncCachePolicy<int> cachePolicy = Policy.CacheAsync<int>(cacheProvider, TimeSpan.FromSeconds(10));`
  - `TestController` line 30, where the policy is retrieved by type from PolicyRegistry: `var cachePolicy = _policyRegistry.Get<AsyncCachePolicy<int>>("CachingPolicy");`. 

---

The changes to the concrete types returned when configuring async Polly policies (ie the need to use `AsyncCachePolicy<int>` instead of `CachePolicy<int>` here) was a [breaking change between Polly v6 and v7](https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes#clarify-the-separation-of-synchronous-and-asynchronous-policies).

I see that the solution only directly referenced `Polly.Caching.Memory` _directly_, meaning that the nuget reference to the new Polly v7 was indirect, as shown below. 

![image](https://user-images.githubusercontent.com/9608723/57256809-8f467f00-704f-11e9-9f6b-70b3f7a97de4.png)

Let me know if this unblocks you with this blog post.

Thanks.

**Comment by JimSmith99** [comment]
Hi
It is compiling now. Now I can dive in and learn more about polly.
Your help is appreciated. 
Thanks, Jim
