### ISSUE TITLE
HttpClient.FooAsync() disposes HttpContent in .NET 4.6.1, causing ObjectDisposedException for retries wrapped around httpClient.FooAsync()

### ISSUE THREAD

**Issue by mgo-scavetta** [App-vNext/Polly#651]
Hi Guys!

Winform app using .NET 4.6.1

var response = policy.Execute( () => _httpClient.PutAsync(url, byteContent).Result);

It seems that HttpClient is disposing the HttpContext after the call.  I found online that this is known behavior and the recommended solution is to clone the context and restore between retries.

How can I accomplish this when the actual retries are done in the Polly code?  These retries are triggered for a leaky bucket drip rate error and the policies are working correctly; its just that the 1st retry fails with a disposed object exception for the HttpContent.  

Regards,
Rock

**Comment by reisenberger** [comment]
There are Stack Overflow answers that cover how to clone `HttpContent` and issues more broadly related to retry requests though `HttpClient`, so I'll reference rather than re-write that:

+ https://stackoverflow.com/questions/25044166/how-to-clone-a-httprequestmessage-when-the-original-request-has-content
+ https://stackoverflow.com/questions/19260060/retrying-httpclient-unsuccessful-requests/
+ https://stackoverflow.com/questions/18000583/re-send-httprequestmessage-exception

---

Re:

>How can I [clone the `HttpContent`] when the actual retries are done in the Polly code? 

You can execute more than one statement through `policy.Execute/Async(...)`. In pseudo-code:

    policy.Execute/Async(() =>
    {
        duplicate the HttpContent from some original, or create a new HttpContent instance wrapping some original source;
        PostAsync with the duplicated HttpContent;
    });

---

Consider also the approach of using the retry policy inside a `DelegatingHandler` within the `HttpClient`, rather than around the call to `httpClient.PutAsync(...)`.  This is the approach HttpClientFactory in DotNetCore takes.  References:

+ https://stackoverflow.com/a/19650002/  (shows a hand-built retry rather than Polly)
+ [source code of the kind of DelegatingHandler used by HttpClientFactory](https://github.com/aspnet/Extensions/blob/5061e03597c3b7cbc3e210adbc08e24fed893fd6/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs).  For your purposes, you could probably cut this down a lot to [a single constructor taking and storing a policy](https://github.com/aspnet/Extensions/blob/5061e03597c3b7cbc3e210adbc08e24fed893fd6/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L83-L90), and a [single-line override of `SendAsync(...)` just calling base.SendAsync(...) through the policy](https://github.com/aspnet/Extensions/blob/5061e03597c3b7cbc3e210adbc08e24fed893fd6/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L130)

My reading of the .NET 4.6.1 `HttpClient` source code is that moving the retry inside the `DelegatingHandler` should avoid the `HttpContent`-disposed problem.  However, you might still have issues with this approach if the `HttpContent` is originally a forward-only stream. In that case, you'd need to reset the stream pointer between retries or go back to the approach of cloning the `HttpContent`.

---

For any subsequent readers on .NET Core: the [dot net core implementation of HttpClient no longer disposes the HttpContent unilaterally](https://github.com/dotnet/corefx/pull/19082/files), so this is not an issue on .NET Core.

**Comment by mgo-scavetta** [comment]
Thanks Dylan,

I will try these suggested options today.  Thanks again for your reply.

I am closing this question as it is not a Polly issue.

Regards,
Rock
