### ISSUE TITLE
Possible to get last execution time when retrying?

### ISSUE THREAD

**Issue by jvitkauskas** [App-vNext/Polly#654]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

I am using Polly for retrying requests to 3rd party server. Request processing time seems to vary considerably. Therefore I would like to have retry policy which takes into account elapsed execution time. i.e. I want to retry sending request each X seconds no matter how much time it takes to get the response back.

<br/>

**Describe your proposed or preferred solution**:

Elapsed last execution time could be provided to sleepDurationProvider so I could subtract it from my retry time.

<br/>

**Any additional info?**

Not really sure if this https://github.com/App-vNext/Polly/issues/473 could be considered duplicate, because my intention is not to cause any mutations.

**Comment by reisenberger** [comment]
Hi @jvitkauskas .  This can be achieved with existing Polly by [using `Polly.Context` to pass data (in this case execution duration) between the delegate executed through the policy and the `sleepDurationProvider` delegate](https://github.com/App-vNext/Polly/wiki/Keys-And-Context-Data#using-context-for-custom-data).  

Execute through the policy using an [`.Execute/Async(...)` overload taking a `Context` input parameter](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/AsyncPolicy.TResult.ExecuteOverloads.cs#L40), and store the execution duration in `context`:

    var context = new Context();
    var result = policy.ExecuteAsync(() => {
            var stopwatch = System.Diagnostics.Stopwatch.StartNew();
            var r = await action(); // the code originally intended to be executed through the policy
            context["executionDuration"] = stopwatch.Elapsed;
            return r;
        }, context);

If you don't like the extra boilerplate, you can wrap it in an extension method.  Or just use the [TimingPolicy we provide on Polly.Contrib](https://github.com/Polly-Contrib/Polly.Contrib.TimingPolicy) configured something like: `timingPublisher: (span, context) => { context["executionDuration"] = span; return Task.CompletedTask; }` - you'd use that TimingPolicy inside the retry policy in a PolicyWrap.  

Meanwhile, your retry policy would be configured using [an overload where `sleepDurationProvider` takes `Context` as an input parameter](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Retry/AsyncRetrySyntax.cs#L596) (just an example overload, there are similar for all variants of retry).  In the `sleepDurationProvider` just extract the execution time from `context["executionDuration"]` and make whatever calculation you want based on it.

Please let me know if that helps.  (This is a sketch to get you a quick reply rather than leave you waiting, you might need to vary some details if I overlooked anything.)

Thanks

**Comment by reisenberger** [comment]
Closing due to lack of response.  If you require any further assistance, please post, and we can gladly re-open.
