### ISSUE TITLE
Finalize (OnSuccess Action) the WaitAndRetryAsync with a WrapAsync Policy 

### ISSUE THREAD

**Issue by BartHuls** [App-vNext/Polly#663]
I have a FallbackAsync Policy combined with a WaitAndRetryAsync Policy.
Both Policies are wrapped together with WrapAsync.
FallbackPolicy.WrapAsync(RetryPolicy). This works.

Is have a need to add some Finalizer eq. When the WaitAndRetryAsync succeeds like the fallbackAction but in the WaitAndRetryAsync

**Comment by BartHuls** [comment]
I used now a command Action delegate which is called  on "onFallbackAsync" 

```
 return Policy
                .Handle<Exception>()
                .FallbackAsync(
                    fallbackAction: async ct => { await Task.FromResult(true); },
                    onFallbackAsync: async e =>
                    {
                        await Task.FromResult(true);
                        fallbackAction(sender, self, e);
                    });
```

**Comment by reisenberger** [comment]
Hi @BartHuls . There is no in-built syntax in Polly to express "on success".  Some possible approaches:

**1. Execute with [`ExecuteAndCaptureAsync()`](https://github.com/App-vNext/Polly#post-execution-capturing-the-result-or-any-final-exception)** and check the `policyResult.Outcome` property to see whether the overall outcome was success or failure - and add logic based on that.

This doesn't provide a solution all encapsulated within one `PolicyWrap`, but you could wrap executing in this style with an extension method.

**2. Use a `FallbackPolicy` capturing the success case**.  A `FallbackPolicy` is just a policy that executes some extra code (and can change the returned result) when a condition is true. And that condition can be anything. So you can add in your PolicyWrap an extra FallbackPolicy that handles the "success" condition instead of the "failure" condition.  In pseudo-code:

    var fallbackForFailure = Policy./*Handle and/or HandleResult clauses capturing failures*/.FallbackAsync(/* extra actions for failure case*/);
    var fallbackForSuccess = Policy./*Handle and/or HandleResult clauses capturing successes*/.FallbackAsync(/* extra actions for success case*/);
    var retry = Policy./*Handle and/or HandleResult clauses capturing failures*/.WaitAndRetryAsync(...);
    var combinedPolicy = Policy.WrapAsync(fallbackForFailure, fallbackForSuccess, retry);

(_pseudo-code because I don't have all the info we ask for in our_ [issue templates](https://github.com/App-vNext/Polly/issues/new/choose))

This gives you a solution all in one `PolicyWrap`. You can [use the same type of policy more than once in a PolicyWrap](https://github.com/App-vNext/Polly/wiki/PolicyWrap#using-the-same-type-of-policy-more-than-once-in-a-wrap), as this does with FallbackPolicy.

**Comment by reisenberger** [comment]
Quick comment on async. You could also eliminate some extra async state machines (makes things slightly more performant), if it happens that your delegates only need to be synchronous and don't do anything async. eg:

```
 return Policy
                .Handle<Exception>()
                .FallbackAsync(
                    fallbackAction: ct => Task.FromResult(true), // or Task.CompletedTask if you are using the language version supporting it
                    onFallbackAsync: e =>
                    {
                        fallbackAction(sender, self, e);
                        return Task.FromResult(true);  // or Task.CompletedTask if you are using the language version supporting it
                    });
```
