### ISSUE TITLE
Is polly bringing System.Net.Http 4.2.0.0?

### ISSUE THREAD

**Issue by afcruzs** [App-vNext/Polly#668]
**Summary**: 
I'm writing a library that depends on Polly and I discovered that the moment I add polly as a package reference it suddenly brings System.Net.Http 4.2.0.0. This is a very painful well known issue on .net (see [this](https://github.com/dotnet/corefx/issues/25773)) and I wouldn't like the consumers of our library to go through it, it forces them to write obscure assembly redirects and if they don't they *may* (this is the annoying part) have runtime issues depending on the GAC of the system.
<br/>
<br/>

**Expected behavior**: 

Polly shouldn't bring any System.Net.Http dependencies since is not listed on the dependencies of their nuget package: https://www.nuget.org/packages/Polly/

<br/>
<br/>

**Actual behaviour**:

This is the output of ildasm of a testing library after adding polly as a dependency and using httpclient:

```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:2:0:0
}
```

<br/>
<br/>

**Steps / Code to reproduce the problem**: 

A very simple library project should reproduces this:

TestingPolly.csproj
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TestingPolly</RootNamespace>
    <AssemblyName>TestingPolly</AssemblyName>
    <TargetFramework>net461</TargetFramework>
    <Platforms>x64</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <!-- Try removing Polly -->
    <PackageReference Include="Polly" Version="7.1.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.3" />
  </ItemGroup>
</Project>

```
Class1.cs
```
using System.Net.Http;

namespace TestingPolly
{
    public class Class1
    {
        private HttpClient foo;
    }
}
```
After building the project, running this command on the output directory of the project (on the VS developer command prompt) with the polly package `ildasm TestingPolly.dll /OUT=testingpolly.txt && notepad testingpolly.txt` will output this:

```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:2:0:0
}
```

If polly is removed, ildasm will output this (expected since we depend on System.Net.Http):
```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:1:1:2
}
```

**Comment by reisenberger** [comment]
Polly [contains no reference to System.Net.Http](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Polly.csproj). [Searching the Polly repo for http](https://github.com/App-vNext/Polly/search?q=http&unscoped_q=http) confirms there is no reference to `System.Net.Http`.

Polly [supports .Net Framework via .NET Standard targets](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Polly.csproj#L4).  My assumption is that the bridge from .NET Standard to .NET Framework for .NET4.6.1 is bringing in `System.Net.Http` indirectly - _and/or_ that the MsBuild tooling is messing up the versions (as the issue you linked suggests). This is not something Polly can control; it is on the Microsoft side.

Are either of (1) and (2) below options for you?

(1) Add an explicit reference to `System.Net.Http`, the version you want to use, to your top-level project. (From the **Steps / Code to reproduce** which you quoted and the issue you linked, I suspect this may not be a complete solution, but it may be worth trying.)

(2) Upgrade to / support only .NET 4.7.2. This is a Microsoft recommendation (see [footnote 2 here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)) for those on .NET4.6.1-4.7.1.  Because of the widely documented issues with .NET Framework 4.6.1-4.7.1 projects consuming .NET Std packages.

---

If those are not an option, a third option could be to explore whether this (3) would help:

(3) [Add explicit .NET Framework targets](https://github.com/App-vNext/Polly/issues/545) to Polly

If you wish to explore (3), please could you trial and report back whether this resolves your case or not. You can pull the Polly codebase from github to your local machine, add explicit framework targets as you require [here](https://github.com/App-vNext/Polly/blob/eff944e005ba3e39c22f4f00e60b07baf57165ec/src/Polly/Polly.csproj#L4), run the build, and trial the nuget package which is generated in the `artifacts\nuget-package` folder. Start from the head of [this branch](https://github.com/App-vNext/Polly/commits/v711-or-v720), not `master`.

Based on reading https://github.com/dotnet/corefx/issues/25773, I cannot confidently say that (3) would solve the issue for you (the problem may still be caused by the interaction of MS Build/GAC and depend on the end-user's version of Visual Studio/MS Build). 

**_If_** (3) resolves your issue, it could be another reason for us to add .NET Framework targets to Polly.  We have been reluctant to do this, because it will force us to add a .NET Framework 4.7.2 target also (so that nuget does not downgrade those users to .NET4.6.1 dependencies); and that would change the .NET 4.7.2 experience to consuming framework instead of .NET Standard 2.0. That is a (theoretically) unnecessary change for .NET 4.7.2 users, but the nuget tooling would force us to do it.

I haven't been working in .NET Framework for some months now, so all community feedback is welcome.

**Comment by afcruzs** [comment]
I tried variations of 1) but didn't work. I think the best approach we should take is 2) as is recommended by MS and .net is moving forward.

Having said that, I'll give it a shot to 3) and will let you know my findings.

**Comment by afcruzs** [comment]
All right, so I've tried adding the 461 target (branch [here](https://github.com/afcruzs/Polly/commit/186e2f589459bd72fffc29c6bfa48d88e037fca7)). Indeed the manifest looks more what I'm expecting on the minimal repro library after using the nuget built locally:

```
.assembly extern System.Net.Http
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:1:1:2
}
```

**Comment by reisenberger** [comment]
Thanks!  Good to know.  Ok, I will consult with the other Polly team key stakeholder whether we are good to add .NET Framework targets back in, seems like it would help here.

**Comment by hyrmn** [comment]
@afcruzs We experienced the same. We "resolved" it in the short-term by adding an explicit binding redirect to downgrade system.net.http to 4.0.0.0

```
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
```

This may not work for your use case but, if so, it might be a way forward in the short-term. This issue affects us on 461 and 472.

**Comment by reisenberger** [comment]
Polly v7.2.0 [has been published](https://www.nuget.org/packages/polly) with .NET Framework targets 4.6.1 and 4.7.2 now supported natively as part of the nuget package.  Should resolve this issue.
