### ISSUE TITLE
RetryUntilTimeout

### ISSUE THREAD

**Issue by hichemaichour** [App-vNext/Polly#672]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**
It is a feature to make it possible to define the retry based on Time rather than count.

**Describe your proposed or preferred solution**:
Just how it is done with retries, once the Timeout is reached, the last result is returned (default if none). Note, since it is retrying, we don't want to throw an exception like the case of TimeoutPolicy.

**Describe any alternative options you've considered**:
Currently, I am just wrapping TimeoutPolicy with RetryForever but that doesn't capture the last result

**Comment by reisenberger** [comment]
Polly TimeoutPolicy does not target this use case.

The simplest way to achieve this is to define your own timing-out CancellationToken and then use an existing form of retry policy with a handle clause along these lines:

    Policy
        .Handle<FooException>(e => !token.IsCancellationRequested)

Because CancellationTokens are single-use only, with an existing retry policy, you would need to define a new such policy instance per execution.

You could make a single policy instance which could be re-used, by defining your own custom policy for the behaviour: http://www.thepollyproject.org/2019/02/13/authoring-a-reactive-polly-policy-custom-policies-part-iii-2/

If you define a custom policy for this, we would love to include it in Polly-Contrib!: http://www.thepollyproject.org/2019/02/13/introducing-custom-polly-policies-and-polly-contrib-custom-policies-part-i/

**Comment by hichemaichour** [comment]
Thanks, will look into doing that 😄

**Comment by setood** [comment]
find simple workaround for this use case:
```csharp
// timeoutPolicy thrown own exception, that overlap retry exceptions,
// so this list used for catch the retry exceptions.
List<Exception> retryExceptions = new List<Exception>();
var timeoutPolicy = Policy.TimeoutAsync(seconds: 2);
var retryPolicy = Policy
    .Handle<Exception>()
    .WaitAndRetryAsync(new[] {TimeSpan.FromSeconds(3)},
        onRetry: (exception, _) => retryExceptions.Add(exception));
var policy =
    Policy.WrapAsync(timeoutPolicy,retryPolicy);
try
{
    await policy.ExecuteAsync(
        action: async () =>
        {
            throw new NotImplementedException();
        });

}
catch (TimeoutRejectedException e)
{
    throw new AggregateException(
        retryExceptions
            .Append(e)
            .Reverse());
}
```
