### ISSUE TITLE
How to prevent exception bubbling in Policy.Wrap()

### ISSUE THREAD

**Issue by slyce130** [App-vNext/Polly#684]
```
Example code:

                    var noLogicPolicy = Policy
                        .Handle<ArgumentException>(deleteError => deleteError.Message.Contains("No such file or directory.")
                        .Retry(0);

                    var reconnectPolicy = Policy
                        .Handle<InvalidOperationException>()                        
                        .Retry(1,);

                    var retryPolicy = Policy
                        .Handle<Exception>()
                        .WaitAndRetry();
                            });

Policy.Wrap(retryPolicy, noLogicPolicy, reconnectPolicy).Execute(command);
```

In this context, say noLogicPolicy is triggered because the exception is of type ArgumentException with the message "No such file or directory". The retryPolicy is also triggering because it is handling all exceptions. I do not want the retryPolicy to execute in this case.

As per https://github.com/App-vNext/Polly/wiki/PolicyWrap, "exceptions bubble back outwards (until handled) through the layers", I'm assuming there should be something to prevent the backwards bubbling. Any suggestions? Hopefully, I do not have to manually filter out the other exceptions in the generic exception policy.

This is on Polly 7.1.1 targeting .net 4.6.1

**Comment by reisenberger** [comment]
@slyce130 , good question.

Components of a `PolicyWrap` have no knowledge of the content of the other policies; only pointers to them. There is no in-built mechanism within `PolicyWrap` for a more-outer policy to know that a further-in policy might have matched its `Handle` clause.  So in this case, yes, if you want the `Handle` clauses of different policies to be mutually exclusive, you have to code them that way explicitly.

This flows from the fact that a PolicyWrap expresses nested execution (functional composition) rather than side-by-side switch/case or if-elseif-elseif-else logic. 

---

It could have been possible to introduce special rules about adjacent retry policies (making them follow an if-elseif exclusivity), but that would have ended up mixing idioms - some cases of a PolicyWrap (or even parts of the same PolicyWrap) would have "nesting" meaning and others "parallel mutual exclusivity" meaning.  If we were to introduce parallel-mutual-exclusivity in Polly, we might (thinking aloud) express it in a different way - perhaps as a new kind/variant of retry policy.

**Comment by slyce130** [comment]
Thanks for getting back to me. Looks like I'll be coding it explicitly.

**Comment by reisenberger** [comment]
No problem. It highlights the fact that Polly doesn't have a syntax story for the mutual-exclusive use case

If you had a lot of them (to code), it would probably be possible to write an extension method that converted the conditions (stated-without-explicit-exclusivity) into explicitly mutually exclusive steps in a PolicyWrap.
