### ISSUE TITLE
[WCF-specific] Error Occurs When given timeout and it cannot again because the [WCF] state does not allow Again What do I do?

### ISSUE THREAD

**Issue by alvpaz** [App-vNext/Polly#77]
**Exception message**: 
System.TimeoutException : The opening operation was not completed within the allotted time limit of 00:05:00 . The time allocated for this operation may have been a part of a longer timeout . ---> System.TimeoutException : The socket transfer timed out after 00: 04: 59.9499950 . You have exceeded the time limit set in their association. The time allocated for this operation may have been a part of a longer timeout . ---> System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not answer properly after a period of time, or established connection failed

**retry two**
Exception message: System.ServiceModel.CommunicationObjectFaultedException: The communication object, System.ServiceModel.Channels.ServiceChannel **can not be used for communication because it is in Failed state**.

```
var tentativas = 0;
            var policy = Policy
                .Handle<Exception>()
                .Retry(3,
                    (exception, retryCount, context) =>
                    {
                        Log.LogarErro(string.Format("{0} {1} ", messagemErro, tentativas++), exception);
                    });
            return policy;
```

**Comment by joelhulen** [comment]
@alvpaz Based on your errors, it appears as though you are connecting to a WCF endpoint, which is timing out. On the other hand, it could be that it is throwing some other exception, then timing out when the policy retries the request. Perhaps if this is the case, then the ServiceChannel object isn't reusable and you need to reset it somehow between retries.

Do you still encounter this issue when you take Polly out of the picture?

If it only happens when using the retry policy, could you try modifying your policy to capture a more specific exception to perhaps determine the source problem?

Do your logs reflect the timeout error, or does it show something else?

Finally, could you create a very small sample project that reproduces this error?

**Comment by alvpaz** [comment]
I will create the project. But the problem is that I am connecting a WCF service and gave expired time error, and when he tries to run again he did not allow because the context already with error status, I will try to simulate an example and post here.
