### ISSUE TITLE
Unit test code that contains AsyncCircuitBreakerPolicy

### ISSUE THREAD

**Issue by lkurzyniec** [App-vNext/Polly#784]
**Summary: What are you wanting to achieve?**
Unit test code with circuit breaker policy

**What code or approach do you have so far?**  
Let be that I'm registering policy with this snippet
```cs
            var policy = Policy
                .Handle<HttpRequestException>()
                .CircuitBreakerAsync(
                    exceptionsAllowedBeforeBreaking: 2,
                    durationOfBreak: TimeSpan.FromMinutes(1)
                );
            services.AddTransient(_ => policy);
```
I can register it also with `services.AddTransient<ICircuitBreakerPolicy, AsyncCircuitBreakerPolicy>(_ => policy);`, but then I need to cast it to `AsyncCircuitBreakerPolicy`. It works for app, but doesn't for unit test (missing `ExecuteAsync()` in `ICircuitBreakerPolicy` ).

My code that I would like to cover by unit tests
```cs
            ctor(AsyncCircuitBreakerPolicy breaker, ...) { ... }

            var url = $"{_options.Value.ApiUrl}?some-query";

            HttpResponseMessage response = null;
            try
            {
                if (_breaker.CircuitState == CircuitState.Open)
                {
                    return null;
                }
                response = await _breaker.ExecuteAsync((token) => _client.GetAsync(url, token), cancellationToken);
            }
            catch (BrokenCircuitException) { }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to make request to '{Url}'", url);
            }
```

There is no way to mock both `ICircuitBreakerPolicy` (which has `CircuitState`) and `IAsyncPolicy` (which has `ExecuteAsync()`). Or I'm missing something.

The issue could be that there is no combined interface (ICircuitBreakerPolicy with state and IAsyncPolicy with execute action) that I can inject and later on mock in unit test.

**Comment by ben-burton** [comment]
I also tried injecting ICircuitBreakerPolicy so I can get to the CircuitState and I am casting it to IAsyncPolicy to call execute. This presents the same problem trying to unit test. I'm not sure if this is the right approach? Is there a single interface I can inject that will allow me to do both the execution and inspect the circuit state

**Comment by lkurzyniec** [comment]
@ben-burton could you write your solution here? I can't figure out how to properly register and inject custom `ICircuitBreaker`.

**Comment by martincostello** [comment]
Have you considered using a _real_ circuit breaker policy in your tests, rather than the interfaces, and then testing your code that way?

Mocking the policies won't test whether you've configured your policies correctly to get the behaviour you actually want at runtime, for example.

I've had this problem in the past where my assumptions about how Polly works were incorrect and then the mocks just reflected those incorrect assumptions, leading to bugs even though the tests passed.

**Comment by lkurzyniec** [comment]
@martincostello I don't want to unit test policy itself. I would like to test my business code properly that's relay on policy.

**Comment by martincostello** [comment]
I'm not suggesting you unit test the policy, I'm suggesting your test your code that _uses_ policies. You can do that without needing mocks for circuit breakers.

If you can mock the _action_ wrapped in the policy to throw an appropriate exception for your usage, then the circuit breaker will trip (assuming you've configured it correctly) and test your business logic handles it appropriately.

Otherwise you're coupling your tests too much to the implementation details of Polly. There's not much need to mock out Polly because it's not doing any I/O or other things where mocks are more useful (like calling an API or reading from a database).

I'm just suggesting you adapt your test approach to test your code in a different way, removing the need for you to "solve" this mocking problem.

If for some philosophical reason you don't want to do that, then that's fine and that's your choice. But it's not how I'd go about testing business logic that relied on Polly myself for reasons including the ones I mentioned above, which is why this is my suggestion.

**Comment by SimonCropp** [comment]
IMO this has been answered?
