### ISSUE TITLE
Policy Registry implementation for Xamarin Forms and TinyIoC

### ISSUE THREAD

**Issue by kkazmierczak-vertex** [App-vNext/Polly#855]
Hi!

I'm looking for a policy registry implementation example:

https://github.com/App-vNext/Polly/wiki/PolicyRegistry.

My stack is Xamarin Forms and TinyIoC - https://github.com/grumpydev/TinyIoC

Can anyone advise how this should be implemented?

Many thanks in advance!

**Comment by martincostello** [comment]
[`PolicyRegistry`](https://github.com/App-vNext/Polly/blob/master/src/Polly/Registry/PolicyRegistry.cs) is built into Polly. Does it not meet your needs in some way?

**Comment by kkazmierczak-vertex** [comment]
The problem is I don't know how to implement it. I believe I should implement IReadOnlyPolicyRegistry<string> interface but not sure how.

**Comment by martincostello** [comment]
Why do you need to implement it? The `PolicyRegistry` class implements it, so you could just use that.

Or do you mean how to implement _using_ it? In that case the documentation you've linked to should be sufficient. If it's not, what's confusing about it that we can improve?

**Comment by kkazmierczak-vertex** [comment]
Yes, I have problem using it. I'm not exactly sure how I can add policies to the registry and then "access" them in one of my services.

**Comment by kkazmierczak-vertex** [comment]
I add policy in my App.xaml.cs (startup class):

Polly.Registry.PolicyRegistry registry = new Polly.Registry.PolicyRegistry();
registry.Add("MyPolicy", _unauthorizedPolicy);

When I pass the registry instance to one my services I got:
FreshTinyIoC.TinyIoCResolutionException: 'Resolve failed: ChooseProductPageModel - Reason: Resolve failed: IReadOnlyPolicyRegistry`1'

Which makes sense. I stuck with part related to DI.

**Comment by martincostello** [comment]
Polly doesn't register any services with a DI container - otherwise it would need a dependency on one or more DI containers itself.

Without knowing what DI container you use, I can't give you a concrete example of how to register it with your DI container (or the best way to do so for you use case).

By way of an example, here's how ASP.NET Core configures the policy registry in the Polly extensions in .NET 6: https://github.com/dotnet/aspnetcore/blob/436d3b413dc09b0698ea017a524c98d282efee37/src/HttpClientFactory/Polly/src/DependencyInjection/PollyServiceCollectionExtensions.cs#L30-L36

**Comment by kkazmierczak-vertex** [comment]
I use https://github.com/grumpydev/TinyIoC

**Comment by martincostello** [comment]
I've never used TinyIoC, so you're already more of an expert in it than me 😉 

This doesn't appear to be an issue specific to Polly. `PolicyFactory` is a concrete type, which implements three different interfaces (which you can see in the ASP.NET Core code I linked to above). You will need to register `PolicyFactory` (or some other implementation of the interfaces) with your TinyIoC DI container in whatever manner is appropriate to you.

For example, with `PolicyFactory` as the concrete class and `IPolicyRegistry<string>` as the abstraction. If you wanted to use something other than `string` as the key, then you'd need to implement your own policy registry and then register that with TinyIoC in whatever way you'd do that with that DI container.

**Comment by kkazmierczak-vertex** [comment]
Hi Martin! I hope you are doing well. And I also hope you don't mind me asking another questions. I'm trying to implement Polly.Registry.IPolicyRegistry<string> interface and I tried to simply return simple policy for Get function. And I got:

Cannot implicitly convert type 'Polly.Retry.RetryPolicy' to 'TPolicy'

Do you know where I can find simple IPolicyRegistry<string> implementation? I'm confused by the fact all examples are for asp .net core. I'd like to see example for simple console app. Sorry for bothering you and thank you in advance.

**Comment by martincostello** [comment]
Look at [`PolicyFactory`](https://github.com/App-vNext/Polly/blob/174cc53e17bf02da5e1f2c0d74dffb4f23aa99c0/src/Polly/Registry/PolicyRegistry.cs#L13) - it's just a wrapper on top of a dictionary that uses `string` as the key and [`IsPolicy`](https://github.com/App-vNext/Polly/blob/174cc53e17bf02da5e1f2c0d74dffb4f23aa99c0/src/Polly/IsPolicy.cs#L8) as the value, I don't think it could be much simpler. But again - why not just use `PolicyRegistry`? You don't seem to have articulated any reason why you need to actually implement your own version.

**Comment by kkazmierczak-vertex** [comment]
Thank you!. There is one thing I don't understand. TinyIoC returns an instance of my policy registry, but with no policies. Should I cache this policies dictionary somehow?

**Comment by kkazmierczak-vertex** [comment]
I'd love to use PolicyRegistry, but not sure how I could add policies there and reuse them in my services later.

**Comment by martincostello** [comment]
The wiki link you provided already at the top of the issue shows how to:

1. Create a registry (they start empty, it's up to you to fill it with policies)
2. How to add items to a registry
3. How to inject the registry into a service
4. How to get policies back out of the registry

If this existing documentation still doesn't help you, then we can update it to be more informative, but you need to tell us _exactly_ what it is about it that you don't understand or find confusing.

Otherwise we just seem to be going around in circles with me pointing you at documentation, and you saying you don't understand it without articulating _specifically_ why. It appears to me that it provides examples for exactly what you're trying to do (other than the IoC registration part, which is outside the scope of Polly).

Without more specific and actionable details about the shortfalls in the Polly documentation there may be that's leading to your misunderstanding or confusion, there's not much more I can do to help you out.

**Comment by kkazmierczak-vertex** [comment]
The biggest problem for me was to understand how I can get registry instance filled with policies. In Xamarin Forms there is an App class, where I defined my registry:

public static Polly.Registry.PolicyRegistry registry;

in App constructor I add my policies and then I can use them in my services:

IAsyncPolicy p = App.registry.Get<IAsyncPolicy>("MyPolicy");

It works and I hope it is a proper approach. Thank you very much for your time once again!

**Comment by martincostello** [comment]
Yep, that's pretty much exactly how you're intended to use it.

**Comment by kkazmierczak-vertex** [comment]
Thank you!
