### ISSUE TITLE
How to get OutcomeType when using a policy with typed HttpClient?

### ISSUE THREAD

**Issue by IanKemp** [App-vNext/Polly#874]
**Summary: What are you wanting to achieve?**
I want to convert the following code:

```csharp
// CallingService
public async Task SomeMethod()
{
    var policy = Policy
                     .Handle<Exception>()
                     .WaitAndRetryAsync(_pollyRetryValue,
                     (i) => TimeSpan.FromSeconds(_pollyWaitValueInSeconds * i));

    var result = await _pollyRetryPolicy.ExecuteAndCaptureAsync(async () => await _anotherService.MakeAnHttpRequestAsync());

    // problem comes in here
    if (lookupResult.Outcome == OutcomeType.Success)
    {
        DoSomething();
    }
    else
    {                                    
        LogError();
    }
}

// AnotherService
public async Task MakeAnHttpRequestAsync()
{
    var response = await _httpClient.GetAsync(someUrl);
}
```

to use IHttpClientFactory with a typed HttpClient, and wrap the whole thing with a Polly policy in Startup.cs ConfigureServices. Essentially my `AnotherService` will have an HttpClient instance injected, make an HTTP request, and do something with the result.

**Problem:** I've read through the entirety of https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory and as far as I can see, there's no way to get the `OutcomeType` when using the IHttpClientFactory approach. The Polly.Context() object shown in "Use Case: Exchanging information between policy execution and calling code" is basically just a Dictionary that carries random metadata through the request pipeline, with no indication that Polly executed the request successfully or not. It also seems like this context has to be set on a raw HttpRequestMessage and isn't auto-created when calling the "intrinsic" HttpClient operations that create an HttpRequestMessage internally, e.g. GetAsync.

How can I achieve the desired behaviour?

**What code or approach do you have so far?**  

Nothing, since I don't know what to write as per above.

**Comment by martincostello** [comment]
To do this you'd need to implement your own variant of `DelegatingHandler` like [the ASP.NET Core one](https://github.com/dotnet/aspnetcore/blob/ac3a403cb3e496841e76d367d41519f8273cebe8/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L108-L141) except you'd use `ExecuteAndCaptureAsync()` instead of `ExecuteAsync()`, and then do whatever it is you wanted to do with the outcome.

You'd then plug that into HttpClientFactory using the `AddHttpMessageHandler()` overload like ASP.NET Core does in the `AddPolicyHandler()` methods ([code](https://github.com/dotnet/aspnetcore/blob/main/src/HttpClientFactory/Polly/src/DependencyInjection/PollyHttpClientBuilderExtensions.cs)).

**Comment by IanKemp** [comment]
@martincostello Thanks for that.

To verify for my own understanding, since all the HttpClient convenience methods like GetAsync are internally creating HttpRequestMessages, then any sort of DelegatingHandler I apply will automatically Just Work? If so, I guess I could make a very minor alteration to [PolicyHttpMessageHandler.cs](https://github.com/dotnet/aspnetcore/blob/main/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L130) to the following:

```csharp
var result = await policy.ExecuteAndCaptureAsync((c, ct) => SendCoreAsync(request, c, ct), context, cancellationToken).ConfigureAwait(false);
response = result.Result;
context[nameof(OutcomeType)] = result.Outcome;
```

I guess my next question would be, is this worthwhile to do? As far as I understand, the only difference between ExecuteAndCaptureAsync and ExecuteAsync is that the latter will bubble up the exception while the former will not, and thinking further (without actually looking at Polly source) I'd assume that ExecuteAndCaptureAsync is doing something like:

```
var result = new PolicyResult<HttpResponseMessage>();

try
{
    var response = await ExecuteAsync();

    result.Outcome = OutcomeType.Success;
    result.Result = response;
}
catch (Exception ex)
{
    result.Outcome = OutcomeType.Failure;
    result.FinalException = ex;
}

return result;
```

so I'd imagine that there's really no advantage (in terms of performance) in using ExecuteAndCaptureAsync? If so, why does it exist?

**Comment by martincostello** [comment]
Yeah that's right.

I don't really understand what the specific use cases are for `ExecuteAndCaptureAsync()` (maybe A/B testing/observations? the README doesn't seem to explain _why_ it exists, just that it's a thing you can use), but out of the two approaches I would have thought it's the slower one, which is why the standard usage is just `ExecuteAsync()`, which the HttpClientFactory extensions use.
