### ISSUE TITLE
Better support of AggregateException

### ISSUE THREAD

**Issue by fubar-coder** [App-vNext/Polly#89]
Whenever an `AggregateException` is caught, it must be rethrown after calling its `Flatten()` function. Otherwise we might have nested `AggregateException`s.

EDIT: The [MSDN documentation](https://msdn.microsoft.com/de-de/library/dd537614.aspx)

**Comment by reisenberger** [comment]
@fubar-coder Very many thanks for this and for your involvement with Polly!

Do you have any code example, where an `action` executed through Polly is generating nested `AggregateException`s? 

The Polly async implementation is `async`/`await` throughout, therefore, nested `AggregateException`s should not be generated specifically by using Polly.  (Ref, second half of: [Stephen Toub on Task Exception Handling](http://blogs.msdn.com/b/pfxteam/archive/2011/09/28/10217876.aspx)).  

I would only expect Polly to return nested `AggregateException`s if:

(i) the `action` delegate itself is generating the nested `AggregateException`s.

_or_

(ii) the `action` delegate only generates one (not-nested) `AggregateException`, but code is synchronously-waiting on the result of async policy execution, like `policy.ExecuteAsync(action).Wait()` (or similar).  

In (ii), the Polly codebase cannot help flatten the `AggregateException`: it has no control over the `AggregateException` returned by the outer `.Wait()`.

In (i), the question becomes whether Polly should (on behalf of the user) flatten nested `AggregateException`s created purely within the user's `action` delegate. 

My first instinct is that Polly should not intervene by modifying exception effects purely of the user's `action` delegate.  This keeps Polly's intervention minimal and transparent, without adding any 'side effects' (save the retries or whatever intended) to how the user's delegate is executed.  This is a slightly purist approach, but allows the user maximum control to make their own choice about exceptions, rather than imposing a choice from the library.

Users calling `.ExecuteAsync(...)` in a mode like `policy.ExecuteAsync(action).Wait()` can of course call `.Flatten()` themselves, which has the advantage of including the outer `AggregateException`.

**Comment by reisenberger** [comment]
@fubar-coder Based on the above reasoning, I am intending to recommend this as 'wont-fix'.  

However, if you have a particular code sample where this is causing problems, we would be very interested to see it, as this could (of course) shed further light on the problem.

Many thanks
