### ISSUE TITLE
Polly Timeout is not working as expected

### ISSUE THREAD

**Issue by asos-samsuganid** [App-vNext/Polly#907]
I have implimented Polly timeout for long running httpclient inorder to terminate the request if it's taking more than the threshold value. Request you to provide your advise please.

**Expected behavior**:

httpclient request call should be terminated if the request crossed more than 30ms 

**Actual behaviour**:

But it's not working, as we could see some of the calls are not terminated within 30 ms

**Steps / Code to reproduce the problem**: 

Best is a [complete example](https://stackoverflow.com/help/mcve) or failing unit test.  It is _always_ useful to see:

```csharp
 private readonly Policy _policy;
 public   constructor()
{
        _policy = Policy.TimeoutAsync(TimeSpan.FromMilliseconds(30));
}

actual implimentation

 return await _policy.ExecuteAsync(
                    async () => await _httpClientWrapper.GetAsync(httpRequest).ConfigureAwait(false)).ConfigureAwait(false)
```

**Comment by martincostello** [comment]
As explained [in the documentation](https://github.com/App-vNext/Polly#optimistic-timeout), using an optimistic timeout requires you to use a delegate overload which receives a `CancellationToken` parameter, which you would then pass to the `HttpClient` instance. This would then cause the request to be cancelled after 30 milliseconds (or sooner if the value of `HttpClient.Timeout` is less than 30 milliseconds):

```csharp
 return await _policy.ExecuteAsync(
    async (cancellationToken) =>
        await _httpClientWrapper.GetAsync(httpRequest, cancellationToken).ConfigureAwait(false))
    .ConfigureAwait(false);
```

Otherwise, you need to use a [pessimistic timeout](https://github.com/App-vNext/Polly#pessimistic-timeout), which will cause the code calling through the policy to observe an exception if it takes more than 30 milliseconds (at the expense of an additional task/thread to observe the HTTP request to time it does not take too long).

```csharp
public YourConstructor()
{
    _policy = Policy.TimeoutAsync(TimeSpan.FromMilliseconds(30), , TimeoutStrategy.Pessimistic);
}
```

Optimistic retries are the recommended approach with `HttpClient`, so you just need to pass through the `CancellationToken`, which would cause the request to timeout as you require.
