### ISSUE TITLE
Polly Timeout: How to utilize optimistic timeout on all HttpClient.GetAsync calls when using HttpClientFactory

### ISSUE THREAD

**Issue by fsgarin-lacity** [App-vNext/Polly#924]
**Summary: What are you wanting to achieve?**

This is somewhat related to #907, but within the context of `HttpClientFactory`. If a `CancellationToken` is required to be passed to the `HttpClient` instance for optimistic timeout, how would you go about doing that when nearly everything about the policy setup with `HttpClientFactory` is implicit? There is no `CancellationToken` object in sight to reference or pass around!

**What code or approach do you have so far?**  

I have two separate source files here: the main program where all the DI-framework magic with `HttpClientFactory` happens, and the `GitHubService` class that actually makes the HTTP calls.

In Program.cs:

```csharp
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();
var jitterDelay = Backoff.DecorrelatedJitterBackoffV2(TimeSpan.FromSeconds(1), 6);
var retryPolicy = Policy
    .Handle<RateLimitRejectedException>()
    .OrTransientHttpError()
    .WaitAndRetryAsync(jitterDelay);
var timeoutPolicy = Policy
    .TimeoutAsync<HttpResponseMessage>(10);
var host = new HostBuilder()
    .ConfigureServices(services =>
    {
        services.AddHttpClient<IGitHubService, GitHubService>((sp, client) =>
        {
            client.BaseAddress = new Uri("https://api.github.com");
            client.DefaultRequestHeaders.Add(
                HeaderNames.Accept, "application/vnd.github.v3+json");
            client.DefaultRequestHeaders.Add(
                HeaderNames.UserAgent, "HttpRequestsSample");
            client.Timeout = TimeSpan.FromSeconds(60); // overall timeout
            // pass config file as second argument in GitHubService constructor
            ActivatorUtilities.CreateInstance<GitHubService>(sp, client, config);
        })
        .AddPolicyHandler(retryPolicy);
        .AddPolicyHandler(timeoutPolicy);
    })
    .Build();
var gitHubService = host.Services.GetRequiredService<GitHubService>();
var gitHubZen = await gitHubService.GetZenAsync();
Console.WriteLine(gitHubZen);
```

In GitHubService.cs:

```csharp
public class GitHubService : IGitHubService
{
    private readonly HttpClient _httpClient;
    // other private fields to populate via config

    public GitHubService(HttpClient httpClient, IConfiguration config)
    {
        _httpClient = httpClient;
        // populate private fields via config
    }

    public async Task<string> GetZenAsync()
    {
        using var response = await _httpClient.GetAsync("/zen");
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadAsStringAsync();
    }
}

public interface IGitHubService
{
}
```
Even if I modified `GetAsync()` to include a `CancellationToken`, where would it come from? Should it be included in the constructor for `GitHubService`?

**Comment by martincostello** [comment]
If you don't have any place to meaningfully provide a `CancellationToken` value to the get request of the `HttpClient`, then an optimistic policy isn't really of much use to you if your overall HTTP timeout is of the order of a minute.

If the intention is to call it from a HTTP request (your code example is calling it like a sort of console app), then you could use [`HttpContext.RequestAborted`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-6.0), which can be automatically provided to MVC actions and Minimal API endpoints automatically by having a `CancellationToken` parameter on the method. This would automatically cancel the request if the client disconnected.

Otherwise the only way to provide a meaningful `CancellationToken` value through to your `HttpClient` is to create one yourself via a source such as [`CancellationTokenSource.Token`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.token?view=net-6.0).

```csharp
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
var gitHubService = host.Services.GetRequiredService<GitHubService>();
var gitHubZen = await gitHubService.GetZenAsync(cts.Token);
```

**Comment by fsgarin-lacity** [comment]
Hi,

Thanks for the super quick response. You are correct that my example (and real world use case that this example is based on) is strictly within the context of a console app that makes HTTP requests as part of an ETL process, so ASP.NET Core is not even in the picture.

Looking at your code sample, it looks like the shorter call timeout is being handled by the creation of a `CancellationToken` based on a 1-second timespan instead of the explicit Timeout policy.  Is my understanding correct?

**Comment by martincostello** [comment]
So in that example, you'd have a 60 second timeout on the `HttpClient`, then a 10 second pessimistic timeout policy with Polly, and then a 1 second timeout from the call site via the `CancellationToken`.

In practice that'd mean your individual requests would time out after 1 second and then do a decorrelated jitter retry until it either exhausted the retries or hit the overall 10 second timeout configured on the timeout policy.

**Comment by martincostello** [comment]
Sorry, you're right, what I wrote was incorrect. The overall timeout would be 1 second if you passed through the `CancellationToken` because the inner policies would "give up" when the cancellation was triggered.

A policy cannot "switch" between pessimistic and optimistic. It's always whatever you specified when you created it, which in your example is optimistic.

For your use case, I'd review what exactly the behaviour you'd expect to be is. The choice of pessimistic vs optimistic is going to be a function of how you want it to retry, if you have client-specified timeouts, or you don't and that's what you want the timeout policy to achieve. It will depend on the relative values of those.

Regarding documentation, we have #853 to update any out-of-date documentation, but the `HttpClientFactory` integration is a bit of a grey area as the implementation is actually in the [ASP.NET Core repo](https://github.com/dotnet/aspnetcore/blob/6ac8ebc38cd43027efb4b2cbb32599befe9a6f60/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L131), and there's further documentation of their own [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) and [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly).

**Comment by fsgarin-lacity** [comment]
> Regarding documentation, we have #853 to update any out-of-date documentation, but the `HttpClientFactory` integration is a bit of a grey area as the implementation is actually in the [ASP.NET Core repo](https://github.com/dotnet/aspnetcore/blob/6ac8ebc38cd43027efb4b2cbb32599befe9a6f60/src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs#L131), and there's further documentation of their own [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) and [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly).

Oof, so that explains why a lot of the documentation regarding `HttpClientFactory` keeps squawking about crap I don't care about such as `PageModel`. My use case is simply just a console app that gets scheduled to run at specific times via Task Manager in Windows Server and needs to communicate to API endpoints via HTTP. I also like the idea of having a **well-behaved** client app that talks to API endpoints, which is how I stumbled upon Polly and `HttpClientFactory`, which solves the exhausted socket and stale DNS issues.

Anyway, I didn't realize until you told me that `CancellationTokenSource.Token` exists. I might just use that for per-call timeouts instead while leaving the other policies in place. I have another use case where the overall timeout in HttpClient is set to 5 minutes and the per-call timeout has to be 1 minute, so I'm guessing that will change the calculus a bit when deciding between pessimistic vs. optimistic.

Thanks for the discussion. As I continue to work through this console app, I'll make note on which parts of the documentation aren't clear and give feedback (if any) to #853.

**Comment by martincostello** [comment]
> I'll make note on which parts of the documentation aren't clear and give feedback (if any) to https://github.com/App-vNext/Polly/issues/853.

Great, thanks!
