### ISSUE TITLE
Exception not being handled

### ISSUE THREAD

**Issue by mihaimyh** [App-vNext/Polly#926]
I am trying to handle a LdapException, not sure why is not working:

![image](https://user-images.githubusercontent.com/549272/154587472-4b0ad9f9-0b36-45be-993a-5934ead96937.png)

**Comment by martincostello** [comment]
In what way is it not working exactly? It is not clear from your issue.

For example, looking at the code screenshot (the text of the code in the issue would be more useful) that could be being thrown of one of the allowable retries, which would be "by design" and not an actual problem.

If your credentials are invalid, are you expecting them to become valid after a certain number of retries? If not it would always fail, exhaust the retries, and throw the final attempt's LdapException to the caller.

**Comment by mihaimyh** [comment]
@martincostello You are right, I don't expect the credentials to be valid, but the problem here is that the retries are not happening. The exception is being thrown at the first attempt.

**Comment by martincostello** [comment]
Things to look at:

1. Is Visual Studio configured to break when an exception is first thrown from user code? I would expect it to be highlighting the `Execute()` call as the source of the exception, not the lambda it's wrapping.
2. Is the `Debug.WriteLine()` call being hit if you continue execution after that exception is thrown? If it is, then retries are indeed being applied.
3. Is the `LdapException` type being handled exactly the same type that's being thrown? Sometimes I've seen issues where two similarly named exceptions exist, and one is being thrown and the other caught. As they aren't the same type, the handling doesn't work. `TimeoutException` is a good example of this kind of problem I've seen in the past.

**Comment by mihaimyh** [comment]
Thanks a lot, the issue was with VS being configured to break on user unhandled exceptions.
