### ISSUE TITLE
Circuit not closing when used in a nested way under concurrent situations

### ISSUE THREAD

**Issue by viveks7** [App-vNext/Polly#933]
**Summary**: 

We are using Polly circuit breaker policy to wrap our calls to Redis cache instace. As part of testing, we noticed that in concurrent situations, incase if the circuit breaker becomes open, it never closes even after the configured breaker duration. Upon close inspection, we found a usage in our code base where we had a method A which was calling method B wrapped in a circuit breaker policy & method B was internally calling redis client method again wrapped in the **same circuit breaker policy**. This was not intended and we removed it. Then onwards we found that circuit breaker was working as expected in the same test, where once the breaker becomes open, it transition to half open and closes as expect with the breaker duration eclipsed. 

I couldn't see any documentation on whether this usage was valid or if this the expected behaviour incase of the such nested calling of the same policy? Can someone clarify?

**Steps / Code to reproduce the problem**: 

1. Create a polly circuit breaker policy
2. Call your I/O logic wrapped in policy.Execute() method
3. Call this wrapped method again nested inside the same policy.Execute() method
4. Call the method in step 3 in concurrent situations
5. Trigger a circuit breaking condition

**Comment by kaiserbergin** [comment]
You're sharing the policy across both calls, which _is_ the issue [(docs).](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#half-open) The circuit breaker only allows ONE call to pass through the breaker in a half open state. So your outer instance of the shared policy lets a call through, but then the inner instance cannot let _another_ call go through in the half open state and returns a "circuit breaker is open". Since your circuit breaker does not handle that exception (most likely based on your config), the circuit remains "half open". That's why the top level request executes (one request goes through), but the inner one blocks because you've _already_ allowed one delegate to execute through the circuit breaker.

If you have nested circuit breakers, you need them to be separate policies.
