### ISSUE TITLE
Compatibility with .NET Framework 3.0

### ISSUE THREAD

**Issue by JosieBigler** [App-vNext/Polly#954]
**Is your feature request related to a specific problem? Or an existing feature? Please describe.**

How difficult would it be to create a version of Polly to be compatible with .NET Framework 3.0?  If it's not a herculean lift I would be willing to do it.  I could not find the commit that is version 4.3.0 of Polly. 

**Describe your proposed or preferred solution**:

Create a version of Polly that will work with .NET framework 3.0 

**Describe any alternative options you've considered**:

I need a reliable web client, I could "create" my own retry mechanics, but it would likely be naive.  

**Any additional info?**

**Comment by martincostello** [comment]
.NET Framework 3.0 has been [out of support since July 12th 2011](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework#:~:text=.NET%20Framework%203.0,Jul%2012%2C%202011), we have no plans to support it in Polly.

If you need to support that version of .NET Framework for some reason, maintaining your own fork would be the best approach.

**Comment by ylr-research** [comment]
Without too much context on the business model. I would suggest, if you're willing to take the time to implement backward-compatibility, I'd rather used that time to upgrade your .NET Framework.

**Comment by JosieBigler** [comment]
I'm definitely going down that route of upgrading.  And it looks _probable_, but it's not a certainty. In the case I can't it'd be nice to be able to use Polly with 3.0.
