### ISSUE TITLE
Share Circuit Breaker state for different return types

### ISSUE THREAD

**Issue by shayvt** [App-vNext/Polly#959]
**I want to share the state of a circuit breaker but for different return types (generics policy)**

As I understood in order to share the state of the circuit breaker I have to use the same policy instance.
But I want also to use the HandleResult which makes my policy Policy<Type>.

I saw this question: https://github.com/App-vNext/Polly/issues/411
But it looks that the suggested code for v6 doesn't exist:

```
ConsecutiveCountCircuitController sharedController = new ConsecutiveCountCircuitController(/* your configuration */);
Policy<StateA> policyA = Policy.HandleResult<StateA>(StateA.Bad).CustomCircuitBreaker(sharedController);
Policy<StateB> policyB = Policy.HandleResult<StateB>(StateB.Unhealthy).CustomCircuitBreaker(sharedController);
```

Is there any solution for this?

Thank you.

**Comment by STARSCrazy** [comment]
It would be extremely helpful if there was this possibility. I am currently writing a library whose methods can be called both synchronously and asynchronously. Therefore I also need the CircuitBreaker in the synchronous and asynchronous variant. But since the same endpoint is protected, the CircuitBreaker must also share its state.

An alternative would be to make at least the three small changes:
1. ConsecutiveCountCircuitController would have to be public.
2. a new extension method for AsyncCircuitBreakerPolicy
`public static AsyncCircuitBreakerPolicy<TResult> CircuitBreakerAsync<TResult>(this PolicyBuilder<TResult> policyBuilder, ConsecutiveCountCircuitController<TResult> controller)`
3. and one for CircuitBreakerPolicy
`public static CircuitBreakerPolicy<TResult> CircuitBreaker<TResult>(this PolicyBuilder<TResult> policyBuilder, ConsecutiveCountCircuitController<TResult> controller)`

That would probably be all.

**Comment by PeterCsalaHbo** [comment]
All of the Controllers are marked as `internal`, so we can't create a new instance of them. That's why there are no methods or overloads where you could provide a controller during the policy setup.

Let me share with you two workarounds:
### Using a `Policy<object>`

You can create a single policy which can return anything (or nothing). 
With this approach you are loosing the strongly typediness but you can share the state. 

It is kinda the same idea what you can do for async methods with  `TaskCompletionSource`:
```cs
TaskCompletionSource<object> tcs = new();
...
tcs.TrySetResult(null); //or simply calling the SetResult
``` 

### Using signaling with `Isolate` and `Reset` calls
Since Polly 4 we have two publicly exposed methods to [control manually the CB's state](https://github.com/App-vNext/Polly/wiki/Circuit-Breaker#manual-control--polly-v40): `Isolate` and `Reset`

If you have two CB policies then you can use the `onBreak` and `onReset` delegates to control the other CB's state
```cs
ICircuitBreakerPolicy<StateA> policyA = Policy<StateA>
    .Handle<Exception>()
    .CircuitBreaker(2, TimeSpan.FromSeconds(5));

var policyB = Policy<StateB>
    .Handle<Exception>()
    .CircuitBreaker(2, TimeSpan.FromSeconds(5),
    onBreak: (_, __) => policyA.Isolate(),
    onReset: policyA.Reset);
```
The problem with this approach that you can't refer directly to `policyB` from `policyA`, because it is defined later. 
But you can do that indirectly via `Context` object.
```cs
public static class ContextExtensions
{
    private static readonly string key = "OtherCB";
    public static Context WithCB<T>(this Context context, ICircuitBreakerPolicy<T> cb)
    {
        context[key] = cb;
        return context;
    }

    public static ICircuitBreakerPolicy<T>? GetCB<T>(this Context context)
    {
        return context.TryGetValue(key, out object logger) ? logger as ICircuitBreakerPolicy<T> : null;
    }
}
```
```cs
var policyA = Policy<StateA>
    .Handle<Exception>()
    .CircuitBreaker(2, TimeSpan.FromSeconds(5),
    onBreak: (_, __, ctx) => ctx.GetCB<StateB>()?.Isolate(),
    onReset: (ctx) => ctx.GetCB<StateB>()?.Reset());

var policyB = Policy<StateB>
    .Handle<Exception>()
    .CircuitBreaker(2, TimeSpan.FromSeconds(5),
    onBreak: (_, __, ctx) => ctx.GetCB<StateA>()?.Isolate(),
    onReset: (ctx) => ctx.GetCB<StateA>()?.Reset());
```
The above code works only for two CBs but can be easily extended to work with any number of CBs.

**Comment by martintmk** [comment]
Hey @shayvt !

This problem is addressed in v8 and issue will be closed when v8 is released.

See how to share the state in this example:
https://github.com/App-vNext/Polly/blob/v8-fixed-issues/src/Polly.Core.Tests/Issues/IssuesTests.CircuitBreakerStateSharing_959.cs


cc @martincostello, @PeterCsalaHbo

**Comment by martintmk** [comment]
The alpha is released, and you can try this out.

https://www.nuget.org/packages/Polly

Closing the issue.
