### ISSUE TITLE
Handle Custom exception with no default constructor

### ISSUE THREAD

**Issue by mehdihadeli** [App-vNext/Polly#968]
How can I Handle Custom exception with no default constructor?

``` csharp
public class IdentityUserNotFoundException : AppException
{
    public IdentityUserNotFoundException(Guid id) : base(
        $"IdentityUser with id '{id}' not found.",
        HttpStatusCode.NotFound)
    {
    }
}
```

**Comment by martincostello** [comment]
What have you tried that doesn't appear to work?

**Comment by mehdihadeli** [comment]
@martincostello I call an external api, and that api has above exception type, I want to catch the same exception type in my api client.

**Comment by martincostello** [comment]
Yes but what have you tried _in code_?

From reading the documentation for Polly, what have you tried to do that doesn't achieve your stated goal?

**Comment by mehdihadeli** [comment]
``` csharp
   var response = await Policy
            .Handle<IdentityUserNotFoundException>()
            .RetryAsync()
            .ExecuteAsync(async () => await _httpClient.GetFromJsonAsync<GetUserByEmailResponse>(
                $"/{_options.UsersEndpoint}/by-email/{email}",
                cancellationToken));
```
This is my code with polly, I think polly can't handle it automatically

**Comment by martincostello** [comment]
And why do you think that? What behaviour are you seeing that makes you think it doesn't work?

Polly just asks you to specify the type via a generic type parameter, so as long as it's a public type it should be catch-able regardless of what constructors it has.

**Comment by mehdihadeli** [comment]
Because `EnsureStatusCode` inner `GetFromJsonAsync` returns `HttpRequestException` exception, and I have to just use this type of exception. maybe this is because of using HttpClient

**Comment by martincostello** [comment]
So in that case you want to handle `HttpRequestException` with a predicate of `exception => exception.InnerException is IdentityUserNotFoundException`?

**Comment by mehdihadeli** [comment]
Yes, Is it possible to get actual exception from the server?

[https://github.com/App-vNext/Polly#handing-return-values-and-policytresult](https://github.com/App-vNext/Polly#handing-return-values-and-policytresult)

Example is not clear here.

**Comment by martincostello** [comment]
Like the final example in the code block in the example in the readme here: https://github.com/App-vNext/Polly#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle

**Comment by martincostello** [comment]
If the _server_ is throwing that exception and you are the _client_ then there's a remote procedure call between you and the exception won't cross the network boundary.

Polly (or any library) won't help you here because the exception is an implementation detail of the server running in a different process.

**Comment by mehdihadeli** [comment]
So handling exception types in polly is not possible in network calls, and I should throw a custom exception In my client based on server app status code.

**Comment by martincostello** [comment]
It's not possible because exceptions are not a concept of HTTP, it's got nothing to do with Polly. The exceptions do not leave the server.

`HttpClient` is seeing a non-2xx status code, treating it as an error, and throwing an exception, in this case `HttpRequestException`.

That is the only exception happening in your process and you need to catch it and deal with it appropriately based on the HTTP status code returned by your server in this scenario.

Ultimately this has got nothing to do with `IdentityNotFoundException` or what constructors it does or doesn't have in the server, because that's invisible to you, the client.
